### ISSUE TITLE
Babel error after clean install npx create-medusa-app@latest

### ISSUE THREAD

**Issue by IanvanZyl636** [medusajs/medusa#5996] opened 2024-01-04 10:59 UTC
Trying to install Madusa for the first time getting a babel error when installation is completed

### System information

Medusa version (including plugins): 1.19.0
Node.js version: 20.10.0
Database: PostgreSQL 16.1.1
Operating system: Windows 10

### Steps to reproduce the behavior

1. run `npx create-medusa-app@latest`
### Expected behavior

Expect the service to start and allow me to log into the admin dashboard

### Screenshots

![image](https://github.com/medusajs/medusa/assets/66467372/3d59cdcf-9b50-4413-9020-c412c9877f83)

![image](https://github.com/medusajs/medusa/assets/66467372/35f431c9-4244-431b-b3d2-c3126654a5c2)

**Comment by OmarMHawash** [comment] 2024-01-04 16:11
already opened and resolved 
 check #5905

**Comment by olivermrbl** [comment] 2024-01-04 19:41
Duplicate of #5905

**Closed as completed by olivermrbl** 2024-01-04 19:41 UTC
Labels: type: bug, status: needs triaging
