### ISSUE TITLE
Discount usage_count isn't incrementing

### ISSUE THREAD

**Issue by edinskeja** [medusajs/medusa#5997] opened 2024-01-04 13:08 UTC
### Describe the bug

The usage_count isn't working for discounts. I had a limit usage on 2 on a discount and it never got that limit since the usage_count didn't increase. It used to work before since i can see that some discounts has redemptions from before and no idea on which version it broke. 

### System information

Medusa version (including plugins): 1.19.0
Node.js version: 20
Database: Postgres
Operating system: Mac
Browser (if relevant): Chrome

### Steps to reproduce the behavior

Make a purchase with discount and check if the redemption count has increased. 

### Expected behavior

usage_count to increase when using discount in order.

**Comment by olivermrbl** [comment] 2024-01-04 15:15
I just created a new project and installed our latest version, and I couldn't reproduce your issue.

Can I get you to provide a reproducible setup?

**Comment by sradevski** [comment] 2024-07-05 11:08
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏

**Closed as completed by sradevski** 2024-07-05 11:08 UTC
Labels: status: needs more
