### ISSUE TITLE
[Bug]: When the order is capture can't refund

### ISSUE THREAD

**Issue by hans642** [medusajs/medusa#10453] opened 2024-12-05 13:23 UTC
### Package.json file

```JSON
{
  "name": "medusa-starter-default",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "dev": "medusa develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "latest",
    "@medusajs/cli": "latest",
    "@medusajs/framework": "latest",
    "@medusajs/medusa": "latest",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "@paypal/checkout-server-sdk": "^1.0.3",
    "awilix": "^8.0.1",
    "liquidjs": "^10.17.0",
    "pg": "^8.13.0"
  },
  "devDependencies": {
    "@medusajs/test-utils": "latest",
    "@mikro-orm/cli": "5.9.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

v20.15.1

### Database and its version

16.4

### Operating system name and version

macOS 15.1

### Browser name

Chrome

### What happended?

When do refund on a Capture order show :
**error:   Order does not have an outstanding balance to refund**

![image](https://github.com/user-attachments/assets/7dfec623-4215-4a5d-94d7-5e176c9d6230)

Check it break in `order.summary?.raw_pending_difference!`, why the Capture order can't refund?

### Expected behavior

Can refund for capture order

### Actual behavior

Can not refund for capture order

### Link to reproduction repo

medusa(v2)

**Comment by olivermrbl** [comment] 2024-12-05 14:22
Duplicate of #10392

**Closed as completed by olivermrbl** 2024-12-05 14:22 UTC
Labels: status: needs triaging, version: 2.0
