### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Gevork-Sarkisyan222** [medusajs/medusa#8639] opened 2024-08-17 11:18 UTC
### What Medusa version and documentation are you using?

None

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Server Error TypeError: Failed to parse URL from undefined/store/regions

This error happened while generating the page. Any console logs will be displayed in the terminal window. Source src\middleware.ts (21:30) @ fetch

19 | ) { 20 | // Fetch regions from Medusa. We can't use the JS client here because middleware is running on Edge and the client needs a Node environment.

21 | const { regions } = await fetch(${BACKEND_URL}/store/regions, { | ^ 22 | next: { 23 | revalidate: 3600, 24 | tags: ["regions"]

backend url is not fetching in the from nextjs storefront to medusa backend

### How can this issue be resolved?

1. I put in env file a NEXT_PUBLIC_MEDUSA_BACKEND_URL
2. I restart my app
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by srindom** [comment] 2024-08-19 08:23
Unclear what the problem is here. `Failed to parse URL from undefined/store/regions` would indicate that your env var wasn't properly defined. Closing for now

**Closed as completed by srindom** 2024-08-19 08:23 UTC
Labels: type: docs
