### ISSUE TITLE
mpath is not returned when doing any of the product-categories fetches

### ISSUE THREAD

**Issue by chemicalkosek** [medusajs/medusa#5694] opened 2023-11-22 18:47 UTC
### Describe the bug

`mpath` for product categories is not returned.

### System information

Medusa version (including plugins): 1.17.3
Node.js version: 18
Database: postgres

### Steps to reproduce the behavior

1. Use any of below endpoints:
`GET /store/product-categories`
`GET /store/product-categories/[categoryId]`
`GET /store/products?expand=categories`
2. See `mpath` is not returned

### Expected behavior

`mpath` is in the response

**Comment by olivermrbl** [comment] 2023-11-26 16:18
@riqwan, would you be able to help @chemicalkosek? :)

**Comment by riqwan** [comment] 2023-11-27 10:17
Hey @chemicalkosek, this is unfortunately due to a limitation in typeorm. mpath is a virtual field and therefore doesn't return in the response.

You can extend the product-category service to circumvent this:

1. [Extend](https://docs.medusajs.com/development/services/extend-service) the ProductCategory service and add this in the constructor:

```
this.productCategoryRepo_.metadata.columns =
  this.productCategoryRepo_.metadata.columns.map((column) => {
    if (column.databaseName === "mpath") {
      column.isVirtual = false
    }

    return column
  })
```

2. Extend the `allowedStoreProductCategoryFields` and `defaultStoreProductCategoryFields` to add `mpath` in the array.

You should now receive mpath in the API. I've created a quick test here - https://github.com/medusajs/medusa/compare/feat/allow-mpath-categories?expand=1

Let me know if you come across any issues.

**Comment by riqwan** [comment] 2023-12-18 09:07
Closing this for now @chemicalkosek, feel free to reopen if this didn't work

**Closed as completed by riqwan** 2023-12-18 09:07 UTC
Labels: type: bug
