### ISSUE TITLE
Unable to build Medusajs v2 with Digital Products Recipe

### ISSUE THREAD

**Issue by 420coupe** [medusajs/medusa#9877] opened 2024-10-30 22:21 UTC
### Describe the bug

After the latest pull of rc, i cannot build the medusajs backend that has the digital product recipe implemented. 

### System information

Medusa version (including plugins): 
```ts
├─ @medusajs/admin-bundler@2.0.0-rc-20241022183311
├─ @medusajs/admin-sdk@2.0.0-rc-20241022183311
├─ @medusajs/admin-shared@2.0.0-rc-20241022183311
├─ @medusajs/admin-vite-plugin@2.0.0-rc-20241022183311
├─ @medusajs/api-key@2.0.0-rc-20241022183311
├─ @medusajs/auth-emailpass@2.0.0-rc-20241022183311
├─ @medusajs/auth-github@2.0.0-rc-20241022183311
├─ @medusajs/auth-google@2.0.0-rc-20241022183311
├─ @medusajs/auth@2.0.0-rc-20241022183311
├─ @medusajs/cache-inmemory@2.0.0-rc-20241022183311
├─ @medusajs/cache-redis@2.0.0-rc-20241022183311
├─ @medusajs/cart@2.0.0-rc-20241022183311
├─ @medusajs/cli@2.0.0-rc-20241022183311
├─ @medusajs/core-flows@2.0.0-rc-20241022183311
├─ @medusajs/currency@2.0.0-rc-20241022183311
├─ @medusajs/customer@2.0.0-rc-20241022183311
├─ @medusajs/dashboard@2.0.0-rc-20241022183311
├─ @medusajs/event-bus-local@2.0.0-rc-20241022183311
├─ @medusajs/event-bus-redis@2.0.0-rc-20241022183311
├─ @medusajs/file-local@2.0.0-rc-20241022183311
├─ @medusajs/file-s3@2.0.0-rc-20241022183311
├─ @medusajs/file@2.0.0-rc-20241022183311
├─ @medusajs/framework@2.0.0-rc-20241022183311
├─ @medusajs/fulfillment-manual@2.0.0-rc-20241022183311
├─ @medusajs/fulfillment@2.0.0-rc-20241022183311
├─ @medusajs/icons@2.0.0-rc-20241022183311
├─ @medusajs/index@2.0.0-rc-20241022183311
├─ @medusajs/inventory@2.0.0-rc-20241022183311
├─ @medusajs/js-sdk@2.0.0-rc-20241022183311
├─ @medusajs/link-modules@2.0.0-rc-20241022183311
├─ @medusajs/locking-postgres@2.0.0-rc-20241022183311
├─ @medusajs/locking-redis@2.0.0-rc-20241022183311
├─ @medusajs/locking@2.0.0-rc-20241022183311
├─ @medusajs/medusa@2.0.0-rc-20241022183311
├─ @medusajs/modules-sdk@2.0.0-rc-20241022183311
├─ @medusajs/notification-local@2.0.0-rc-20241022183311
├─ @medusajs/notification-sendgrid@2.0.0-rc-20241022183311
├─ @medusajs/notification@2.0.0-rc-20241022183311
├─ @medusajs/orchestration@2.0.0-rc-20241022183311
├─ @medusajs/order@2.0.0-rc-20241022183311
├─ @medusajs/payment-stripe@2.0.0-rc-20241022183311
├─ @medusajs/payment@2.0.0-rc-20241022183311
├─ @medusajs/pricing@2.0.0-rc-20241022183311
├─ @medusajs/product@2.0.0-rc-20241022183311
├─ @medusajs/promotion@2.0.0-rc-20241022183311
├─ @medusajs/region@2.0.0-rc-20241022183311
├─ @medusajs/sales-channel@2.0.0-rc-20241022183311
├─ @medusajs/stock-location@2.0.0-rc-20241022183311
├─ @medusajs/store@2.0.0-rc-20241022183311
├─ @medusajs/tax@2.0.0-rc-20241022183311
├─ @medusajs/telemetry@2.0.0-rc-20241022183311
├─ @medusajs/test-utils@2.0.0-rc-20241022183311
├─ @medusajs/types@2.0.0-rc-20241022183311
├─ @medusajs/ui@4.0.0-rc-20241022183311
├─ @medusajs/user@2.0.0-rc-20241022183311
├─ @medusajs/utils@2.0.0-rc-20241022183311
├─ @medusajs/workflow-engine-inmemory@2.0.0-rc-20241022183311
├─ @medusajs/workflow-engine-redis@2.0.0-rc-20241022183311
└─ @medusajs/workflows-sdk@2.0.0-rc-20241022183311
```
Node.js version: ``v21.7.1``
Database: ``Supabse (postgres)``
Operating system: ``Ubuntu 22.04.4 LTS``
Browser (if relevant):

### Steps to reproduce the behavior

1. Stand up medusajs v2 backend
2. implement digital products recipe
3. run yarn build

### Expected behavior

Should be able to build the app with no errors, this implementation was previously working with prior RCs. 

### Screenshots

![image](https://github.com/user-attachments/assets/487f96eb-57d9-455c-b6fc-361a41eaa278)

### Code Snippet

`src/workflows/fulfill-digital-order/index.ts`
```ts
import {
  createWorkflow,
  WorkflowResponse,
} from "@medusajs/framework/workflows-sdk";
import { useRemoteQueryStep } from "@medusajs/medusa/core-flows";
import { sendDigitalOrderNotificationStep } from "./steps/send-digital-order-notification";

type FulfillDigitalOrderWorkflowInput = {
  id: string;
};

export const fulfillDigitalOrderWorkflow = createWorkflow(
  "fulfill-digital-order",
  ({ id }: FulfillDigitalOrderWorkflowInput) => {
    const digitalProductOrder = useRemoteQueryStep({
      entry_point: "digital_product_order",
      fields: [
        "*",
        "products.*",
        "products.medias.*",
        "order.*",
        "order.fulfillments.*",
      ],
      variables: {
        filters: {
          id,
        },
      },
      list: false,
      throw_if_key_not_found: true,
    });

    sendDigitalOrderNotificationStep({
      digital_product_order: digitalProductOrder,
    });

    return new WorkflowResponse(digitalProductOrder);
  }
);
```

`src/workflows/fulfill-digital-order/steps/send-digital-order-notification.ts`

```ts
import { createStep, StepResponse } from "@medusajs/framework/workflows-sdk";
import {
  INotificationModuleService,
  IFileModuleService,
  IOrderModuleService,
  IFulfillmentModuleService,
} from "@medusajs/framework/types";
import { Modules } from "@medusajs/framework/utils";
import {
  DigitalProductOrder,
  MediaType,
  OrderStatus,
} from "../../../modules/digital-product/types";
import DigitalProductModuleService from "../../../modules/digital-product/service";
import { DIGITAL_PRODUCT_MODULE } from "../../../modules/digital-product";

type SendDigitalOrderNotificationStepInput = {
  digital_product_order: DigitalProductOrder;
};

export const sendDigitalOrderNotificationStep = createStep(
  "send-digital-order-notification",
  async (
    {
      digital_product_order: digitalProductOrder,
    }: SendDigitalOrderNotificationStepInput,
    { container }
  ) => {
    const notificationModuleService: INotificationModuleService =
      container.resolve(Modules.NOTIFICATION);
    const fileModuleService: IFileModuleService = container.resolve(
      Modules.FILE
    );
    const orderModuleService: IOrderModuleService = container.resolve(
      Modules.ORDER
    );
    const digitalProductModuleService: DigitalProductModuleService =
      container.resolve(DIGITAL_PRODUCT_MODULE);
    const fulfillmentModuleService: IFulfillmentModuleService =
      container.resolve(Modules.FULFILLMENT);

    const order = await orderModuleService.retrieveOrder(
      digitalProductOrder.order.id,
      {
        select: ["total"],
        relations: ["billing_address.*"],
      }
    );

    const formatCurrency = (
      value: any,
      isDiscount: boolean = false
    ): string => {
      const numberValue = Number(value);
      if (isDiscount && numberValue === 0) {
        return "";
      }
      return numberValue.toFixed(2);
    };

    const capitalizeFirstLetter = (string: string): string => {
      if (!string) return string;
      return string.charAt(0).toUpperCase() + string.slice(1).toLowerCase();
    };

    const formatPhoneNumber = (phone: string): string => {
      const cleaned = ("" + phone).replace(/\D/g, "");

      if (cleaned.length === 10) {
        // Format the phone number as (XXX) XXX-XXXX
        return `(${cleaned.substring(0, 3)}) ${cleaned.substring(
          3,
          6
        )}-${cleaned.substring(6)}`;
      } else if (cleaned.length > 10) {
        // Handle other country codes or phone number formats
        return `+${cleaned.substring(
          0,
          cleaned.length - 10
        )} ${cleaned.substring(
          cleaned.length - 10,
          cleaned.length - 7
        )}-${cleaned.substring(
          cleaned.length - 7,
          cleaned.length - 4
        )}-${cleaned.substring(cleaned.length - 4)}`;
      }
      return phone;
    };

    const notificationData = await Promise.all(
      digitalProductOrder.products.map(async (product) => {
        const medias = [];
        const attachments = [];

        await Promise.all(
          product.medias
            .filter((media) => media.type === MediaType.MAIN)
            .map(async (media) => {
              const file = await fileModuleService.retrieveFile(media.fileId);
              const filename =
                media.fileId ||
                decodeURIComponent(
                  file.url.split("/").pop()?.split("?")[0] ||
                    "default_filename.png"
                );
              const fileBuffer = await fetch(file.url).then((res) =>
                res.arrayBuffer()
              );

              const base64File = Buffer.from(fileBuffer).toString("base64");
              medias.push(file.url);
              attachments.push({
                content: base64File,
                filename,
                type: media.mimeType,
                disposition: "attachment",
              });
            })
        );

        return {
          name: product.name,
          medias,
          attachments,
        };
      })
    );

    const notification = await notificationModuleService.createNotifications({
      to: digitalProductOrder.order.email,
      template: "dynamic-Id",
      channel: "email",
      attachments: notificationData.flatMap((product) => product.attachments),
      data: {
        digitalProductOrder: digitalProductOrder,
        siteName: process.env.SITE_NAME,
        siteURL: process.env.SITE_URL,
        orderNumber: digitalProductOrder.order.display_id,
        products: order.items.map((item) => ({
          name: item.title,
          subtitle: item.subtitle,
          description: item.product_description,
          quantity: item.quantity,
          price: formatCurrency(item.unit_price),
          url: item.product_handle,
          image: item.thumbnail,
        })),
        billing: {
          name: `${capitalizeFirstLetter(
            order.billing_address.first_name
          )} ${capitalizeFirstLetter(order.billing_address.last_name)}`,
          address_1: order.billing_address.address_1,
          address_2: order.billing_address.address_2,
          city: capitalizeFirstLetter(order.billing_address.city),
          country_code: order.billing_address.country_code.toUpperCase(),
          province: order.billing_address.province.toUpperCase(),
          postal_code: order.billing_address.postal_code,
          phone: formatPhoneNumber(order.billing_address.phone),
        },
        subTotal: formatCurrency(order.subtotal),
        discount: formatCurrency(order.discount_subtotal, true),
        shipping: formatCurrency(order.shipping_total),
        taxes: formatCurrency(order.tax_total),
        orderTotal: formatCurrency(order.total),
        subject: `Order #${digitalProductOrder.order.display_id} Confirmation`,
      },
    });

    const updateDigitalProductOrder =
      await digitalProductModuleService.updateDigitalProductOrders({
        id: digitalProductOrder.id,
        status: OrderStatus.SENT,
      });

    const fulfillmentDelivered =
      await fulfillmentModuleService.updateFulfillment(
        digitalProductOrder.order.fulfillments[0].id,
        { delivered_at: new Date().toISOString() }
      );

    return new StepResponse(notification);
  }
);
```

**Comment by 420coupe** [comment] 2024-10-30 23:14
So upon some further digging looks like the `display_id` is missing from `OrderDTO` and `attachments` from `CreateNotificationDTO`

`packages/core/types/src/notification/mutation.ts`
```ts
import { Attachment} from "./common"
export interface CreateNotificationDTO {
// ...other code
/**
* the attachments that get passed to provider
*/
attachments?:  Attachment[] | null;
}
```
`packages/core/types/src/order/common.ts`
```ts
export interface OrderDTO {
//... other code
/**
* The order's display ID.
*/
 display_id: number;
 }
 ```

**Comment by 420coupe** [comment] 2024-10-31 01:39
I got it to build with `// @ts-expect-error` flags but now attachments are not sending correctly. They show in the message but the data is not attached correctly.

This code was working prior to updating to latest RC.

**Comment by 420coupe** [comment] 2024-10-31 02:10
I got it to build with `// @ts-expect-error` flags but think these should be added to the core interfaces so it doesnt throw TS errors on build.

**Comment by shahednasser** [comment] 2024-11-11 08:32
Hey @420coupe just tried reproducing this, didn't get any errors. Can you try using `latest` versions instead of `rc`?

**Comment by sradevski** [comment] 2024-11-22 13:15
Closing this as we couldn't reproduce, please let us know if it's still an issue

**Closed as completed by sradevski** 2024-11-22 13:15 UTC
