### ISSUE TITLE
[Bug]: Password reset email not being sent

### ISSUE THREAD

**Issue by homosape** [medusajs/medusa#10682] opened 2024-12-20 09:20 UTC
### Package.json file

```JSON
{
  "name": "qnari-commerce",
  "version": "0.0.1",
  "author": "Nari Solutions",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "dev": "medusa develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "^2.1.0",
    "@medusajs/cli": "^2.1.0",
    "@medusajs/framework": "^2.1.0",
    "@medusajs/medusa": "^2.1.0",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "awilix": "^8.0.1",
    "medusa-plugin-auth": "^1.11.1",
    "pg": "^8.13.0",
    "zod": "^3.22"
  },
  "devDependencies": {
    "@medusajs/test-utils": "^2.1.0",
    "@mikro-orm/cli": "5.9.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.6.2",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  },
  "packageManager": "yarn@1.22.22+sha512.a6b2f7906b721bba3d67d4aff083df04dad64c399707841b7acf00f6b133b7ac24255f2652fa22ae3534329dc6180534e98d17432037ff6fd140556e2bb3137e"
}
```

### Node.js version

v22.11.0

### Database and its version

supabase

### Operating system name and version

MacOS Sequoia 15.2

### What happended?

I've implemented Sendgrid Notification Module provider according [this documentation](https://docs.medusajs.com/resources/architectural-modules/notification/sendgrid).

I've subscribed to password reset according [this documentation](https://docs.medusajs.com/resources/commerce-modules/auth/reset-password#main).

The problem is that it never sends email.

My subscriber `src/password-reset.ts`
```
import { SubscriberArgs, type SubscriberConfig } from "@medusajs/medusa";
import { Modules } from "@medusajs/framework/utils";

export default async function resetPasswordTokenHandler({
  event: {
    data: { entity_id: email, token, actor_type },
  },
  container,
}: SubscriberArgs<{ entity_id: string; token: string; actor_type: string }>) {
  const notificationModuleService = container.resolve(Modules.NOTIFICATION);

  const urlPrefix =
    actor_type === "customer"
      ? process.env.MEDUSA_STOREFRONT_URL
      : process.env.MEDUSA_BACKEND_URL;
  const url = `${urlPrefix}/callback?action=passwordReset&token=${token}&email=${email}`;

  console.log("Trigger Sendgrid Notification Module");

  await notificationModuleService.createNotifications({
    to: email,
    channel: "email",
    content: {
      html: `
        <!DOCTYPE html>
        <html lang="en">
          <head>
            <meta charset="UTF-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            <title>Password reset</title>
          </head>
          <body>
            <h1>You've requested password reset</h1>
            <a href=${url} target="_blank">Click here</a>
          </body>
        </html>
      `,
    },
    template: "n/a",
  });
}

export const config: SubscriberConfig = {
  event: "auth.password_reset",
};
```

It doesn't even log the message `Trigger Sendgrid Notification Module` when I call reset password endpoint.

My modules in `medusa.config.ts`
```
  modules: [
    {
      resolve: "@medusajs/medusa/payment",
      options: {
        providers: [
          {
            resolve: "./src/modules/bog",
            id: "bog-payment",
          },
        ],
      },
    },
    {
      resolve: "./src/modules/marketplace",
    },
    {
      resolve: "@medusajs/medusa/notification",
      options: {
        providers: [
          {
            resolve: "@medusajs/medusa/notification-sendgrid",
            id: "sendgrid",
            options: {
              channels: ["email"],
              api_key: process.env.SENDGRID_API_KEY,
              from: process.env.SENDGRID_FROM,
            },
          },
        ],
      },
    },
    // {
    //   resolve: "@medusajs/medusa/cache-redis",
    //   options: {
    //     redisUrl: process.env.REDIS_URL,
    //   },
    // },
    // {
    //   resolve: "@medusajs/medusa/event-bus-redis",
    //   options: {
    //     redisUrl: process.env.REDIS_URL,
    //   },
    // },
    // {
    //   resolve: "@medusajs/medusa/workflow-engine-redis",
    //   options: {
    //     redis: {
    //       url: process.env.REDIS_URL,
    //     },
    //   },
    // },
  ],
```

### Expected behavior

It should send emails.

### Actual behavior

No email is sent.

### Link to reproduction repo

n/a

**Comment by olivermrbl** [comment] 2024-12-20 09:43
It sounds like your subscriber might not be registered correctly. If you provide a minimum reproduction in a repository, we can take a look at it.

**Comment by olivermrbl** [comment] 2024-12-20 09:43
Just be sure, have you located your subscribers in `src/subscribers`? They are only loaded from within this folder.

**Comment by homosape** [comment] 2024-12-20 09:53
@olivermrbl  https://github.com/homosape/medusa-demo

**Comment by olivermrbl** [comment] 2024-12-20 11:38
@homosape, I am not allowed to clone the repo. Could you grant me read access?

**Comment by homosape** [comment] 2024-12-20 14:25
@olivermrbl i've added you as contributor

**Comment by olivermrbl** [comment] 2024-12-20 16:04
@homosape, I cloned your repro, ran `yarn install`, and tried to reset my password. The subscriber ran fine. 

Below are the logs:

![CleanShot 2024-12-20 at 17 02 48](https://github.com/user-attachments/assets/e3028113-12f5-4263-9d44-ebcb19919111)

The error you are seeing is because I don't have SendGrid configured, but you can see the console.log from the subscriber handler function.

Closing until reproducible steps are confirmed.

**Closed as completed by olivermrbl** 2024-12-20 16:04 UTC
Labels: status: needs more, version: 2.0

**Comment by homosape** [comment] 2024-12-23 07:35
@olivermrbl  this is what i get
<img width="1088" alt="Screenshot 2024-12-23 at 11 34 55" src="https://github.com/user-attachments/assets/20fc3b33-f5f9-4a9c-9aca-43ff0838c487" />

**Comment by AyushChauhan9389** [comment] 2025-01-03 21:08
> @homosape, I cloned your repro, ran `yarn install`, and tried to reset my password. The subscriber ran fine. 
> 
> Below are the logs:
> 
> ![CleanShot 2024-12-20 at 17 02 48](https://github.com/user-attachments/assets/e3028113-12f5-4263-9d44-ebcb19919111)
> 
> The error you are seeing is because I don't have SendGrid configured, but you can see the console.log from the subscriber handler function.
> 
> Closing until reproducible steps are confirmed.

I am seeing same error of password _ reset not initing

**Comment by SalahAdDin** [comment] 2025-01-04 19:42
> > @homosape, I cloned your repro, ran `yarn install`, and tried to reset my password. The subscriber ran fine.
> > Below are the logs:
> > ![CleanShot 2024-12-20 at 17 02 48](https://private-user-images.githubusercontent.com/59018053/397795028-e3028113-12f5-4263-9d44-ebcb19919111.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYwMTgxMjEsIm5iZiI6MTczNjAxNzgyMSwicGF0aCI6Ii81OTAxODA1My8zOTc3OTUwMjgtZTMwMjgxMTMtMTJmNS00MjYzLTlkNDQtZWJjYjE5OTE5MTExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA0VDE5MTAyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3NmFiODgzYWNiMzAzYWRkMDc3YzhiNWE3YTc2MzQ3MzM5ODI1Nzg1YjQ3ODViYmMzYmRlM2M3MWFkZjUxNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cKeXpwasr_wuQZ8gylktRyBzQpPaNfMZy5CFqYA9vV8)
> > The error you are seeing is because I don't have SendGrid configured, but you can see the console.log from the subscriber handler function.
> > Closing until reproducible steps are confirmed.
> 
> I am seeing same error of password _ reset not initing

add the track log and the reproduction steps here, please.

**Comment by AyushChauhan9389** [comment] 2025-01-04 19:59
> > > @homosape, I cloned your repro, ran `yarn install`, and tried to reset my password. The subscriber ran fine.
> > > Below are the logs:
> > > ![CleanShot 2024-12-20 at 17 02 48](https://private-user-images.githubusercontent.com/59018053/397795028-e3028113-12f5-4263-9d44-ebcb19919111.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYwMTgxMjEsIm5iZiI6MTczNjAxNzgyMSwicGF0aCI6Ii81OTAxODA1My8zOTc3OTUwMjgtZTMwMjgxMTMtMTJmNS00MjYzLTlkNDQtZWJjYjE5OTE5MTExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA0VDE5MTAyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3NmFiODgzYWNiMzAzYWRkMDc3YzhiNWE3YTc2MzQ3MzM5ODI1Nzg1YjQ3ODViYmMzYmRlM2M3MWFkZjUxNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cKeXpwasr_wuQZ8gylktRyBzQpPaNfMZy5CFqYA9vV8)
> > > The error you are seeing is because I don't have SendGrid configured, but you can see the console.log from the subscriber handler function.
> > > Closing until reproducible steps are confirmed.
> > 
> > I am seeing same error of password _ reset not initing
> 
> add the track log and the reproduction steps here, please.

I fixed it . Idk how but when i deleted .medusa folder and did build again it wirked

**Comment by Grsmto** [comment] 2025-10-02 22:43
Having the same issue with latest version. Getting notifications from other events but just `auth.password_reset` not kicking in from both storefront API call and admin...Anyone found a solution?
