### ISSUE TITLE
Can't test a custom plugin

### ISSUE THREAD

**Issue by RickCastle2018** [medusajs/medusa#3234] opened 2023-02-09 22:40 UTC
### Describe the bug

I am currently creating a plugin for Medusa. All the steps from https://docs.medusajs.com/advanced/backend/plugins/create are working, except for the actual testing of the plugin. It just won't run throwing off well-known Error: The class must be a valid service implementation. The troubleshoot instructions do not help unfortunately.

### System information

Medusa version (including plugins): 1.6.0
Node.js version: 14
Database: default
Operating system: Mac OS Ventura (M2 MacBook air)
Browser (if relevant):

### Steps to reproduce the behavior

Try to follow all the steps from tutorial. No matter what service you create you are getting the same error

### Expected behavior

The tutorial from the documentation should be working.

Please, tell me what can be done

**Comment by jono-allen** [comment] 2023-02-13 04:19
@RickCastle2018 do you have the medusa-extender installed? Im getting this error on my server which has the extender installed but it works on a fresh install of medusa

**Comment by olivermrbl** [comment] 2023-02-13 07:42
Are you extending the `TransactionBaseService` from `@medusajs/medusa` or the `BaseService` from `medusa-interfaces`? It is required for our loaders to identify your service classes.

Closing for now until further details are shared.

**Closed by olivermrbl** 2023-02-13 07:42 UTC
Labels: type: bug, status: needs triaging

**Comment by jono-allen** [comment] 2023-02-13 07:54
I can confirm mine was due to a mismatched version of `medusa-interfaces` in my case causing this error to be raised.  @RickCastle2018  Try upgrading `@medusajs/medusa` and `medusa-interface` to the latest versions. 
If the error continues reach out in `help` on discord.

**Comment by olivermrbl** [comment] 2023-02-13 07:55
Thanks for pitching in @jono-allen 🙏
