### ISSUE TITLE
[Bug]: Field(s) are required to have value to continue - sales_channel_id

### ISSUE THREAD

**Issue by mohamadfala** [medusajs/medusa#10597] opened 2024-12-13 07:33 UTC
### Package.json file

```JSON
{
	"name": "project",
	"version": "0.0.1",
	"license": "MIT",
	"keywords": [
		"sqlite",
		"postgres",
		"typescript",
		"ecommerce",
		"headless",
		"medusa"
	],
	"scripts": {
		"build": "medusa build",
		"seed": "medusa exec ./src/scripts/seed.ts",
		"start": "medusa start",
		"dev": "medusa develop",
		"test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
		"test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
		"test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
	},
	"dependencies": {
		"@medusajs/admin-sdk": "2.1.1",
		"@medusajs/cli": "2.1.1",
		"@medusajs/framework": "2.1.1",
		"@medusajs/medusa": "2.1.1",
		"@mikro-orm/core": "5.9.7",
		"@mikro-orm/knex": "5.9.7",
		"@mikro-orm/migrations": "5.9.7",
		"@mikro-orm/postgresql": "5.9.7",
		"awilix": "^8.0.1",
		"pg": "^8.13.0",
		"@medusajs/js-sdk": "2.1.1",
		"moment": "^2.30.1",
		"pdfkit": "^0.15.1"
	},
	"devDependencies": {
		"@medusajs/test-utils": "2.1.1",
		"@mikro-orm/cli": "5.9.7",
		"@swc/core": "1.5.7",
		"@swc/jest": "^0.2.36",
		"@types/jest": "^29.5.13",
		"@types/node": "^20.0.0",
		"@types/react": "^18.3.2",
		"@types/react-dom": "^18.2.25",
		"jest": "^29.7.0",
		"prop-types": "^15.8.1",
		"react": "^18.2.0",
		"react-dom": "^18.2.0",
		"ts-node": "^10.9.2",
		"typescript": "^5.6.2",
		"vite": "^5.2.11"
	},
	"engines": {
		"node": ">=20"
	}
}
```

### Node.js version

v20.16.0

### Database and its version

PostgreSQL 16.4

### Operating system name and version

Windows 11

### Browser name

Chrome

### What happended?

Accessing the checkout page on the medusa nextjs starter template throws the following error in the backend:

error:   Field(s) are required to have value to continue - sales_channel_id
{
  message: 'Field(s) are required to have value to continue - sales_channel_id',
  name: 'Error',
  stack: 'Error: Field(s) are required to have value to continue - sales_channel_id\n' +
    '    at Object.<anonymous> (C:\\Users\\mfa\\Projects\\PG\\backend\\node_modules\\@medusajs\\core-flows\\src\\common\\steps\\validate-presence-of.ts:27:13)\n' +
    '    at Object.invoke (C:\\Users\\mfa\\Projects\\PG\\backend\\node_modules\\@medusajs\\workflows-sdk\\src\\utils\\composer\\helpers\\create-step-handler.ts:72:67)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DistributedTransaction.handler (C:\\Users\\mfa\\Projects\\PG\\backend\\node_modules\\@medusajs\\orchestration\\src\\workflow\\workflow-manager.ts:214:16)\n' +
    '    at async stepHandler (C:\\Users\\mfa\\Projects\\PG\\backend\\node_modules\\@medusajs\\orchestration\\src\\transaction\\transaction-orchestrator.ts:827:20)\n' +
    '    at async Promise.allSettled (index 0)\n' +
    '    at async promiseAll (C:\\Users\\mfa\\Projects\\PG\\backend\\node_modules\\@medusajs\\utils\\src\\common\\promise-all.ts:27:18)\n' +
    '    at async TransactionOrchestrator.executeNext (C:\\Users\\mfa\\Projects\\PG\\backend\\node_modules\\@medusajs\\orchestration\\src\\transaction\\transaction-orchestrator.ts:965:7)\n' +
    '    at async executeNext (C:\\Users\\mfa\\Projects\\PG\\backend\\node_modules\\@medusajs\\orchestration\\src\\transaction\\transaction-orchestrator.ts:1013:14)\n' +
    '    at async TransactionOrchestrator.resume (C:\\Users\\mfa\\Projects\\PG\\backend\\node_modules\\@medusajs\\orchestration\\src\\transaction\\transaction-orchestrator.ts:1028:5)\n' +
    '    at async LocalWorkflow.run (C:\\Users\\mfa\\Projects\\PG\\backend\\node_modules\\@medusajs\\orchestration\\src\\workflow\\local-workflow.ts:371:5)\n' +
    '    at async originalExecution (C:\\Users\\mfa\\Projects\\PG\\backend\\node_modules\\@medusajs\\workflows-sdk\\src\\helper\\workflow-export.ts:111:26)\n' +
    '    at async LocalWorkflow.newRun [as run] (C:\\Users\\mfa\\Projects\\PG\\backend\\node_modules\\@medusajs\\workflows-sdk\\src\\helper\\workflow-export.ts:190:12)\n' +
    '    at async GET (C:\\Users\\mfa\\Projects\\PG\\backend\\node_modules\\@medusajs\\medusa\\src\\api\\store\\shipping-options\\route.ts:12:40)\n' +
    '    at async C:\\Users\\mfa\\Projects\\PG\\backend\\node_modules\\@medusajs\\utils\\src\\common\\wrap-handler.ts:17:14\n' +
    '⮑ sat C:\\Users\\mfa\\Projects\\PG\\backend\\node_modules\\@medusajs\\core-flows\\dist\\cart\\workflows\\list-shipping-options-for-cart.js: [list-shipping-options-for-cart -> validate-presence-of (invoke)]',
  __isMedusaError: true,
  type: 'invalid_data',
  code: undefined,
  date: 2024-12-13T07:17:33.210Z
}
http:    GET /store/shipping-options?cart_id=cart_01JEZDNBSY32NMXMXTJPQA1FRJ ← - (400) - 13.987 ms

### Expected behavior

Should return cart shipping options

### Actual behavior

Not returning cart shipping options

### Link to reproduction repo

#

**Comment by riqwan** [comment] 2024-12-13 12:27
Hey @mohamadfala, can you run this on your db and paste the output?  `select default_sales_channel_id from store;`

**Comment by mohamadfala** [comment] 2024-12-13 12:30
> Hey @mohamadfala, can you run this on your db and paste the output? `select default_sales_channel_id from store;`

Hello @riqwan here's the output:
![image](https://github.com/user-attachments/assets/aa65fb9b-6b27-4765-a307-9552de3f25f3)

**Comment by riqwan** [comment] 2024-12-13 12:32
thanks, just to confirm, can you also paste the result of this:

`select id, deleted_at from sales_channel;`

This should have worked. Can you clear your browser cookies and try again?

**Comment by mohamadfala** [comment] 2024-12-13 12:34
> thanks, just to confirm:
> 
> `select id, deleted_at from sales_channel;`
> 
> This should have worked. Can you clear your browser cookies and try again?

@riqwan 
![image](https://github.com/user-attachments/assets/bec11609-0f54-417e-b5fc-60558056ef9d)

I also tried clearing cookies. lots of api requests throwing the same error.
for example fetching shipping methods, adding to cart, removing from cart...

**Comment by mohamadfala** [comment] 2024-12-13 12:36
@riqwan I think clearing the cookies again did the job.
Not sure why its fixed now.

Any explanation?

**Comment by riqwan** [comment] 2024-12-13 12:39
The cart that was initially created probably was created before the default store was created. Can't think of another reason why this could've been the case. 

If you come across this again, make sure to record that steps you did before you ended up in that spot. It'll help us debug better. 

In the meantime, i'll create a ticket for us to make the sales_channel_id a required property so we don't end up in this spot. 

Feel free to ping again when you come across this. Closing for now! 🙇🏻

**Closed as completed by riqwan** 2024-12-13 12:39 UTC
Labels: status: needs triaging, version: 2.0

**Comment by mohamadfala** [comment] 2025-01-03 10:46
Hello again @riqwan the issue is happening again out of nowhere.
I've tried clearing application data, cookies, hard reload multiple times and its persistent. 

![image](https://github.com/user-attachments/assets/20849b94-4059-4e48-b7b8-b966dfa5a274)

```
error:   Field(s) are required to have value to continue - sales_channel_id
{
  message: 'Field(s) are required to have value to continue - sales_channel_id',
  name: 'Error',
  stack: 'Error: Field(s) are required to have value to continue - sales_channel_id\n' +
    '    at Object.<anonymous> (C:\\Users\\mfa\\Projects\\PG\\backend\\node_modules\\@medusajs\\core-flows\\src\\common\\steps\\validate-presence-of.ts:27:13)\n' +
    '    at Object.invoke (C:\\Users\\mfa\\Projects\\PG\\backend\\node_modules\\@medusajs\\workflows-sdk\\src\\utils\\composer\\helpers\\create-step-handler.ts:72:67)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n' +
    '    at async DistributedTransaction.handler (C:\\Users\\mfa\\Projects\\PG\\backend\\node_modules\\@medusajs\\orchestration\\src\\workflow\\workflow-manager.ts:214:16)\n' +
    '    at async stepHandler (C:\\Users\\mfa\\Projects\\PG\\backend\\node_modules\\@medusajs\\orchestration\\src\\transaction\\transaction-orchestrator.ts:827:20)\n' +
    '    at async Promise.allSettled (index 0)\n' +
    '    at async promiseAll (C:\\Users\\mfa\\Projects\\PG\\backend\\node_modules\\@medusajs\\utils\\src\\common\\promise-all.ts:27:18)\n' +
    '    at async TransactionOrchestrator.executeNext (C:\\Users\\mfa\\Projects\\PG\\backend\\node_modules\\@medusajs\\orchestration\\src\\transaction\\transaction-orchestrator.ts:965:7)\n' +
    '    at async executeNext (C:\\Users\\mfa\\Projects\\PG\\backend\\node_modules\\@medusajs\\orchestration\\src\\transaction\\transaction-orchestrator.ts:1013:14)\n' +
    '    at async TransactionOrchestrator.resume (C:\\Users\\mfa\\Projects\\PG\\backend\\node_modules\\@medusajs\\orchestration\\src\\transaction\\transaction-orchestrator.ts:1028:5)\n' +
    '⮑ sat C:\\Users\\mfa\\Projects\\PG\\backend\\node_modules\\@medusajs\\core-flows\\dist\\cart\\workflows\\list-shipping-options-for-cart.js: [list-shipping-options-for-cart -> validate-presence-of (invoke)]\n' +
    '⮑ sat C:\\Users\\mfa\\Projects\\PG\\backend\\node_modules\\@medusajs\\core-flows\\dist\\cart\\workflows\\refresh-cart-shipping-methods.js: [refresh-cart-shipping-methods -> list-shipping-options-for-cart-as-step (invoke)]\n' +
    '⮑ sat C:\\Users\\mfa\\Projects\\PG\\backend\\node_modules\\@medusajs\\core-flows\\dist\\cart\\workflows\\refresh-cart-items.js: [refresh-cart-items -> refresh-cart-shipping-methods-as-step (invoke)]\n' +
    '⮑ sat C:\\Users\\mfa\\Projects\\PG\\backend\\node_modules\\@medusajs\\core-flows\\dist\\cart\\workflows\\update-cart.js: [update-cart -> refresh-cart-items-as-step (invoke)]',
  __isMedusaError: true,
  type: 'invalid_data',
  code: undefined,
  date: 2025-01-03T10:43:57.909Z
}
```

**Comment by riqwan** [comment] 2025-01-03 11:46
Hey @mohamadfala, does the current region have a store associated with it?

**Comment by mohamadfala** [comment] 2025-01-03 11:49
> Hey @mohamadfala, does the current region have a store associated with it?

Yes store a has default_region_id

**Comment by riqwan** [comment] 2025-01-03 11:52
Thats weird indeed. Can you share the results of these sql queries:

```
select * from store;

select * from sales_channel;
```

**Comment by mohamadfala** [comment] 2025-01-03 11:56
> Thats weird indeed. Can you share the results of these sql queries:
> 
> ```
> select * from store;
> 
> select * from sales_channel;
> ```

select * from store:
```
"id"	"name"	"default_sales_channel_id"	"default_region_id"	"default_location_id"	"metadata"	"created_at"	"updated_at"	"deleted_at"
"store_01JB15Y8MSWT991AMGRWY48H8R"	"StoreName"	"sc_01JB15Y8MKHBW0HG2A9VSHR2DJ"	"reg_01JB15YAP9TRC655E7PGHTTTGR"		"{}"	"2024-10-25 09:31:07.67266+03"	"2024-10-25 09:31:07.67266+03"		
```


select * from sales_channel;
```
"id"	"name"	"description"	"is_disabled"	"metadata"	"created_at"	"updated_at"	"deleted_at"
"sc_01JB15Y8MKHBW0HG2A9VSHR2DJ"	"Default Sales Channel"	"Created by Medusa"	false		"2024-10-25 09:31:07.667+03"	"2024-10-25 09:31:07.667+03"	
```

**Comment by riqwan** [comment] 2025-01-03 12:00
Thanks, that looks good. 

Can you open this file - `node_modules/@medusajs/core-flows/dist/cart/steps/find-sales-channel.js`

on line 29, add the following logs:

```
console.log("data - ", JSON.stringify(data,null,4))
console.log("salesChannel - ", JSON.stringify(salesChannel,null,4))
```

Then:

1. restart your server
2. delete all cookies
3. add to cart

You should be able to see the logs after

**Comment by mohamadfala** [comment] 2025-01-03 12:04
> Thanks, that looks good.
> 
> Can you open this file - `node_modules/@medusajs/core-flows/dist/cart/steps/find-sales-channel.js`
> 
> on line 29, add the following logs:
> 
> ```
> console.log("data - ", JSON.stringify(data,null,4))
> console.log("salesChannel - ", JSON.stringify(salesChannel,null,4))
> ```

```
data -  {}
salesChannel -  {
    "id": "sc_01JB15Y8MKHBW0HG2A9VSHR2DJ",
    "name": "Default Sales Channel",
    "description": "Created by Medusa",
    "is_disabled": false,
    "metadata": null,
    "created_at": "2024-10-25T06:31:07.667Z",
    "updated_at": "2024-10-25T06:31:07.667Z",
    "deleted_at": null
}
```

**Comment by riqwan** [comment] 2025-01-03 12:06
That looks good as well! Can you finally paste the contents of `node_modules/@medusajs/core-flows/dist/cart/utils/fields.js`

**Comment by mohamadfala** [comment] 2025-01-03 12:08
> That looks good as well! Can you finally paste the contents of `node_modules/@medusajs/core-flows/dist/cart/utils/fields.js`

```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.productVariantsFields = exports.completeCartFields = exports.cartFieldsForRefreshSteps = void 0;
exports.cartFieldsForRefreshSteps = [
    "id",
    "currency_code",
    "quantity",
    "subtotal",
    "total",
    "item_subtotal",
    "shipping_subtotal",
    "region_id",
    "currency_code",
    "metadata",
    "completed_at",
    "sales_channel_id",
    "region.*",
    "items.*",
    "items.product.id",
    "items.product.collection_id",
    "items.product.categories.id",
    "items.product.tags.id",
    "items.adjustments.*",
    "items.tax_lines.*",
    "shipping_address.*",
    "shipping_methods.*",
    "shipping_methods.adjustments.*",
    "shipping_methods.tax_lines.*",
    "customer.*",
    "customer.groups.*",
    "promotions.code",
];
exports.completeCartFields = [
    "id",
    "currency_code",
    "email",
    "created_at",
    "updated_at",
    "completed_at",
    "total",
    "subtotal",
    "tax_total",
    "discount_total",
    "discount_tax_total",
    "original_total",
    "original_tax_total",
    "item_total",
    "item_subtotal",
    "item_tax_total",
    "sales_channel_id",
    "original_item_total",
    "original_item_subtotal",
    "original_item_tax_total",
    "shipping_total",
    "shipping_subtotal",
    "shipping_tax_total",
    "original_shipping_tax_total",
    "original_shipping_subtotal",
    "original_shipping_total",
    "raw_total",
    "raw_subtotal",
    "raw_tax_total",
    "raw_discount_total",
    "raw_discount_tax_total",
    "raw_original_total",
    "raw_original_tax_total",
    "raw_item_total",
    "raw_item_subtotal",
    "raw_item_tax_total",
    "raw_sales_channel_id",
    "raw_original_item_total",
    "raw_original_item_subtotal",
    "raw_original_item_tax_total",
    "raw_shipping_total",
    "raw_shipping_subtotal",
    "raw_shipping_tax_total",
    "raw_original_shipping_tax_total",
    "raw_original_shipping_subtotal",
    "raw_original_shipping_total",
    "items.*",
    "items.tax_lines.*",
    "items.adjustments.*",
    "customer.*",
    "shipping_methods.*",
    "shipping_methods.tax_lines.*",
    "shipping_methods.adjustments.*",
    "shipping_address.*",
    "billing_address.*",
    "region.*",
    "payment_collection.*",
    "payment_collection.payment_sessions.*",
    "items.variant.id",
    "items.variant.product.id",
    "items.variant.manage_inventory",
    "items.variant.allow_backorder",
    "items.variant.inventory_items.inventory_item_id",
    "items.variant.inventory_items.required_quantity",
    "items.variant.inventory_items.inventory.requires_shipping",
    "items.variant.inventory_items.inventory.location_levels.stock_locations.id",
    "items.variant.inventory_items.inventory.location_levels.stock_locations.name",
    "items.variant.inventory_items.inventory.location_levels.stock_locations.sales_channels.id",
    "items.variant.inventory_items.inventory.location_levels.stock_locations.sales_channels.name",
];
exports.productVariantsFields = [
    "id",
    "title",
    "sku",
    "manage_inventory",
    "allow_backorder",
    "requires_shipping",
    "is_discountable",
    "variant_option_values",
    "barcode",
    "product.id",
    "product.title",
    "product.description",
    "product.subtitle",
    "product.thumbnail",
    "product.type.value",
    "product.type.id",
    "product.collection.title",
    "product.handle",
    "product.discountable",
    "calculated_price.*",
    "inventory_items.inventory_item_id",
    "inventory_items.required_quantity",
    "inventory_items.inventory.requires_shipping",
    "inventory_items.inventory.location_levels.stock_locations.id",
    "inventory_items.inventory.location_levels.stock_locations.name",
    "inventory_items.inventory.location_levels.stock_locations.sales_channels.id",
    "inventory_items.inventory.location_levels.stock_locations.sales_channels.name",
];
//# sourceMappingURL=fields.js.map
```

**Comment by riqwan** [comment] 2025-01-03 12:13
That looks good too. 🤔 Can you check if the cart actually has a sales_channel_id in the db?

`select sales_channel_id from cart where id='cart_..'` you can get the cart id from the cookie.

**Comment by mohamadfala** [comment] 2025-01-03 12:16
> That looks good too. 🤔 Can you check if the cart actually has a sales_channel_id in the db?
> 
> `select sales_channel_id from cart where id='cart_..'` you can get the cart id from the cookie.

Apparently not:
![image](https://github.com/user-attachments/assets/75faac41-e0b6-4ab2-8458-53c422f6ba2f)

**Comment by riqwan** [comment] 2025-01-03 12:26
Ok, we gotta go back to `node_modules/@medusajs/core-flows/dist/cart/workflows/create-carts.js`

line 111: `console.log("data -- ", JSON.stringify(data,null,4))`

Paste results of that

**Comment by mohamadfala** [comment] 2025-01-03 12:31
> Ok, we gotta go back to `node_modules/@medusajs/core-flows/dist/cart/workflows/create-carts.js`
> 
> line 111: `console.log("data -- ", JSON.stringify(data,null,4))`
> 
> Paste results of that

I've added it on line 107 before the return, can't see anything logged.
Couldn't add it at line 111, bcz adding it after `cartToCreate` wont work since data is not defined at that level.

Please let me know if i need to fix its location.

![image](https://github.com/user-attachments/assets/e336592f-0074-4b8d-88f6-9dfa719d2882)

**Comment by riqwan** [comment] 2025-01-03 12:35
Adding it to 107 should have returned something. Weird that its not. Can you update to the latest version, purge the node_modules and try again?

**Comment by mohamadfala** [comment] 2025-01-03 12:49
> console.log("data -- ", JSON.stringify(data,null,4))

Now that I'm on the latest version (2.1.3) I've added the logger at the line 111, and here's the result:

```
data --  {
    "lineItems": [],
    "cartInput": {
        "region_id": "reg_01JB15YAP9TRC655E7PGHTTTGR",
        "sales_channel_id": "sc_01JB15Y8MKHBW0HG2A9VSHR2DJ",
        "currency_code": "aed",
        "shipping_address": {
            "country_code": "ae"
        }
    }
}
```

**Comment by riqwan** [comment] 2025-01-03 12:55
that seems like it should create a cart with a sales channel. Is the issue present still?

**Comment by mohamadfala** [comment] 2025-01-03 12:57
> that seems like it should create a cart with a sales channel. Is the issue present still?

yes same error, and also the cart has no channel id in the database yet:

![image](https://github.com/user-attachments/assets/5df56197-4b7c-4cb1-ac9d-6665091acef6)

**Comment by riqwan** [comment] 2025-01-03 12:58
ok, thats weird. Can you email me your db dump and your repository zip to riqwan[at]medusajs[dot]com?

**Comment by mohamadfala** [comment] 2025-01-03 13:16
> ok, thats weird. Can you email me your db dump and your repository zip to riqwan[at]medusajs[dot]com?

Email sent.

**Comment by mohamadfala** [comment] 2025-01-06 08:53
@riqwan any updates regarding this weird issue?

**Comment by riqwan** [comment] 2025-01-06 08:54
I have it on my list to investigate today 🙂

**Comment by mohamadfala** [comment] 2025-01-07 06:45
I added `export const fetchCache = "force-no-store";` to some pages like store, products, cart, checkout in order to disable caching products since prices are changing every minute in my case, and i was able to create an order and the previous error did not occur.

**Comment by riqwan** [comment] 2025-01-07 07:16
Thanks @mohamadfala. I'm confused, how does that fix a backend error?

**Comment by mohamadfala** [comment] 2025-01-07 07:24
> Thanks @mohamadfala. I'm confused, how does that fix a backend error?

I have absolutely no idea! could it a caching issue? it's not happening on production.
I've cleared all browser cache, tried incognito, cleared .next, node_modules, with no luck.
adding the `forece-no-store` unintentionally  fixed it.

It might not be the case, but I though I should let you know.

**Comment by riqwan** [comment] 2025-01-07 07:44
For what its worth, I tried to reproduce the error on your repo yesterday and tried my best to break it, but I could not reproduce it, which is good news I suppose. Try removing the `force-no-store` to see if you're still getting it.
