### ISSUE TITLE
New Medusa project storefront not running. Need urgent help.

### ISSUE THREAD

**Issue by vasugarg09** [medusajs/medusa#9483] opened 2024-10-06 17:47 UTC
I am facing this very unexpected issue while creating a Medusa app storefront.
I have gone through various github issues and searched for the solutions, but I couldn't find one. 
I even tried logging the api keys or the url but everything is showing right, and those URLs are also getting the data if run separately.

I have installed Medusa using npx and am using it's latest version on macos. Node, postgres, all are at the latest versions.
I tried both the latest release and also 2.0, facing issues with fetch in both. 
I am quite ne to this so maybe I'm doing something wrong. 

<img width="563" alt="Screenshot_2024-10-05_at_9 45 29_AM" src="https://github.com/user-attachments/assets/3adb93db-83e3-413b-b171-b24da2e3d9e8">
<img width="975" alt="Screenshot_2024-10-05_at_9 51 32_AM" src="https://github.com/user-attachments/assets/d892be7a-1e00-42d3-8ccd-2749c8f25d54">
<img width="586" alt="Screenshot_2024-10-05_at_9 51 43_AM" src="https://github.com/user-attachments/assets/78aca14b-b759-4e29-b30d-a43351780cda">
<img width="946" alt="Screenshot_2024-10-05_at_9 43 55_AM" src="https://github.com/user-attachments/assets/953667be-4764-4ed1-976e-3d46ed226eba">

Thanks to everyone for helping in advance.

**Comment by olivermrbl** [comment] 2024-10-08 07:36
Does your server console log any errors?

**Comment by SalahAdDin** [comment] 2024-10-21 16:08
@vgvasu35 did you check it?

**Comment by SalahAdDin** [comment] 2024-11-21 13:20
@vgvasu35 did you check it?

**Comment by sradevski** [comment] 2024-11-28 09:19
I cannot reproduce. Closing until someone has reproducible steps.

**Closed as completed by sradevski** 2024-11-28 09:19 UTC
Labels: type: bug
