### ISSUE TITLE
 Workflow with id ... and step definition already exists.

### ISSUE THREAD

**Issue by stelasido** [medusajs/medusa#10133] opened 2024-11-18 06:04 UTC
node: v22.5.1
 "dependencies": {
    "@medusajs/admin-sdk": "latest",
    "@medusajs/cli": "latest",
    "@medusajs/framework": "latest",
    "@medusajs/js-sdk": "^2.0.2",
    "@medusajs/medusa": "latest",
    "@medusajs/types": "^2.0.2",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "awilix": "^8.0.1",
    "pg": "^8.13.0",
    "react-query": "^3.39.3"
  },
  "devDependencies": {
    "@medusajs/test-utils": "latest",
    "@mikro-orm/cli": "5.9.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  }

Reinstalling everything, delete .medusa and it is the same. Where are these workflows saved, in the PostgreDB??? Cleaned Redis and it is the same

**Comment by carlos-r-l-rodrigues** [comment] 2024-11-18 15:26
Could you please provide the full error message?
Which workflow "id"?

Is it a clean medusa project?

**Comment by stelasido** [comment] 2024-11-22 05:28
> Could you please provide the full error message? Which workflow "id"?
> 
> Is it a clean medusa project?

New project. The ID is `Workflow with id "import-products" and step definition already exists.
Error: Workflow with id "import-products" and step definition already exists.`.

**Comment by carlos-r-l-rodrigues** [comment] 2024-11-22 10:02
Have you tried to remove node_modules, lock files (yarn or npm) and reinstall it?
That error could only happen if you have 2 different versions of the same package somewhere.

**Comment by sradevski** [comment] 2024-11-28 09:43
Closing as the issue is two different versions, as Carlos said.

**Closed as completed by sradevski** 2024-11-28 09:43 UTC
Labels: type: bug, status: needs triaging
