### ISSUE TITLE
Batch job strategy Extension not working.

### ISSUE THREAD

**Issue by AbhinavChavareTechcopain** [medusajs/medusa#5817] opened 2023-12-07 05:06 UTC
We are making the B2B marketplace where we need to show the products of a specific user (Seller) to a particular customer(Buyer) for that we have created the store_id column in the product table to define which products belong to which user,  and show on the storefront to those customers.
We have extended the product service to insert the store_id as per logged_in user, while creating the manual products it works very well.
But when it comes to importing products from the .csv file we don't get the logged_in user store_id to insert, as it running in the background.
we are trying to customize the src/strategy/imports.ts  but getting error:
1. when we try to customize the preprocessor with transaction (transaction) transaction is undefined.
2. And we are not able to call  processJob (batchJobId: string)

please guide for the same.

**Comment by riqwan** [comment] 2023-12-13 13:29
Hey @AbhinavChavareTechcopain,

Can you share more details on this one?

- Medusa version
- Code file of the customization (along with the folder structure)

**Comment by AbhinavChavareTechcopain** [comment] 2023-12-14 05:46
Medusa Version 1.3.18
Folder Structure:
src/services/strategies/imports.ts



import {   
    AbstractBatchJobStrategy,   
    ProductStatus,  
   } from "@medusajs/medusa"  
import   BatchJobService   from "@medusajs/medusa/dist/services/batch-job"  
import { Product } from "../models/product"
   import { BatchType, EntityManager } from "typeorm"  
import ProductService from "../services/product"
import BatchJobRepository from "@medusajs/medusa/dist/repositories/batch-job"
     

// type InjectedDependencies = {
//   // eventBusService: EventBusService
//   // configModule: ConfigModule
//   batchJobService:BatchJobService
//   batchJobRepository: typeof BatchJobRepository;
//   transactionManager: EntityManager;
//   manager: EntityManager;
// }
class MyImportStrategy extends AbstractBatchJobStrategy {  
 
    // static identifier = "publish-products-strategy"
    
    static batchType = "product-import"
    protected batchJobService_: BatchJobService  
    protected batchJobRepository_: typeof BatchJobRepository
    protected manager_: EntityManager  
    protected transactionManager_: EntityManager  
    protected productService_: ProductService  
   

    // constructor({ batchJobService, manager, transactionManager }) {  
    //   super({ batchJobService,manager, transactionManager })  
    //   this.batchJobService_ = batchJobService  
    //   this.manager_ = manager
    //   this.transactionManager_ = transactionManager
    //   }  
                  async preProcessBatchJob(batchJobId: string): Promise<void> {  
                    
                    const batchJobRepo = this.manager_.withRepository(this.batchJobRepository_)
                    console.log("batchJobService_ inside the preprocessed L21",batchJobRepo)
                    console.log("preProcessBatchJob inside the preprocessed L20",batchJobId)
                    return await this.atomicPhase_(  
                      async (transactionManager) => {  
                        console.log("atomicPhase_ inside the preprocessed L21")
                //  const batchJob = (await this.batchJobService_  
                //  .withTransaction(transactionManager)  
                //  .retrieve(batchJobId))  
                
                // console.log("transactionManager L42",transactionManager)
                // const batchJob = await this.batchJobService_.retrieve(batchJobId)
                // .then((batchJob) => {
                //   console.log("batchjob service Retrieve L66 ",batchJob);
                //    return batchJob;
                // });
                   
                // let orderStoreIdUpdate= batchJobRepo.retrieve(batchJobId)
                // .then((batchJob) => {
                //   console.log("batchjob service Retrieve L66 ",batchJob);
                //    return batchJob;
                // });
                let batchJob=await batchJobRepo.findOne({
                  where:{
                    id:batchJobId
                  }
                })  
                console.log("batchJob with find one",batchJob)
                 const count = await this.productService_.count({  
                 status: ProductStatus.DRAFT,  
                 })  
                  
                 await batchJobRepo.update(batchJobId, {  
                 result: {  
                 advancement_count: 0,  
                 count,  
                 new_key: "new value", // Add your new key here
                 stat_descriptors: [  
                 {  
                 key: "product-publish-count",  
                 name: "Number of products to publish",  
                 message:   
                 `${count} product(s) will be published.`,  
                 },  
                 ],  
                 },  
                 })  
                 })  
                 }  

    async processJob(batchJobId: string): Promise<void> {
        console.log("Inside the ProcessJob L25")
        console.log("Inside the ProcessJob L26",batchJobId)
        throw new Error("Method not implemented.")
    }

    
    async buildTemplate(): Promise<string> {  
        console.log("batchJob L23 buildTemplate")
    throw new Error("Method not implemented.")  
    }  
   }  
   
   export default MyImportStrategy

**Comment by riqwan** [comment] 2023-12-14 21:36
There too many things going on in there. Can you try with this minimum implementation?

```
import { default as ProductImportStrategy } from "@medusajs/medusa/dist/strategies/batch-jobs/product/import";

class ExtendedProductImportStrategy extends ProductImportStrategy {
  processJob(batchJobId: string): Promise<void> {
    console.log("Calling processJob ---- ", batchJobId);
    return super.processJob(batchJobId);
  }
}

export default ExtendedProductImportStrategy;
```

**Comment by riqwan** [comment] 2023-12-18 09:00
@AbhinavChavareTechcopain i'll close this for now as I can't reproduce it. It's working for the snippet I wrote above. Feel free to reopen if this issue still persists.

**Closed as completed by riqwan** 2023-12-18 09:00 UTC
Labels: type: bug, status: needs triaging
