### ISSUE TITLE
Documentation inaccessible (can't reach this page)

### ISSUE THREAD

**Issue by pjborowiecki** [medusajs/medusa#7873] opened 2024-06-29 09:07 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Documentation seems to be down and inaccessible today (can't reach this page). I tried several browsers, clearing cache, etc. Is anyone else having the same issue?

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by voxsar** [comment] 2024-06-29 17:40
I thought this was only me, but yes. the documentation server seems to allways go down

**Comment by shahednasser** [comment] 2024-07-01 07:20
Hey guys, are you still facing this issue? I can't reproduce it on my side.

**Comment by humbleEwan** [comment] 2024-07-02 10:39
The documentation is half usable at best, so try to use Phind or an up to date GPT model. (yes, this is an actual solution bc they "ate" the documentation) Do not get discouraged when something does not work, Medusa has 433 issues for a reason :laughing:

**Comment by shahednasser** [comment] 2024-07-05 07:58
Closing this issue due to lack of information. Feel free to re-open it when you have more information to allow us to reproduce the issue.

**Closed as completed by shahednasser** 2024-07-05 07:58 UTC
Labels: type: docs

**Comment by voxsar** [comment] 2024-07-07 03:50
The irony is that you closed it due to lack of information and of the issues @humbleEwan is lack of information

Please run a load test on the documentation server i think it crashes with their are two many request

**Comment by shahednasser** [comment] 2024-07-08 08:26
@voxsar were you able to run into this issue again?

**Comment by voxsar** [comment] 2024-07-08 08:39
> @voxsar were you able to run into this issue again?

Yes check right now, this exact moment

It's down

**Comment by shahednasser** [comment] 2024-07-08 08:44
I can't reproduce the issue, it's working fine on my end. Can you check if you're using any VPN, or if you try a different internet provider (for example, a mobile data plan)? This could be a network issue.
