### ISSUE TITLE
Import product csv error

### ISSUE THREAD

**Issue by jyothis0000** [medusajs/medusa#5268] opened 2023-10-02 09:35 UTC
### Describe the bug

I am unable to import items to my local; I had included all product-related categories, collections, and tags as in the previous dashbord that I had exported.

### System information

Medusa version (including plugins):"@medusajs/admin": "^7.1.1",
Node.js version: v16.13.1
Database: postgresql
Operating system: windows 11
Browser (if relevant): chrome

### Steps to reproduce the behavior

1. Go to 'admin dashboard'
2. Click on 'import product'
3. Click on  'notification'

### Expected behavior

Product should be listed in admin dashboard while import

### Screenshots
![image](https://github.com/medusajs/medusa/assets/75600328/926f8bbe-49c0-44c9-8194-15adaa014d55)
![image](https://github.com/medusajs/medusa/assets/75600328/36796951-bdfe-4974-82b1-44a511c19679)

**Comment by thejspro** [comment] 2023-10-02 09:47
I can confirm I have the same bug.

It was fixed in 1.15 if I remember correctly and now it's back again...

**Comment by fPolic** [comment] 2023-10-02 10:21
@jyothis0000 - are you trying to import products from an old database to the new one? If the product/variant id is passed, the import strategy will try to find and update the existing product/variant with that id.
So if you want to recreate products in the new database you have to remove product ids/variant ids from the import file.

**Comment by pepijn-vanvlaanderen** [comment] 2023-10-09 15:27
If you do want Product ID / Product Variant ID to be imported, you could override the import strategy. We made some alterations to support this:

src/strategies/product-import.ts
```
import {
    AbstractBatchJobStrategy,
    BatchJobService,
    IFileService,
    ProductCategoryService,
    ProductCollectionService,
    ProductService,
    ProductVariantService,
    RegionService,
    SalesChannel,
    SalesChannelService,
    ShippingProfileService,
} from '@medusajs/medusa'
import { computerizeAmount, MedusaError } from 'medusa-core-utils'
import { EntityManager } from 'typeorm'
import CsvParser from '@medusajs/medusa/dist/services/csv-parser'
import {
    OperationType,
    ProductImportBatchJob,
    ProductImportCsvSchema,
    ProductImportInjectedProps,
    ProductImportJobContext,
    TBuiltProductImportLine,
    TParsedProductImportRowData,
} from '@medusajs/medusa/dist/strategies/batch-jobs/product/types'
import SalesChannelFeatureFlag from '@medusajs/medusa/dist/loaders/feature-flags/sales-channels'
import ProductCategoryFeatureFlag from '@medusajs/medusa/dist/loaders/feature-flags/product-categories'
import {
    productImportColumnsDefinition,
    productImportProductCategoriesColumnsDefinition,
    productImportSalesChannelsColumnsDefinition,
} from '@medusajs/medusa/dist/strategies/batch-jobs/product/types/columns-definition'
import { FlagRouter } from '@medusajs/utils'
import { transformProductData, transformVariantData } from '@medusajs/medusa/dist/strategies/batch-jobs/product/utils'
import { CreateProductInput } from '@medusajs/medusa/dist/types/product'
import { CreateProductVariantInput } from '@medusajs/medusa/dist/types/product-variant'
import { BatchJob } from '@medusajs/medusa/dist'

/**
 * Process this many variant rows before reporting progress.
 */
const BATCH_SIZE = 100

/**
 * Default strategy class used for a batch import of products/variants.
 */
class ProductImportStrategy extends AbstractBatchJobStrategy {
    static identifier = 'product-import-strategy'

    static batchType = 'product-import'

    private processedCounter: Record<string, number> = {}

    protected readonly featureFlagRouter_: FlagRouter

    protected manager_: EntityManager
    protected transactionManager_: EntityManager | undefined

    protected readonly fileService_: IFileService

    protected readonly regionService_: RegionService
    protected readonly productService_: ProductService
    protected readonly batchJobService_: BatchJobService
    protected readonly productCollectionService_: ProductCollectionService
    protected readonly salesChannelService_: SalesChannelService
    protected readonly productVariantService_: ProductVariantService
    protected readonly shippingProfileService_: ShippingProfileService
    protected readonly productCategoryService_: ProductCategoryService

    protected readonly csvParser_: CsvParser<ProductImportCsvSchema, Record<string, string>, Record<string, string>>

    constructor({
                    batchJobService,
                    productService,
                    salesChannelService,
                    productVariantService,
                    shippingProfileService,
                    regionService,
                    fileService,
                    productCollectionService,
                    productCategoryService,
                    manager,
                    featureFlagRouter,
                }: ProductImportInjectedProps) {
        // eslint-disable-next-line prefer-rest-params
        super(arguments[0])

        const isSalesChannelsFeatureOn = featureFlagRouter.isFeatureEnabled(SalesChannelFeatureFlag.key)

        const isProductCategoriesFeatureOn = featureFlagRouter.isFeatureEnabled(ProductCategoryFeatureFlag.key)

        this.csvParser_ = new CsvParser({
            columns: [
                ...productImportColumnsDefinition.columns,
                ...(isSalesChannelsFeatureOn ? productImportSalesChannelsColumnsDefinition.columns : []),
                ...(isProductCategoriesFeatureOn ? productImportProductCategoriesColumnsDefinition.columns : []),
            ],
        })

        // @ts-ignore
        this.featureFlagRouter_ = featureFlagRouter

        this.manager_ = manager
        // @ts-ignore
        this.fileService_ = fileService
        this.batchJobService_ = batchJobService
        this.productService_ = productService
        this.salesChannelService_ = salesChannelService
        this.productVariantService_ = productVariantService
        this.shippingProfileService_ = shippingProfileService
        this.regionService_ = regionService
        this.productCollectionService_ = productCollectionService
        this.productCategoryService_ = productCategoryService
    }

    async buildTemplate(): Promise<string> {
        throw new Error('Not implemented!')
    }

    /**
     * Create a description of a row on which the error occurred and throw a Medusa error.
     *
     * @param row - Parsed CSV row data
     * @param errorDescription - Concrete error
     */
    protected static throwDescriptiveError(row: TParsedProductImportRowData, errorDescription?: string): never {
        const message = `Error while processing row with
      [(product id: ${row['product.id']}),
      (product handle: ${row['product.handle']}),
      (variant id: ${row['variant.id']}),
      (variant sku: ${row['variant.sku']})]: 
      ${errorDescription}`

        throw new MedusaError(MedusaError.Types.INVALID_DATA, message)
    }

    /**
     * Generate instructions for update/create of products/variants from parsed CSV rows.
     *
     * @param csvData - An array of parsed CSV rows.
     */
    async getImportInstructions(
        csvData: TParsedProductImportRowData[],
    ): Promise<Record<OperationType, TParsedProductImportRowData[]>> {
        const transactionManager = this.transactionManager_ ?? this.manager_
        const shippingProfile = await this.shippingProfileService_.withTransaction(transactionManager).retrieveDefault()

        const seenProducts = {}

        const productsCreate: TParsedProductImportRowData[] = []
        const productsUpdate: TParsedProductImportRowData[] = []

        const variantsCreate: TParsedProductImportRowData[] = []
        const variantsUpdate: TParsedProductImportRowData[] = []

        const existingProductVariants = await this.productVariantService_.list(
            {},
            {
                take: 10000,
                select: ['id', 'product_id'],
            },
        )
        const existingProductIds = Array.from(
            existingProductVariants.reduce((acc, productVariant) => acc.add(productVariant.product_id), new Set()),
        )
        const existingVariantIds = Array.from(
            existingProductVariants.reduce((acc, productVariant) => acc.add(productVariant.id), new Set()),
        )

        for (const row of csvData) {
            if ((row['variant.prices'] as Record<string, any>[]).length) {
                await this.prepareVariantPrices(row)
            }

            if (row['variant.id'] && existingVariantIds.includes(row['variant.id'])) {
                variantsUpdate.push(row)
            } else {
                variantsCreate.push(row)
            }

            // save only first occurrence
            if (!seenProducts[row['product.handle'] as string]) {
                row['product.profile_id'] = shippingProfile!.id
                if (row['product.id'] && existingProductIds.includes(row['product.id'])) {
                    productsUpdate.push(row)
                } else {
                    productsCreate.push(row)
                }

                seenProducts[row['product.handle'] as string] = true
            }
        }

        return {
            [OperationType.ProductCreate]: productsCreate,
            [OperationType.VariantCreate]: variantsCreate,
            [OperationType.ProductUpdate]: productsUpdate,
            [OperationType.VariantUpdate]: variantsUpdate,
        }
    }

    /**
     * Prepare prices records for insert - find and append region ids to records that contain a region name.
     *
     * @param row - An object containing parsed row data.
     */
    protected async prepareVariantPrices(row): Promise<void> {
        const transactionManager = this.transactionManager_ ?? this.manager_

        const prices: Record<string, string | number>[] = []

        for (const price of row['variant.prices']) {
            const record: Record<string, string | number> = {
                amount: price.amount || 0,
            }

            if (price.regionName) {
                try {
                    const region = await this.regionService_
                        .withTransaction(transactionManager)
                        .retrieveByName(price.regionName)

                    record.region_id = region.id
                    record.currency_code = region.currency_code
                } catch (e) {
                    throw new MedusaError(
                        MedusaError.Types.INVALID_DATA,
                        `Trying to set a price for a region ${price.regionName} that doesn't exist`,
                    )
                }
            } else {
                record.currency_code = price.currency_code
            }

            record.amount = computerizeAmount(Number(record.amount), record.currency_code as string)

            prices.push(record)
        }

        row['variant.prices'] = prices
    }

    /**
     * A worker method called after a batch job has been created.
     * The method parses a CSV file, generates sets of instructions
     * for processing and stores these instructions to a JSON file
     * which is uploaded to a bucket.
     *
     * @param batchJobId - An id of a job that is being preprocessed.
     */
    async preProcessBatchJob(batchJobId: string): Promise<void> {
        const transactionManager = this.transactionManager_ ?? this.manager_
        const batchJob = await this.batchJobService_.withTransaction(transactionManager).retrieve(batchJobId)

        const csvFileKey = (batchJob.context as ProductImportJobContext).fileKey
        const csvStream = await this.fileService_.getDownloadStream({
            fileKey: csvFileKey,
        })

        let builtData: Record<string, string>[]
        try {
            const parsedData = await this.csvParser_.parse(csvStream)
            builtData = await this.csvParser_.buildData(parsedData)
        } catch (e) {
            throw new MedusaError(MedusaError.Types.INVALID_DATA, 'The csv file parsing failed due to: ' + e.message)
        }

        const ops = await this.getImportInstructions(builtData)

        await this.uploadImportOpsFile(batchJobId, ops)

        let totalOperationCount = 0
        const operationsCounts = {}
        Object.keys(ops).forEach(key => {
            operationsCounts[key] = ops[key].length
            totalOperationCount += ops[key].length
        })

        await this.batchJobService_.withTransaction(transactionManager).update(batchJobId, {
            result: {
                advancement_count: 0,
                // number of update/create operations to execute
                count: totalOperationCount,
                operations: operationsCounts,
                stat_descriptors: [
                    {
                        key: 'product-import-count',
                        name: 'Products/variants to import',
                        message: `There will be ${ops[OperationType.ProductCreate].length} products created (${
                            ops[OperationType.ProductUpdate].length
                        }  updated).
             ${ops[OperationType.VariantCreate].length} variants will be created and ${
                            ops[OperationType.VariantUpdate].length
                        } updated`,
                    },
                ],
            },
        })
    }

    /**
     * The main processing method called after a batch job
     * is ready/confirmed for processing.
     *
     * @param batchJobId - An id of a batch job that is being processed.
     */
    async processJob(batchJobId: string): Promise<void> {
        return await this.atomicPhase_(async manager => {
            const batchJob = (await this.batchJobService_
                .withTransaction(manager)
                .retrieve(batchJobId)) as ProductImportBatchJob

            await this.createProducts(batchJob)
            await this.updateProducts(batchJob)
            await this.createVariants(batchJob)
            await this.updateVariants(batchJob)
            await this.finalize(batchJob)
        })
    }

    /**
     * Create, or retrieve by name, sales channels from the input data.
     *
     * NOTE: Sales channel names provided in the CSV must exist in the DB.
     *       New sales channels will not be created.
     *
     * @param data an array of sales channels partials
     * @return an array of sales channels created or retrieved by name
     */
    private async processSalesChannels(data: Pick<SalesChannel, 'name' | 'id'>[]): Promise<SalesChannel[]> {
        const transactionManager = this.transactionManager_ ?? this.manager_
        const salesChannelServiceTx = this.salesChannelService_.withTransaction(transactionManager)

        const salesChannels: SalesChannel[] = []

        for (const input of data) {
            let channel: SalesChannel | null = null

            if (input.id) {
                try {
                    channel = await salesChannelServiceTx.retrieve(input.id, {
                        select: ['id'],
                    })
                } catch (e) {
                    // noop - check if the channel exists with provided name
                }
            }

            if (!channel) {
                try {
                    channel = (await salesChannelServiceTx.retrieveByName(input.name, {
                        select: ['id'],
                    })) as SalesChannel
                } catch (e) {
                    // noop
                }
            }

            if (channel) {
                salesChannels.push(channel)
            }
        }

        return salesChannels
    }

    /**
     * Method retrieves product categories from handles provided in the CSV.
     *
     * @param data array of product category handles
     */
    private async processCategories(data: { handle: string }[]): Promise<{ id: string }[]> {
        const retIds: { id: string }[] = []
        const transactionManager = this.transactionManager_ ?? this.manager_
        const productCategoryService = this.productCategoryService_.withTransaction(transactionManager)

        for (const category of data) {
            const categoryPartial = (await productCategoryService.retrieveByHandle(category.handle, {
                select: ['id'],
            })) as { id: string }

            retIds.push(categoryPartial)
        }

        return retIds
    }

    /**
     * Method creates products using `ProductService` and parsed data from a CSV row.
     *
     * @param batchJob - The current batch job being processed.
     */
    private async createProducts(batchJob: ProductImportBatchJob): Promise<void> {
        if (!batchJob.result.operations[OperationType.ProductCreate]) {
            return
        }

        const transactionManager = this.transactionManager_ ?? this.manager_

        const productOps = await this.downloadImportOpsFile(batchJob, OperationType.ProductCreate)

        const productServiceTx = this.productService_.withTransaction(transactionManager)
        const productCollectionServiceTx = this.productCollectionService_.withTransaction(transactionManager)

        const isSalesChannelsFeatureOn = this.featureFlagRouter_.isFeatureEnabled(SalesChannelFeatureFlag.key)

        const isProductCategoriesFeatureOn = this.featureFlagRouter_.isFeatureEnabled(ProductCategoryFeatureFlag.key)

        for (const productOp of productOps) {
            const productData = transformProductData(productOp)

            try {
                if (isSalesChannelsFeatureOn && productOp['product.sales_channels']) {
                    productData['sales_channels'] = await this.processSalesChannels(
                        productOp['product.sales_channels'] as Pick<SalesChannel, 'name' | 'id' | 'description'>[],
                    )
                }

                if (productOp['product.collection.handle'] != null && productOp['product.collection.handle'] !== '') {
                    productData.collection_id = (
                        await productCollectionServiceTx.retrieveByHandle(
                            productOp['product.collection.handle'] as string,
                            { select: ['id'] },
                        )
                    ).id
                    delete productData.collection
                }

                if (isProductCategoriesFeatureOn && productOp['product.categories']) {
                    productData['categories'] = await this.processCategories(
                        productOp['product.categories'] as { handle: string }[],
                    )
                }

                // TODO: we should only pass the expected data and should not have to cast the entire object. Here we are passing everything contained in productData
                await productServiceTx.create(productData as unknown as CreateProductInput)
            } catch (e) {
                ProductImportStrategy.throwDescriptiveError(productOp, e.message)
            }

            await this.updateProgress(batchJob.id)
        }
    }

    /**
     * Method updates existing products in the DB using a CSV row data.
     *
     * @param batchJob - The current batch job being processed.
     */
    private async updateProducts(batchJob: ProductImportBatchJob): Promise<void> {
        if (!batchJob.result.operations[OperationType.ProductUpdate]) {
            return
        }

        const transactionManager = this.transactionManager_ ?? this.manager_
        const productOps = await this.downloadImportOpsFile(batchJob, OperationType.ProductUpdate)

        const productServiceTx = this.productService_.withTransaction(transactionManager)
        const productCollectionServiceTx = this.productCollectionService_.withTransaction(transactionManager)

        const isSalesChannelsFeatureOn = this.featureFlagRouter_.isFeatureEnabled(SalesChannelFeatureFlag.key)

        const isProductCategoriesFeatureOn = this.featureFlagRouter_.isFeatureEnabled(ProductCategoryFeatureFlag.key)

        for (const productOp of productOps) {
            const productData = transformProductData(productOp)
            try {
                if (isSalesChannelsFeatureOn && productOp['product.sales_channels']) {
                    productData['sales_channels'] = await this.processSalesChannels(
                        productOp['product.sales_channels'] as Pick<SalesChannel, 'name' | 'id' | 'description'>[],
                    )
                }

                delete productData.options // for now not supported in the update method

                if (productOp['product.collection.handle'] != null && productOp['product.collection.handle'] !== '') {
                    productData.collection_id = (
                        await productCollectionServiceTx.retrieveByHandle(
                            productOp['product.collection.handle'] as string,
                            { select: ['id'] },
                        )
                    ).id
                    delete productData.collection
                }

                if (isProductCategoriesFeatureOn && productOp['product.categories']) {
                    productData['categories'] = await this.processCategories(
                        productOp['product.categories'] as { handle: string }[],
                    )
                }

                // TODO: we should only pass the expected data. Here we are passing everything contained in productData
                await productServiceTx.update(productOp['product.id'] as string, productData)
            } catch (e) {
                ProductImportStrategy.throwDescriptiveError(productOp, e.message)
            }

            await this.updateProgress(batchJob.id)
        }
    }

    /**
     * Method creates product variants from a CSV data.
     * Method also handles processing of variant options.
     *
     * @param batchJob - The current batch job being processed.
     */
    private async createVariants(batchJob: ProductImportBatchJob): Promise<void> {
        if (!batchJob.result.operations[OperationType.VariantCreate]) {
            return
        }

        const transactionManager = this.transactionManager_ ?? this.manager_

        const variantOps = await this.downloadImportOpsFile(batchJob, OperationType.VariantCreate)

        for (const variantOp of variantOps) {
            try {
                const variant = transformVariantData(variantOp)

                const product = await this.productService_
                    .withTransaction(transactionManager)
                    .retrieveByHandle(variantOp['product.handle'] as string, {
                        relations: ['variants', 'variants.options', 'options'],
                    })

                const optionIds =
                    (variantOp['product.options'] as Record<string, string>[])?.map(
                        variantOption =>
                            product!.options.find(
                                createdProductOption => createdProductOption.title === variantOption.title,
                            )?.id,
                    ) || []

                variant.options =
                    (variant.options as Record<string, any>[])?.map((o, index) => ({
                        ...o,
                        option_id: optionIds[index],
                    })) || []

                delete variant.product

                await this.productVariantService_
                    .withTransaction(transactionManager)
                    .create(product!, variant as unknown as CreateProductVariantInput)

                await this.updateProgress(batchJob.id)
            } catch (e) {
                ProductImportStrategy.throwDescriptiveError(variantOp, e.message)
            }
        }
    }

    /**
     * Method updates product variants from a CSV data.
     *
     * @param batchJob - The current batch job being processed.
     */
    private async updateVariants(batchJob: ProductImportBatchJob): Promise<void> {
        if (!batchJob.result.operations[OperationType.VariantUpdate]) {
            return
        }

        const transactionManager = this.transactionManager_ ?? this.manager_

        const variantOps = await this.downloadImportOpsFile(batchJob, OperationType.VariantUpdate)

        const productServiceTx = this.productService_.withTransaction(transactionManager)

        for (const variantOp of variantOps) {
            try {
                const product = await productServiceTx.retrieveByHandle(variantOp['product.handle'] as string)

                await this.prepareVariantOptions(variantOp, product.id)

                const updateData = transformVariantData(variantOp)
                delete updateData.product
                delete updateData['product.handle']

                await this.productVariantService_
                    .withTransaction(transactionManager)
                    .update(variantOp['variant.id'] as string, updateData)
            } catch (e) {
                ProductImportStrategy.throwDescriptiveError(variantOp, e.message)
            }

            await this.updateProgress(batchJob.id)
        }
    }

    /**
     * Extend records used for creating variant options with corresponding product option ids.
     *
     * @param variantOp - Parsed row data form CSV
     * @param productId - id of variant's product
     */
    protected async prepareVariantOptions(variantOp, productId: string): Promise<void> {
        const transactionManager = this.transactionManager_ ?? this.manager_
        const productOptions = variantOp['variant.options'] || []

        const productServiceTx = this.productService_.withTransaction(transactionManager)
        for (const o of productOptions) {
            const option = await productServiceTx.retrieveOptionByTitle(o._title, productId)
            o.option_id = option?.id
        }
    }

    /**
     * Store import ops JSON file to a bucket.
     *
     * @param batchJobId - An id of the current batch job being processed.
     * @param results - An object containing parsed CSV data.
     */
    protected async uploadImportOpsFile(
        batchJobId: string,
        results: Record<OperationType, TParsedProductImportRowData[]>,
    ): Promise<void> {
        const uploadPromises: Promise<void>[] = []
        const transactionManager = this.transactionManager_ ?? this.manager_

        const files: Record<string, string> = {}

        for (const op in results) {
            if (results[op]?.length) {
                const { writeStream, fileKey, promise } = await this.fileService_
                    .withTransaction(transactionManager)
                    .getUploadStreamDescriptor({
                        name: ProductImportStrategy.buildFilename(batchJobId, op),
                        ext: 'json',
                    })

                uploadPromises.push(promise)

                files[op] = fileKey
                writeStream.write(JSON.stringify(results[op]))
                writeStream.end()
            }
        }

        await this.batchJobService_.withTransaction(transactionManager).update(batchJobId, {
            result: { files },
        })

        await Promise.all(uploadPromises)
    }

    /**
     * Download parsed ops JSON file.
     *
     * @param batchJob - the current batch job being processed
     * @param op - Type of import operation.
     */
    protected async downloadImportOpsFile(
        batchJob: BatchJob,
        op: OperationType,
    ): Promise<TParsedProductImportRowData[]> {
        let data = ''
        const transactionManager = this.transactionManager_ ?? this.manager_

        const readableStream = await this.fileService_.withTransaction(transactionManager).getDownloadStream({
            fileKey: batchJob.result.files![op],
        })

        return await new Promise(resolve => {
            readableStream.on('data', chunk => {
                data += chunk
            })
            readableStream.on('end', () => {
                resolve(JSON.parse(data))
            })
            readableStream.on('error', () => {
                // TODO: maybe should throw
                resolve([] as TParsedProductImportRowData[])
            })
        })
    }

    /**
     * Delete parsed CSV ops files.
     *
     * @param batchJob - the current batch job being processed
     */
    protected async deleteOpsFiles(batchJob: BatchJob): Promise<void> {
        const transactionManager = this.transactionManager_ ?? this.manager_

        const fileServiceTx = this.fileService_.withTransaction(transactionManager)
        for (const fileName of Object.values(batchJob.result.files!)) {
            try {
                await fileServiceTx.delete({
                    fileKey: fileName,
                })
            } catch (e) {
                // noop
            }
        }
    }

    /**
     * Update count of processed data in the batch job `result` column
     * and cleanup temp JSON files.
     *
     * @param batchJob - The current batch job being processed.
     */
    private async finalize(batchJob: BatchJob): Promise<void> {
        const transactionManager = this.transactionManager_ ?? this.manager_

        delete this.processedCounter[batchJob.id]

        await this.batchJobService_.withTransaction(transactionManager).update(batchJob.id, {
            result: { advancement_count: batchJob.result.count },
        })

        const { fileKey } = batchJob.context as ProductImportJobContext

        await this.fileService_.withTransaction(transactionManager).delete({ fileKey })

        await this.deleteOpsFiles(batchJob)
    }

    /**
     * Store the progress in the batch job `result` column.
     * Method is called after every update/create operation,
     * but after every `BATCH_SIZE` processed rows info is written to the DB.
     *
     * @param batchJobId - An id of the current batch job being processed.
     */
    private async updateProgress(batchJobId: string): Promise<void> {
        const newCount = (this.processedCounter[batchJobId] || 0) + 1
        this.processedCounter[batchJobId] = newCount
        if (newCount % BATCH_SIZE !== 0) {
            return
        }

        await this.batchJobService_.withTransaction(this.transactionManager_ ?? this.manager_).update(batchJobId, {
            result: {
                advancement_count: newCount,
            },
        })
    }

    private static buildFilename(
        batchJobId: string,
        operation: string,
        { appendExt }: { appendExt?: string } = { appendExt: undefined },
    ): string {
        const filename = `imports/products/ops/${batchJobId}-${operation}`
        return appendExt ? filename + appendExt : filename
    }
}

export default ProductImportStrategy

```

**Comment by olivermrbl** [comment] 2023-10-11 19:19
Closing this due to inactivity. Keen to reopen in case the issue is still relevant.

**Closed as completed by olivermrbl** 2023-10-11 19:19 UTC
Labels: type: bug, status: needs triaging
