### ISSUE TITLE
[Bug]: Users not deleted

### ISSUE THREAD

**Issue by chillpilllike** [medusajs/medusa#10364] opened 2024-11-29 10:00 UTC
### Package.json file

```JSON
{
  "name": "medusa-starter-default",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "dev": "medusa develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "latest",
    "@medusajs/cli": "latest",
    "@medusajs/framework": "latest",
    "@medusajs/medusa": "latest",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "awilix": "^8.0.1",
    "pg": "^8.13.0"
  },
  "devDependencies": {
    "@medusajs/test-utils": "latest",
    "@mikro-orm/cli": "5.9.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

20

### Database and its version

16

### Operating system name and version

22.04

### Browser name

safari latest

### What happended?

Users not deleted from portal

### Expected behavior

Users when we click on delete should be deleted

### Actual behavior

Nothing happens when we click on delete a user

<img width="970" alt="Screenshot 2024-11-29 at 3 30 28 pm" src="https://github.com/user-attachments/assets/687f122e-5687-4ce1-8834-7a7a40c9b6e3">

### Link to reproduction repo

https://github.com/medusajs/medusa-starter-default.git

**Comment by olivermrbl** [comment] 2024-11-29 12:52
@chillpilllike, you are not allowed to delete users other than yourself from the admin dashboard. If you inspect the network tab, you'll see that you are getting a 400, which is expected behavior.

That said, we should definitely show a toast indicating than the request didn't go through and why. I've created a ticket internally and will close this issue for now.

**Closed as completed by olivermrbl** 2024-11-29 12:52 UTC
Labels: status: needs triaging, version: 2.0

**Comment by amatosc** [comment] 2025-01-22 12:57
Hi @olivermrbl,

How are we supposed to delete users? It seems the admin panel does not allow for self-deletion. Could you please clarify the intended process for handling this scenario?
