### ISSUE TITLE
I encountered some very strange database issues, and many tables were inexplicably deleted.

### ISSUE THREAD

**Issue by ahqrt** [medusajs/medusa#9577] opened 2024-10-15 06:02 UTC
Problem Description
After deploying the Medusa backend to my own server, I encountered some strange issues. The system runs stably for a few days, but then the storefront page reports an error when opened. Upon checking the database, I found that the region table and some other tables were deleted. I'm not sure what caused this.

Table Structure Comparison
Here is the comparison of the database table structure before and after:
Before
<img width="233" alt="image" src="https://github.com/user-attachments/assets/ea1fbd48-ed4c-4de1-953d-03180147bca5">

After
<img width="250" alt="image" src="https://github.com/user-attachments/assets/dbebe345-5871-4e86-8e2b-c7349783fef5">

System Information
Here is my package.json dependencies information:

json
"dependencies": {
    "@medusajs/admin": "^7.1.16",
    "@medusajs/cache-inmemory": "1.8.11",
    "@medusajs/cache-redis": "^1.9.2",
    "@medusajs/event-bus-local": "1.9.9",
    "@medusajs/event-bus-redis": "^1.8.14",
    "@medusajs/file-local": "1.0.4",
    "@medusajs/medusa": "^1.20.9",
    "@tanstack/react-query": "4.22.0",
    "body-parser": "^1.19.0",
    "cors": "^2.8.5",
    "dotenv": "16.3.1",
    "express": "^4.17.2",
    "medusa-fulfillment-manual": "1.1.41",
    "medusa-interfaces": "1.3.10",
    "medusa-payment-manual": "1.0.25",
    "medusa-payment-stripe": "6.0.11",
    "prism-react-renderer": "^2.0.4",
    "typeorm": "0.3.16"
  },
Medusa Version (including plugins): 1.20.9
Node.js Version: v20.17.0
Database: Docker-Postgres
Operating System: Linux VM-0-7-CentOS 4.18.0-348.7.1.el8_5.x86_64
Browser (if relevant):
I hope to find out the cause of the problem and get a solution.

**Comment by renanboni** [comment] 2024-10-15 18:20
to add on top of this - I came across the same but it happened with a pivot table created from module linking (I've updated to the latest RC4 and when I ran the migration it said my table had been deleted)

**Comment by srindom** [comment] 2024-10-22 07:10
Can't reproduce - if you can provide a minimal reproduction we can investigate further. Closing for now.

**Closed as completed by srindom** 2024-10-22 07:10 UTC
Labels: type: bug, status: needs triaging

**Comment by ibrahimkhurram407** [comment] 2025-08-06 20:31
Same thing happened to me only difference is that I had products orders and stuff on it and now we dont have any record, also in postgresql logs there is no intruder attempt

**Comment by gajeraharsh** [comment] 2025-09-08 15:42
@ahqrt 

I come up with same issue did you find any soluation 2 times my database tables is wiped out

**Comment by ibrahimkhurram407** [comment] 2025-09-08 18:08
@gajeraharsh nah man I had to add all the products and pretty much setup the website again
