### ISSUE TITLE
`expand` param does not work on /store/customers/me

### ISSUE THREAD

**Issue by BorisKamp** [medusajs/medusa#4720] opened 2023-08-08 12:23 UTC
Running medusa `1.13.1`, like the title says, when I call `{{medusa-host}}/store/customers/me?expand=orders,groups`, the expand fields are not there in the response.

**Edit** 
I heard on Discord that this is intended. Would be great if the use could at least get their customer group tho?

**Comment by srindom** [comment] 2023-08-09 12:40
The reason for not allowing customer groups here is that when merchants segment customers using customer groups it is not always desirable to have that information flow into the storefront. E.g., if a customer has been segmented into a "VIP group" or "at-risk group" that is generally not something you want them to be able to find out. 

I understand that this can vary depending on the use case - the approach I would take in your scenario would be to create a custom endpoint for fetching these details. Could for example be:

```
GET /store/customers/me/properties
``` 

The endpoint would retrieve the logged-in customer find their customer groups and then respond with the rights that the group enable (if there is nothing sensitive in the group configuration you can of course also just respond with that).

An example of a response could be the following:
```
{
  rights: {
    free_shipping_eligibility: true,
    ...
  },
  ...
}
```

Where `free_shipping_eligibility` is true/false depending on the customer's group.

**Comment by srindom** [comment] 2023-08-09 12:41
Closing as this is intended behavior.

**Closed as completed by srindom** 2023-08-09 12:41 UTC
Labels: type: bug, status: needs triaging
