### ISSUE TITLE
[Issue] Medusa 2.0  Placing Order: Something wrong on place order with loggedIn customer.

### ISSUE THREAD

**Issue by Attachai77** [medusajs/medusa#9755] opened 2024-10-24 09:22 UTC
### Describe the bug

I've already updated my dependencies to '2.0.0' and tried placing an order with a logged-in customer. However, the created order doesn't belong to the logged-in user. Instead, a new customer is created with the same email, and they become the owner of the order. When I place another order, it always belongs to the second customer.

<img width="1243" alt="Screenshot 2567-10-24 at 16 03 39" src="https://github.com/user-attachments/assets/3d402cd1-f8b8-41a9-b8fc-09d87c092c61">

----

<img width="679" alt="Screenshot 2567-10-24 at 16 04 09" src="https://github.com/user-attachments/assets/59474336-57e6-4b9d-8edf-ad5ae290617e">

---

<img width="596" alt="Screenshot 2567-10-24 at 16 04 01" src="https://github.com/user-attachments/assets/87752af6-ce37-492d-ab42-27adb2079028">

---
**_in my case, I logged in with customer cus_01JAYTXGD9TEMBF2CF0DTJ9GJH and then placed order but the order belong to customer cus_01JAYV28PZNX0N0XEYFDD3A9M2 ._**

### System information

Medusa version (including plugins): 2.0
Node.js version: 20
Database: postgresql
Operating system:
Browser (if relevant):

### Expected behavior

A clear and concise description of what you expected to happen

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by olivermrbl** [comment] 2024-10-24 09:54
@Attachai77, thanks for the report. Are you using the Next.js Starter?

**Comment by Attachai77** [comment] 2024-10-24 10:00
> @Attachai77, thanks for the report. Are you using the Next.js Starter?

Yes, I am & I've just now install the latest and getting the same.

**Comment by mustafaugurlu973** [comment] 2024-10-24 10:41
I'm seeing the same issue when placing orders using the Next.js Starter. Logged-in users still get a **Guest** profile created for the same email. As shown in the screenshot, even though the user is registered, a Guest profile is also created.


<img width="1369" alt="Ekran Resmi 2024-10-24 13 34 08" src="https://github.com/user-attachments/assets/7f37f333-cab5-4a94-9624-1e586b44f32a">

**Comment by olivermrbl** [comment] 2024-10-24 11:00
Yup, identified the issue, we are on it!

**Comment by Deroswent** [comment] 2024-10-24 11:11
The same problem was described in this closed thread https://github.com/medusajs/medusa/issues/9629

And the problem has not been solved. Please take a look, maybe it will give you more information.  

Also, there is no way to link the cart and user in Store API[ Cart Create](https://docs.medusajs.com/v2/api/store#carts_postcarts)

**Comment by Attachai77** [comment] 2024-10-25 11:21
any updates here, could you pls tell me when will be fixed.

**Comment by bhuvan0616** [comment] 2024-10-28 04:18
@olivermrbl any update on this issue?

**Comment by y3owk1n** [comment] 2024-10-28 04:37
Hi all, I am facing this issue as well, but after some debugging, I think the issue is not on medusa backend, but on the nextjs starter kit, specifically how we it uses the sdk.

To make it work, you can try to change the following, probably a bug from the starter kit.

```
// src/lib/data/cart.ts

export async function createCart(regionId: string) {
	const cartResp = await sdk.store.cart.create(
		{ region_id: regionId },
		{},
		getAuthHeaders(), // <- Remember to pass the auth header along
	);
	const cart = cartResp.cart;
	setCartId(cart.id);
	revalidateTag("cart");

	return cart;
}
```

```
// src/lib/data/cart.ts

export async function setAddresses(currentState: unknown, formData: FormData) {
	// Get current loggedin customer
	const customer = await getCustomer();

	// Empty email field object
	let emailField = {};

	// If no customer, make sure to use the form data as email, else 
	// DO NOT send the email field back
	if (!customer) {
		emailField = {
			email: formData.get("email"),
		};
	}

	try {
		if (!formData) {
			throw new Error("No form data found when setting addresses");
		}
		const cartId = getCartId();
		if (!cartId) {
			throw new Error("No existing cart found when setting addresses");
		}

		const data = {
			shipping_address: {
				first_name: formData.get("shipping_address.first_name"),
				last_name: formData.get("shipping_address.last_name"),
				address_1: formData.get("shipping_address.address_1"),
				address_2: "",
				company: formData.get("shipping_address.company"),
				postal_code: formData.get("shipping_address.postal_code"),
				city: formData.get("shipping_address.city"),
				country_code: formData.get("shipping_address.country_code"),
				province: formData.get("shipping_address.province"),
				phone: formData.get("shipping_address.phone"),
			},
			...emailField, // Spread the email field here
		} as any;

		const sameAsBilling = formData.get("same_as_billing");
		if (sameAsBilling === "on")
			data.billing_address = data.shipping_address;

		if (sameAsBilling !== "on")
			data.billing_address = {
				first_name: formData.get("billing_address.first_name"),
				last_name: formData.get("billing_address.last_name"),
				address_1: formData.get("billing_address.address_1"),
				address_2: "",
				company: formData.get("billing_address.company"),
				postal_code: formData.get("billing_address.postal_code"),
				city: formData.get("billing_address.city"),
				country_code: formData.get("billing_address.country_code"),
				province: formData.get("billing_address.province"),
				phone: formData.get("billing_address.phone"),
			};
		await updateCart(data);
	} catch (e: any) {
		return e.message;
	}

	redirect(
		`/${formData.get("shipping_address.country_code")}/checkout?step=delivery`,
	);
}
```

By doing this, the nextjs starter kit should work with both loggedin and not logged in user during cart and order.

### Side note:
Turns out that in the backend `updateCartWorkflow`, the workflow is not expecting any auth context and the validated body does not allow `customer_id` but only `email`.

https://github.com/medusajs/medusa/blob/7c629f494f7d733d893c78f25a1493f41c8e4e98/packages/medusa/src/api/store/carts/validators.ts#L46-L58

Specifically at this workflow, we can see that `customer_id` or any auth context id is never passed to the workflow.
https://github.com/medusajs/medusa/blob/7c629f494f7d733d893c78f25a1493f41c8e4e98/packages/medusa/src/api/store/carts/%5Bid%5D/route.ts#L24-L46

If we pass in `email`, it will technically override the customer object because of this, and it will create a guest account that has the same `email` of your loggedin account. It will never be a customerId being passed to here.
https://github.com/medusajs/medusa/blob/7c629f494f7d733d893c78f25a1493f41c8e4e98/packages/core/core-flows/src/cart/steps/find-or-create-customer.ts#L47-L74

Hope it helps!

**Comment by agnwoj99** [comment] 2024-10-30 15:18
@y3owk1n I think that is not error related to Nextjs Starter kit, because like you see below, this request, which update cart, throws me an error with `customer_id` in body:
<img width="813" alt="Postman request" src="https://github.com/user-attachments/assets/43bad7b7-b35f-4062-837f-d1c983998a49">
And the request is consistent with the documentation: https://docs.medusajs.com/resources/storefront-development/cart/update#update-carts-customer

**Comment by vethan** [comment] 2024-11-01 14:26
Think we can add a middleware to fix this temporarily?

**Comment by chizidotdev** [comment] 2024-11-02 01:42
> @y3owk1n I think that is not error related to Nextjs Starter kit, because like you see below, this request, which update cart, throws me an error with `customer_id` in body

Had the same experience trying to update the cart with customer id during the checkout process. I initially thought it was an issue from the sdk until I saw @y3owk1n 's comment.

So as a work around, I created a new `link cart` route for this...

```ts
// The route I"ve chosen for this is: /store/cart/:id/link
// File path: src/api/store/cart/[id]/link/route.ts
import { MedusaRequest, MedusaResponse } from "@medusajs/framework";
import { PostStoreLinkCartSchema } from "./validators";
import { z } from "zod";
import { MedusaError, Modules } from "@medusajs/framework/utils";

// Validation reference: https://docs.medusajs.com/learn/advanced-development/api-routes/validation
type PostStoreLinkCartSchemaType = z.infer<typeof PostStoreLinkCartSchema>;

export async function POST(
  req: MedusaRequest<PostStoreLinkCartSchemaType>,
  res: MedusaResponse,
): Promise<void> {
  const cartId = req.params.id;
  const customerId = req.body.customer_id;

  const cartModuleService = req.scope.resolve(Modules.CART);

  if (!customerId) {
    throw new MedusaError(MedusaError.Types.INVALID_DATA, "`customer_id` field is required.");
  }

  try {
    await cartModuleService.updateCarts([
      {
        id: cartId,
        customer_id: customerId,
      },
    ]);

    res.status(200).json({
      message: "Customer linked successfully!",
    });
  } catch (error) {
    throw new MedusaError(MedusaError.Types.DB_ERROR, "An error occured, please try again");
  }
}
```
Then on the storefront, I call the link route during the checkout flow with an axios request
```ts
  return axios
    .post(
      `${process.env.NEXT_PUBLIC_MEDUSA_BACKEND_URL}/store/cart/${cartId}/link`,
      { customer_id: customer.id },
      { headers: { "x-publishable-api-key": `${process.env.NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY}` } }
    )
    .then(() => {
      revalidateTag("cart");
    })
    .catch(medusaError);
```

--- 
**PS.** This is not in any way a perfect solution but it's solved the issue. I'm hoping the fix for allowing a `customer_id` field from the updateCartWorkflow is pushed soon.
It might just be updating this zod schema as @y3owk1n mentioned...
https://github.com/medusajs/medusa/blob/7b51204ef396cecdc85ec7a18270c123d29a24cd/packages/medusa/src/api/store/carts/validators.ts#L46-L58

**Comment by FinaritrAndrianiaina** [comment] 2024-11-04 11:56
Until there is a fix, I found a workaround by using patch package if someone is interested. There is a step in the cart workflows findOrCreateCustomer that doesn't receive customer_id but receive the email. It will always attach the order to a customer guest. So to fix it just install [patch-package](https://www.npmjs.com/package/patch-package) and paste this code in `patches/@medusajs+core-flows+2.0.1.patch`
```diff
diff --git a/node_modules/@medusajs/core-flows/dist/cart/steps/find-or-create-customer.js b/node_modules/@medusajs/core-flows/dist/cart/steps/find-or-create-customer.js
index 53d65c5..a6b9892 100644
--- a/node_modules/@medusajs/core-flows/dist/cart/steps/find-or-create-customer.js
+++ b/node_modules/@medusajs/core-flows/dist/cart/steps/find-or-create-customer.js
@@ -34,10 +34,16 @@ exports.findOrCreateCustomerStep = (0, workflows_sdk_1.createStep)(exports.findO
         const validatedEmail = (0, utils_1.validateEmail)(data.email);
         let [customer] = await service.listCustomers({
             email: validatedEmail,
-            has_account: false,
+            has_account: true,
         });
         if (!customer) {
-            customer = await service.createCustomers({ email: validatedEmail });
+            [customer] = await service.listCustomers({
+                email: validatedEmail,
+                has_account: false,
+            });
+            if (!customer) {
+                customer = await service.createCustomers({ email: validatedEmail });
+            }
             customerWasCreated = true;
         }
         customerData.customer = customer;
``` 
P.S: if the user is using another mail when ordering the order will not appear in his order history even if the customer is authenticated. Just make sure the email in the order is the user's.

**Comment by justinelut** [comment] 2024-11-07 09:10
is there any other way to fix this for the moment, and @chizidotdev you never provided the PostStoreLinkCartSchema that you used.

**Comment by justinelut** [comment] 2024-11-07 09:47
after apdating to version 2.0.2 thinking they have fixed the issue cart not linking am unfortunately getting another error 
  message: 'column i3.product_type_id does not exist',

![image](https://github.com/user-attachments/assets/1b4e0b74-483b-4bc5-9191-12761830bd7e)

**Comment by fPolic** [comment] 2024-11-07 10:21
hey @justinelut did you run migrations after the upgrade?

**Comment by justinelut** [comment] 2024-11-07 10:28
@fPolic unfortunately i did not, am so confused

**Comment by vethan** [comment] 2024-11-07 10:57
Cart issue isn't fixed in 2.0.2 unfortunately

**Comment by justinelut** [comment] 2024-11-07 11:00
I just followed @chizidotdev procedure and it works, make sure in the zod schema you add customer_id

**Comment by bhuvan0616** [comment] 2024-11-10 03:31
@olivermrbl @justinelut Any update on this issue? seems not released fix with 2.0.2. Please update on the release timeline.

**Comment by olivermrbl** [comment] 2024-11-10 07:30
@bhuvan0616, in the next release, 2.0.3, we will introduce the following behavior:

**Guest Customer Checkout**
- Create cart without customer
- Update email on cart -> Create guest customer and populate `customer_id` on cart
- Update email on cart again -> Create new guest customer and update `customer_id` on cart
- Other cart updates -> Do nothing
- When completing cart -> Cart `customer_id` is transferred to the order

**Logged-in Customer Checkout**
- Create cart -> set `customer_id` on cart to logged-in customer
- Update email on cart -> Maintain `customer_id` on cart but update `cart.email`
- Update email on cart again -> Same as above
- Other cart updates -> Do nothing
- When completing cart -> Cart `customer_id` is transferred to the order (one of the main culprits to the issue reported here)

It will not be possible to assign a logged-in customer to a cart that was created before the log-in. This will come in a follow-up improvement.

**Comment by bhuvan0616** [comment] 2024-11-10 13:07
@olivermrbl Thanks for the update

**Comment by haf** [comment] 2024-11-10 19:32
@justinelut Could you detail how you got around the product_type_id error? Applying the latest migrations doesn't seem to help for me...

**Comment by justinelut** [comment] 2024-11-11 04:24
@haf , i first upgraded all medusa core packages to version 2.0.2. Then i just ran medusa migrations and waited until they finished, then restarted the application and everything worked. Unless i see the error u r getting i might be unable to fully help

**Comment by Attachai77** [comment] 2024-11-12 02:20
I've updated to 2.0.3 and I got new something I'm not sure that's bug or not. 

**Placing an order as Logged-In customer.**
- placing an order with  shipping email same as Account, it works fine. ✅
- but do that with different email, it will create new customer and an order doesn't belong to the logged-in customer. ❌

**Comment by HarleySalas** [comment] 2024-11-13 12:56
I understand not automatically merging emails, as guests can enter any email, without verification and that is a privacy issue.

However, when a cart is associated with a customer_id that is not registered (cart is associated to guest) and the same cart is updated by a user, or retrieved by a user that then has a registered account, it should update the customer id to the registered account, without having to look at, or consider emails.

It's an extremely common scenario where a new customer discovers a site, adds some items to their cart and then only registers to the site after they begin the checkout process. It's not very reassuring that some of the most fundamental e-commerce features may not be addressed for a month or two, when the product is supposedly released. (referencing [comment](https://github.com/medusajs/medusa/issues/9999#issuecomment-2466747037))

**Comment by olivermrbl** [comment] 2024-11-13 14:01
@HarleySalas, as I mentioned in the comment you are referencing, we are aware of this limitation and are working to introduce the functionality very soon, likely within two months. 

Here's how it will (likely) work:
- Cart is created with a guest customer association -> `cart.customer_id` is an unregistered customer
- Guest customer signs in/creates an account -> `cart.customer_id` stays the same
- Storefront calls `POST /cart/:id/customer` -> Cart is transferred to registered customer
- `cart.customer_id` is updated to the ID of the registered customer

I appreciate that you are highlighting how would expect this to work–we've also considered the approach of updating it automatically under the hood. However, after internal discussion, we ended up with the approach above.

Let me know if this makes sense. Appreciate the patience, there is only so much we can work on as a small team.

I will close this issue now, as the issue OP reported has been resolved.

**Closed as completed by olivermrbl** 2024-11-13 14:01 UTC

**Comment by riqwan** [comment] 2024-11-25 12:10
Hey y'all,

With the new release - 2.0.6, you should now be able to transfer cart from guest to registered customer with this endpoint -> /store/carts/:id/customer.

I've updated the nextjs and b2b starters to account for this - example: https://github.com/medusajs/nextjs-starter-medusa/pull/407/files
