### ISSUE TITLE
'Deploy Medusa Backend on Railway' fails to deploy

### ISSUE THREAD

**Issue by coderreco** [medusajs/medusa#5104] opened 2023-09-17 22:26 UTC
## Bug report
When deploying the 'Deploy Medusa Backend on Railway' Railway template([Railway](https://railway.app/template/zC7eOq), (Github)[https://github.com/shahednasser/railway-deploy-demo]), the build and deployment fails. cc: @shahednasser 

### Describe the bug
When deploying the 'Deploy Medusa Backend on Railway' Railway template([Railway](https://railway.app/template/zC7eOq), (Github)[https://github.com/shahednasser/railway-deploy-demo]), the build and deployment fails. The build logs indicate that the healthcheck fails:
```
====================

Starting Healthcheck

====================


Path: /health

Retry window: 5m0s

 

Attempt #1 failed with service unavailable. Continuing to retry for 4m59s

Attempt #2 failed with service unavailable. Continuing to retry for 4m58s

Attempt #3 failed with service unavailable. Continuing to retry for 4m56s

Attempt #4 failed with service unavailable. Continuing to retry for 4m52s

Attempt #5 failed with service unavailable. Continuing to retry for 4m44s

Attempt #6 failed with service unavailable. Continuing to retry for 4m28s

Attempt #7 failed with service unavailable. Continuing to retry for 3m58s

Attempt #8 failed with service unavailable. Continuing to retry for 3m28s

Attempt #9 failed with service unavailable. Continuing to retry for 2m58s

Attempt #10 failed with service unavailable. Continuing to retry for 2m28s

Attempt #11 failed with service unavailable. Continuing to retry for 1m58s

Attempt #12 failed with service unavailable. Continuing to retry for 1m28s

Attempt #13 failed with service unavailable. Continuing to retry for 58s

Attempt #14 failed with service unavailable. Continuing to retry for 28s

 

1/1 replicas never became healthy!

Healthcheck failed!
```
And the deploy logs indicate that the redis instance may not be connecting properly?
```
[medusa-config] ⚠️ redis_url not found. A fake redis instance will be used.

No Redis url was provided - using Medusa in production without a proper Redis instance is not recommended

Using fake Redis

Initializing models

Models initialized

Initializing plugin models

Plugin models initialized

Initializing strategies

Strategies initialized

Initializing modules

Local Event Bus installed. This is not recommended for production.

Modules initialized

Initializing database

Database initialized

Initializing repositories

Repositories initialized

Initializing services

Services initialized

Initializing express

Warning: connect.session() MemoryStore is not

designed for a production environment, as it will leak

memory, and will not scale past a single process.

Express intialized

Initializing plugins

[info] [webpackbar] Compiling Webpack
```

### System information

Managed deployment via Railway Template

### Steps to reproduce the behavior

1. Go to ('Deploy Medusa Backend on Railway' template)[https://railway.app/template/zC7eOq]
2. Click on 'Deploy'
3. Connect github if not already authorized, then provide name for repo to be created.
4. Allow deployment process
5. See errors in backend logs

### Expected behavior

Expected a successful deployment of the medusa backend and admin panel.

### Screenshots

![CleanShot 2023-09-17 at 14 44 57](https://github.com/medusajs/medusa/assets/73268171/5947f480-8a75-4def-8b61-0eab8dd2f294)
![CleanShot 2023-09-17 at 14 45 46](https://github.com/medusajs/medusa/assets/73268171/1a7f3c3e-6027-4a1a-a8e8-9d06cbcf234a)
![CleanShot 2023-09-17 at 14 46 18](https://github.com/medusajs/medusa/assets/73268171/c6a5267c-0f9a-4b9e-a1cb-dc69603ac6b8)
![CleanShot 2023-09-17 at 14 46 37](https://github.com/medusajs/medusa/assets/73268171/086da3bd-1384-4a5d-9d69-dd731425b657)

### Code snippets

N/A

### Additional context

N/A

**Comment by shahednasser** [comment] 2023-09-18 07:56
Thank you for opening this issue @coderreco . It seems like the build time is taking long and the healthcheck is executing before, which stops the build after retrying 10 times.

Can I get you to try the following:

1. In your GitHub instance, click on the Settings tab
2. Scroll down to find the "Healthcheck Timeout" field and set its value to `300`
3. Click save and wait for the redeployment.

If that doesn't work, you can also try either increasing the timeout value or the number in the "On-Failure Restart Policy Max Retry" field. Let me know if any of these solutions work out

**Comment by jpizzle34** [comment] 2023-09-18 13:19
I had this issue as well. The timeout is probably because the backend service is unable to connect to another dependent service, i.e. the Postgres instance. 

You will need to amend a couple of the env vars as the default ones are incorrect.

Change `{{Postgresql.DATABASE_URL}}` to lowercase, like, `{{postgresql.DATABASE_URL}}`

Similar for the redis instance.

**Comment by shahednasser** [comment] 2023-09-18 13:28
Thank you @jpizzle34 , but we've fixed the docs and the button to fix the variable names, so that's not the issue. Also, if there's any issue in connected to PostgreSQL or Redis then there would be an error like "cannot connect to xxx"

There are no error in the logs, and the build hasn't finished before the deployment is considered as failed, so I think it's most likely due to the healthcheck timeout.

**Comment by coderreco** [comment] 2023-09-18 13:31
> I had this issue as well. The timeout is probably because the backend service is unable to connect to another dependent service, i.e. the Postgres instance.
> 
> You will need to amend a couple of the env vars as the default ones are incorrect.
> 
> Change `{{Postgresql.DATABASE_URL}}` to lowercase, like, `{{postgresql.DATABASE_URL}}`
> 
> Similar for the redis instance.

Thanks for the insight, but I checked and confirmed the variables in mine were already correct.

**Comment by jpizzle34** [comment] 2023-09-18 13:32
Ahhh i see. Sorry i jumped the gun there :)

**Comment by shahednasser** [comment] 2023-09-18 13:36
@jpizzle34 all good! I actually only recently discovered the issue with environment variables, so it's always helpful to be made aware of this stuff 😄

**Comment by coderreco** [comment] 2023-09-18 13:37
> Ahhh i see. Sorry i jumped the gun there :)

No apology necessary! Appreciate the help and any other insights into how you got it working.

@shahednasser I checked the timeout and it was already set to 300. I upped it to 500, and updated to the new version from upstream. It is building currently and I will report back on whether it succeeds or fails this time around.

**Comment by coderreco** [comment] 2023-09-18 14:01
@shahednasser No changes and same outcome unfortunately.

During each health check(I think), I can see in the deploy logs that it is not finding the redis_url:
![CleanShot 2023-09-18 at 06 55 32@2x](https://github.com/medusajs/medusa/assets/73268171/8080ed48-8438-4986-b2b8-b57c45a984bb)

I am attempting a deploy with the redis_url value pasted directly into the environment variable instead of using the plugin value to see if that makes any change.

**Comment by shahednasser** [comment] 2023-09-18 14:03
This is not an issue, as Medusa will use a fake redis (although functionalities related to scheduled jobs will not work). To enable Redis, you can refer to [this documentation](https://docs.medusajs.com/development/backend/configurations#redis_url).

Did it stop at the "Compiling Webpack" step, or did it move forward? It's strange but I can't reproduce it on my end, so that's why a lot of this is just mainly me guessing 😅

**Comment by coderreco** [comment] 2023-09-18 14:08
It looks like it always stops on the compiling webpack step. Well I appreciate your help! That is strange as I have had the same result on two entirely separate attempts to use the template.

**Comment by shahednasser** [comment] 2023-09-18 14:12
Maybe you can try another hosting provider. You can find our guides for all providers [here](https://docs.medusajs.com/deployments/server/).

**Comment by shahednasser** [comment] 2023-09-18 14:14
You can also view the [public demo](https://railway.app/project/a1e5a434-29dc-4c2e-9be9-3630bff145da) we have of the Railway template. Maybe it will provide some idea to how to fix it or any differences compared to your project?

**Comment by DuncanLHS** [comment] 2024-01-17 22:20
There are sill problems with the "Deploy to Railway" one click button. @shahednasser the public link you shared is not working either. The logs are full of 404s

From my logs I have the following that don't look right:

```
- Local Event Bus installed. This is not recommended for production.
- No Redis url was provided - using Medusa in production without a proper Redis instance is not recommended.
- Warning: connect.session() MemoryStore is not designed for a production environment, as it will leak memory, and will not scale past a single process.
- You don't have Redis configured. Scheduled jobs will not be enabled.
```

I get a response code 200 on "/health" but 404 on "/"

**Comment by sradevski** [comment] 2024-07-05 10:30
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏

**Closed as completed by sradevski** 2024-07-05 10:30 UTC
Labels: type: bug, status: needs triaging
