### ISSUE TITLE
Order edit with id oe_xxxxxx was not found

### ISSUE THREAD

**Issue by tsvetann** [medusajs/medusa#4932] opened 2023-09-01 09:54 UTC
## Bug report

`error:   Order edit with id oe_xxxxxx was not found
Error: Order edit with id oe_xxxxxx was not found
    at OrderEditService.<anonymous> (..../node_modules/@medusajs/medusa/dist/services/order-edit.js:132:35)
    at step (.../node_modules/@medusajs/medusa/dist/services/order-edit.js:59:23)
    at Object.next (.../node_modules/@medusajs/medusa/dist/services/order-edit.js:40:53)
    at fulfilled (.../server/node_modules/@medusajs/medusa/dist/services/order-edit.js:31:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  type: 'not_found',
  code: undefined,
  date: 2023-09-01T09:48:08.649Z`

### Describe the bug

Place an order -> in medusa admin open the order (summary section) click on Edit order -> Close the modal -> the above error appears in the logs

### System information

Medusa version ^1.15.0:
Node.js version: 16.14
Database: postgre
Operating system: MacOS
Browser (if relevant):

### Steps to reproduce the behavior

Place an order -> in medusa admin open the order (summary section) click on Edit order -> Close the modal -> the above error appears in the logs

### Expected behavior

To not get the error. I am not sure what the impact of this error is

**Comment by fPolic** [comment] 2023-09-01 10:32
@tsvetann - I can't reproduce this on the latest version of admin. Which admin version and browser are you using?

**Comment by tsvetann** [comment] 2023-09-01 10:42
@fPolic I am using Admin v ^6.0.5 as v7 fails with an error - see https://discord.com/channels/876835651130097704/1147073454269550673/1147073454269550673

**Comment by sradevski** [comment] 2024-07-05 10:20
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏

**Closed as completed by sradevski** 2024-07-05 10:20 UTC
Labels: type: bug, status: needs triaging
