### ISSUE TITLE
Admin UI - Corrupted Options in Edit Options and Edit Variants and Add Variants for existing product

### ISSUE THREAD

**Issue by tsemachh** [medusajs/medusa#4738] opened 2023-08-10 09:01 UTC
### Describe the bug

When creating new product we add options and variants based on those options.
After product is created when we enter one of the next screens the options are corrupted:
1. Edit Options , 
 Existing options - options are looking like free text without the values related to the options
 Add an option - - options are looking like free text without the values related to the options
 2. Edit Variant
 Options appear as free text without the ability to choose from other options
### System information
Medusa version:
    "@medusajs/admin": "7.0.0-beta-20230727162508",
    "@medusajs/cache-inmemory": "^1.8.7",
    "@medusajs/cache-redis": "^1.8.7",
    "@medusajs/event-bus-local": "^1.9.4",
    "@medusajs/event-bus-redis": "^1.8.7",
    "@medusajs/file-local": "^1.0.1",
    "@medusajs/medusa": "1.13.1-beta-20230727162508",
    "medusa-fulfillment-manual": "^1.1.37",
    "medusa-interfaces": "^1.3.7",
    "medusa-payment-manual": "^1.0.23",
    "medusa-payment-stripe": "^6.0.1",
    "medusa-plugin-meilisearch": "^2.0.10",
    "medusa-plugin-smtp": "^1.2.0",
Node.js version: v18.12.1
Database: Postgrea 10.4
Operating system: Windows 10
Browser (if relevant): Chrome latest

### Steps to reproduce the behavior
1. Create new Product
2. Add Options and Variants to the product
3. Save the Product
4. Enter the product - > Edit Options , Edit Variants - Add/Edit Variant

### Expected behavior
Options are listed in all screens as defined in the initial product creation

### Screenshots

If applicable, add screenshots to help explain your problem
![image](https://github.com/medusajs/medusa/assets/2004954/a89e9695-d593-4239-8617-7e86a752488c)
![image](https://github.com/medusajs/medusa/assets/2004954/e3294af5-ff21-41c9-8cad-2eb6ab5bbb3e)
![image](https://github.com/medusajs/medusa/assets/2004954/8b92c024-a80c-40ca-8f29-98db29ca7235)
![image](https://github.com/medusajs/medusa/assets/2004954/084e98af-81a6-4831-a93a-b83fdd88672b)
![image](https://github.com/medusajs/medusa/assets/2004954/5d681530-503b-403c-80f0-eda0fb99177a)

**Comment by VladOrackle** [comment] 2023-08-19 20:53
I thought I was going crazy and just misunderstood how options and variants work
Have the same issue and it's easily reproducible

**Comment by rickylabs** [comment] 2023-10-02 15:27
Any news on this ?

**Comment by adrien2p** [comment] 2023-10-03 09:28
i've done some tests of the options in the Admin, and it seems to work as expected, I would like to understand more what problem you are encountering. I ve recorded a video of the options manipulation. It contains the following:
- Go to an already created product
- Add a new option
- Go to an existing variant
- fill up the new option
- create a new variant
- fill up the options
- try to delete an option
- update success, but nothing changed, this is because some variants rely on those options and if the option values where deleted from the variants you would end up with duplicated variant for the same options. take the following example: variant1: M/Red, variant2: M/Blue, if you delete the color option and the values are removed from the variant automatically, you end up with variant1: M and variant2: M and therefore there is a duplication on the same options.
- Delete the variants that rely on the option to remove, except the last one.
- delete the option
- success

Maybe we could improve that by returning an error message instead of success when removing an option that can't be automatically removed without deleting the variants. Another improvement could be if deleting the variant would not create duplicate then we could automatically do it. The drawback would be that if you remove an option by mistake it would remove the variant and you can't rollback as easy.

https://github.com/medusajs/medusa/assets/25098370/4520974a-8d0c-4112-92f5-10a0af10895e

cc @olivermrbl

**Comment by tsemachh** [comment] 2023-10-03 09:49
Try to follow the exact instructions in the report
Main issue is with existing products after first save we can't use the
options for edit or add variants

**Comment by adrien2p** [comment] 2023-10-03 10:14
Yes I ve done all the test with add options, create variant, edit variant and I didn't find the issue. Would you be able to send a screen recording to better follow your steps please. And you can see in the video I ve sent that I did the different cases.

Maybe I miss understood, but the current behaviour is that all variants should have a mix of all the options. So when updating the options (create/delete/update), all variants then display all the options field to be filled up in order to represent the different options permutations

**Comment by tsemachh** [comment] 2023-10-03 10:30
I am out of office at the moment,
Will send you recording next week hopefully.

**Comment by sradevski** [comment] 2024-07-05 10:12
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏

**Closed as completed by sradevski** 2024-07-05 10:12 UTC
Labels: type: bug, status: needs triaging
