### ISSUE TITLE
Deleting a product doesn't delete images from space

### ISSUE THREAD

**Issue by chemicalkosek** [medusajs/medusa#1468] opened 2022-05-03 18:44 UTC
When deleting a product, all connected images are not deleted.
This was tested with the spaces plugin but I assume it's relevant for all file plugins.

This produces orphaned images in buckets, which takes up available disk space.

**Comment by adrien2p** [comment] 2022-05-04 07:43
This depends on the use case of the consumer. What you can do is creating a subscriber that take care of that you can have a look [here](https://docs.medusajs.com/tutorial/adding-custom-functionality/#subscribers)

**Comment by olivermrbl** [comment] 2022-05-16 08:42
@adrien2p Do you think it would make sense to opt-in for this functionality in the file plugins? So in `medusa-config.js`, you could do: 
```
{
    resolve: `medusa-file-spaces`,
    options: {
       ...
       remove_on_delete: true
    },
  }
```

**Comment by adrien2p** [comment] 2022-05-16 08:45
I think it is a very good idea 👍 we can create the ticket add planned it 😀

**Comment by olivermrbl** [comment] 2022-08-05 12:50
Duplicate of #1872

**Closed by olivermrbl** 2022-08-05 12:50 UTC
Labels: type: feature or enhancement

**Comment by chemicalkosek** [comment] 2022-08-06 12:03
Hey, @olivermrbl 
It's not strictly a duplicate.
This issue was about when you're deleting a product then none of product images get deleted from spaces bucket.
They're orphaned on the bucket.

The linked issue (https://github.com/medusajs/medusa/issues/1872) is about deleting the image from a product.
The image is deleted from product but it stays on the bucket, even tho such code exists: https://github.com/medusajs/medusa/blob/73383cc466511ba5ab74146a3cec55d8af87dacc/packages/medusa-file-spaces/src/services/digital-ocean.js#L49
And I'm not 100% sure but I believe it was working before.

**Comment by Wooody82** [comment] 2022-09-07 20:26
Is this fixed? or.?
I think it need to check any image if its has space and change it to dash.

**Comment by habibullah-turkmen-peacegl** [comment] 2023-03-07 08:49
The issue, still persists, is there a way to fix it?

**Comment by luluhoc** [comment] 2023-11-17 16:55
Why is this closed the issue still exists
