### ISSUE TITLE
[Bug]: Dependency Injection does not work with AbstractAuthModuleProvider

### ISSUE THREAD

**Issue by akouyate** [medusajs/medusa#10036] opened 2024-11-11 23:11 UTC
### Package.json file

```JSON
{
  "name": "medusa-starter-default",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "dev": "medusa develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "^2.0.3",
    "@medusajs/cli": "^2.0.3",
    "@medusajs/framework": "^2.0.3",
    "@medusajs/medusa": "^2.0.3",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "awilix": "^8.0.1",
    "jsonwebtoken": "^9.0.2",
    "pg": "^8.13.0",
    "typeorm": "^0.3.20"
  },
  "devDependencies": {
    "@medusajs/test-utils": "latest",
    "@mikro-orm/cli": "5.9.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/jsonwebtoken": "^9.0.7",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

v22.2.0

### Database and its version

Postgres 

### Operating system name and version

Docker - MacOs

### What happended?

When implementing a custom authentication provider for passwordless login in Medusa v2, I am encountering the following error:

`Could not find an auth provider with id: passwordless`

```Typescript
// service.ts
import {
  AuthIdentityDTO,
  AuthIdentityProviderService,
  AuthenticationInput,
  AuthenticationResponse,
} from "@medusajs/framework/types";
import {
  AbstractAuthModuleProvider,
  AbstractEventBusModuleService,
  MedusaError,
} from "@medusajs/framework/utils";
import jwt from "jsonwebtoken";
import { eventName } from "src/subscribers/passwordless-token-generated";

type InjectedDependencies = {
  eventBus: AbstractEventBusModuleService;
};
type Options = {
  apiKey: string;
};

class PasswordlessAuthProviderService extends AbstractAuthModuleProvider {
  static identifier: string = "passwordless";

  private readonly JWT_SECRET = process.env.JWT_SECRET || "supersecret";
  private readonly TOKEN_EXPIRATION = "15m";

  protected eventBus: AbstractEventBusModuleService;
  protected options: Options;

  constructor({ eventBus }: InjectedDependencies, options: Options) {
    super();

    // Initialize dependencies
    this.eventBus = eventBus;
    this.options = options;
  }

  /**
   * Registers a new auth identity if one doesn't already exist.
   */
  async register(
    data: AuthenticationInput,
    authIdentityProviderService: AuthIdentityProviderService
  ): Promise<AuthenticationResponse> {
    const { email } = data.body;

    // Check if an auth identity already exists for this email
    try {
      await authIdentityProviderService.retrieve({
        entity_id: email,
      });

      // If an identity exists, return a response indicating it already exists
      return {
        success: false,
        error: "Identity with this email already exists",
      };
    } catch (error) {
      // If the identity does not exist (NOT_FOUND error), create a new one
      if (error.type === MedusaError.Types.NOT_FOUND) {
        const createdAuthIdentity = await authIdentityProviderService.create({
          entity_id: email,
          provider_metadata: {}, // Empty metadata if nothing else is needed
        });

        // Return success with the created auth identity
        return {
          success: true,
          authIdentity: createdAuthIdentity,
        };
      }

      // For other errors, return the error message
      return { success: false, error: error.message };
    }
  }

  /**
   * The `authenticate` method is called when the user initiates the login request.
   */
  async authenticate(
    data: AuthenticationInput,
    authIdentityProviderService: AuthIdentityProviderService
  ): Promise<AuthenticationResponse> {
    const { email } = data.body;

    // Retrieve or create an auth identity for the email
    let authIdentity: AuthIdentityDTO;
    authIdentity = await authIdentityProviderService.retrieve({
      entity_id: email,
    });

    // Generate a token
    const token = this.generateToken(email);

    await authIdentityProviderService.update(email, {
      provider_metadata: { token, expires_at: Date.now() + 15 * 60 * 1000 }, // 15-minute expiry
    });

    // Send the token via email
    const magicLinkUrl = `https://localhost:3000/passwordless/callback?token=${token}`;
    console.log(magicLinkUrl);
    this.eventBus.emit(
      {
        name: eventName,
        data: {
          email: email,
          magicLinkUrl: magicLinkUrl,
          // other data payload
        },
      },
      {}
    );

    return {
      success: true,
      location: `https://localhost:3000/passwordless/confirm`,
    };
  }

  /**
   * The `validateCallback` method is called when the user clicks the link in the email.
   */
  async validateCallback(
    data: AuthenticationInput,
    authIdentityProviderService: AuthIdentityProviderService
  ): Promise<AuthenticationResponse> {
    const { token } = data.query;

    // Validate the JWT token
    const decoded = this.validateToken(token);
    if (!decoded) {
      return {
        success: false,
        error: "Invalid or expired token",
      };
    }

    const email = decoded.email;
    const authIdentity = await authIdentityProviderService.retrieve({
      entity_id: email,
    });

    authIdentity.app_metadata;

    // Remove the token from provider_metadata after successful login
    await authIdentityProviderService.update(authIdentity.id, {
      provider_metadata: { token: null, expires_at: null },
    });

    return {
      success: true,
      authIdentity,
    };
  }

  /**
   * Generates a JWT token for the given email.
   */
  private generateToken(email: string): string {
    return jwt.sign({ email }, this.JWT_SECRET, {
      expiresIn: this.TOKEN_EXPIRATION,
    });
  }

  /**
   * Validates a JWT token and returns the decoded payload if valid.
   */
  private validateToken(token: string): any {
    try {
      return jwt.verify(token, this.JWT_SECRET);
    } catch (error) {
      console.error("Token validation error:", error);
      return null;
    }
  }
}

export default PasswordlessAuthProviderService;
```

```typescript
// index.ts
import { ModuleProvider, Modules } from "@medusajs/framework/utils";
import PasswordlessAuthProviderService from "./service";

export default ModuleProvider(Modules.AUTH, {
  services: [PasswordlessAuthProviderService],
});
```

```typescript
// medusa-config.ts
modules: [
    {
      resolve: "@medusajs/medusa/event-bus-redis",
      options: {
        redisUrl: process.env.EVENTS_REDIS_URL,
      },
    },
    {
      resolve: "@medusajs/medusa/auth",
      options: {
        providers: [
          {
            resolve: "./src/modules/passwordless-authentication",
            id: "passwordless",
            options: {
              // provider options...
            },
          },
          {
            resolve: "@medusajs/medusa/auth-emailpass",
            id: "emailpass",
            options: {
              // provider options...
            },
          },
        ],
      },
    },
  ],
```

### Expected behavior

The custom authentication provider (passwordless) should be successfully registered in Medusa’s DI container. Calling the authenticate method should trigger the login flow without errors.

### Actual behavior

The following error is thrown when attempting to use the authenticate method of the custom provider:
`Could not find an auth provider with id: passwordless`

• The error does not occur if the constructor is removed from the service, indicating an issue with dependency injection when the constructor is used.

### Link to reproduction repo

...

**Comment by olivermrbl** [comment] 2024-11-12 19:43
@akouyate, as you correctly pointed out, the error you are seeing is related to the event bus not being injected properly. To inject other services into a module service, the dependencies need to be specified in the module options. We haven't documented this area of modules yet, but we will be working on it in the near future.

Until then, here's the steps you need to take:

**1. Specify the event bus as a dependency of the `@medusajs/auth` module**
As part of loading the modules, we will inject the dependency to the module.
```ts
{
  resolve: "@medusajs/medusa/auth",
  dependencies: [Modules.EVENT_BUS], // <-------------- This dependency
  options: {
    providers: [
      {
        resolve: "./src/modules/passwordless",
        id: "passwordless",
        options: { ... },
      },
      ...
    ],
  },
}
```

**2. Specify the event bus as an injected dependency in `service.ts`**
You are already doing this, but you need to use a different registration key.
```ts
type InjectedDependencies = {
  [Modules.EVENT_BUS]: IEventBusModuleService;
};
```

**3. Resolve the event from the container in `service.ts`**
Finally, resolve the event bus from the container.
```ts
type InjectedDependencies = {
  [Modules.EVENT_BUS]: IEventBusModuleService;
};
...

constructor(container: InjectedDependencies, options: Options) {
    super();

    this.eventBus = container[Modules.EVENT_BUS];
  }
```


Let me know how it goes. 

I'll close this issue for now since this is not a bug, but an undocumented feature. As said, we will likely introduce documentation about this soon.

**Closed as completed by olivermrbl** 2024-11-12 19:43 UTC
Labels: status: needs triaging, version: 2.0

**Comment by akouyate** [comment] 2024-11-12 20:25
Hi @olivermrbl. It's working !
Thank you for taking the time to help with this issue. It will certainly help other people.

**Comment by herveguetin** [comment] 2025-05-11 17:49
@shahednasser - Hope I am not disturbing you with direct mention.

Reading this thread, do you confirm that this doc at step 4 (https://docs.medusajs.com/resources/references/auth/provider#4-use-module-provider) is correct?

Shouldn't it be: 

```
import { Modules, ContainerRegistrationKeys } from "@medusajs/framework/utils"

module.exports = defineConfig({
  // ...
  modules: [
    {
      resolve: "@medusajs/medusa/auth",
      dependencies: [Modules.CACHE, ContainerRegistrationKeys.LOGGER],
      options: {
        providers: [
          // default provider
          {
            resolve: "@medusajs/medusa/auth-emailpass",
            id: "emailpass",
          },
          {
            // if module provider is in a plugin, use `plugin-name/providers/my-auth`
            resolve: "./src/modules/my-auth",
            id: "my-auth",
            options: {
              // provider options...
            },
          },
        ],
      },
    },
  ]

```

By the way, Oliver's explanation also works with custom modules.

1. Some custom module's `index.ts`

```
import { Module } from "@medusajs/framework/utils";
import OtpModuleService from "./service";

export const OTP_MODULE = "otp";

export default Module(OTP_MODULE, {
  service: OtpModuleService,
});

```

2. Auth Module Provider's `index.ts`

```
import AuthOtpProviderService from "./service";
import { ModuleProvider, Modules } from "@medusajs/framework/utils";

export const AUTH_OTP_MODULE = "auth-otp";

export default ModuleProvider(Modules.AUTH, {
  services: [AuthOtpProviderService],
});

```

3. Extract of Auth Module Provider's `service.ts`

```
...
import { OTP_MODULE } from "../otp";
import OtpModuleService from "../otp/service";

type InjectedDependencies = {
  [OTP_MODULE]: OtpModuleService;
};

class AuthOtpProviderService extends AbstractAuthModuleProvider {
  static identifier = "auth-otp";
  static DISPLAY_NAME = "One Time Password (OTP) Authentication";
  protected otpService_: OtpModuleService;

  constructor(container: InjectedDependencies) {
    super();
    this.otpService_ = container[OTP_MODULE];
  }
...
}

export default AuthOtpProviderService;

```

4. Extract of `medusa-condif.ts`

```
...
import { OTP_MODULE } from "./src/modules/otp";

...

module.exports = defineConfig({
  modules: [
    {
      resolve: "./src/modules/otp",
    },
    {
      resolve: "@medusajs/medusa/auth",
      dependencies: [OTP_MODULE],
      options: {
        providers: [
          {
            resolve: "./src/modules/auth-otp",
            id: "otp",
          },
        ],
      },
    },
    ...
  ],
  ...
});

```

**Comment by shahednasser** [comment] 2025-05-12 06:20
@herveguetin nice catch! Will open a PR to fix the docs.
