### ISSUE TITLE
Can't run on macos

### ISSUE THREAD

**Issue by abdallahhelmy99** [medusajs/medusa#5836] opened 2023-12-10 16:13 UTC
### Describe the bug

Everytime I try to run medusa on macos I can't get it to work on the otherside when I tried the same steps on windows it worked normally.

### System information

Medusa version (including plugins): Latest version
Node.js version: v21.4.0
Database:
Operating system: MacOS
Browser (if relevant): Chrome

### Steps to reproduce the behavior

1. npx @medusajs/medusa-cli develop

### Expected behavior

A clear and concise description of what you expected to happen

### Screenshots

<img width="1470" alt="image" src="https://github.com/medusajs/medusa/assets/76593230/e4e75788-9432-4d4b-95ca-d921e27cdaa2">

<img width="1470" alt="image" src="https://github.com/medusajs/medusa/assets/76593230/0f577122-8362-4e95-9073-137033b6e2a3">

**Comment by riqwan** [comment] 2023-12-13 13:22
Hey @abdallahhelmy99, can you share the complete server logs you're getting?

Additionally, try with node 18 to see if that resolves the issue.

**Comment by dutchakdev** [comment] 2023-12-14 10:14
Darwin Romans-MBP 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:24 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6000 arm64
node version: v20.9.0

Working well

**Comment by riqwan** [comment] 2023-12-18 08:58
Closing this for now as I can't reproduce it. Please reopen if it still doesn't work with node 18 or 20 as mentioned by @dutchakdev

**Closed as completed by riqwan** 2023-12-18 08:58 UTC
Labels: type: bug, status: needs triaging
