### ISSUE TITLE
Admin UI: Invalid Request Header

### ISSUE THREAD

**Issue by pmltechpile** [medusajs/medusa#4904] opened 2023-08-29 18:33 UTC
Hello,

I recently deployed medusa's backend and Admin UI on aws using [this guide](https://pevey.com/medusa-server-on-ubuntu). I have a separate front end and through Cloudflare's service tunnels I am able to connect the two. Everything seems to be working fine except for the Admin UI. When I access the page all I see is `Invalid Host Header`. Not sure if this is a configuration issue on medusa's side or cloudlfare. I've tried everything I could to get this issue resolved but nothing seems to work.

**Comment by srindom** [comment] 2023-08-30 08:32
I haven't heard of this issue before - but from a google search of the error it sounds like it could be something with Webpack dev server. See this: https://stackoverflow.com/questions/43619644/i-am-getting-an-invalid-host-header-message-when-connecting-to-webpack-dev-ser

When deploying you shouldn't be starting the dev server - instead you should build your project and then run `medusa start` - so could imagine there is something wrong with your configuration. Can you share more details on the setup?

**Comment by cellis** [comment] 2023-09-01 22:25
@srindom I also have this issue with cloudflared tunnels. The problem is not that I'm _deploying_ medusa. It's to setup local dns resolvable names for development like store.mycompany.com instead of localhost:7001.

**Comment by sradevski** [comment] 2024-07-05 10:17
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏

**Closed as completed by sradevski** 2024-07-05 10:17 UTC
Labels: type: bug, status: needs triaging
