### ISSUE TITLE
API Ref(store): Issue in Create a Customer

### ISSUE THREAD

**Issue by udaykumar2104** [medusajs/medusa#5070] opened 2023-09-15 07:35 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

has_account is coming default as true when we create a customer 

### How can this issue be resolved?

1.it has to false in default
2.
3.

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment] 2023-09-15 08:25
Thank you for creating this issue. This is the expected behavior, since `has_account` indicates that this customer is a registered customer. You can learn more [here](https://docs.medusajs.com/modules/customers/#has_account-attribute).

Why do you expect it to be false?

**Comment by udaykumar2104** [comment] 2023-09-15 08:57
account is creating for the first time so it has to be false according to the document right..?

**Comment by shahednasser** [comment] 2023-09-15 09:02
No, it's `true` once the user is registered, which is what happens when you use the Create Customer endpoint. As mentioned in the documentation, it's `false` if a guest places an order and an account is created for that guest:

> For example, when a guest customer places an order, a new Customer record is created with the email used (if it doesn’t already exist) and the value for has_account is false. When the unregistered customer creates an account using the same email, a new Customer record will be created with the value of has_account set to true.

I'll close this issue for now. Feel free to re-open it or open a new one if you face any other issues.

**Closed as completed by shahednasser** 2023-09-15 09:02 UTC
Labels: type: docs

**Comment by udaykumar2104** [comment] 2023-09-15 09:11
how a guest customer is created..?

**Comment by shahednasser** [comment] 2023-09-15 09:17
As mentioned above, when a guest customer places an order, they're created as a `Customer` entity but with `has_account` set to `false` and associated with the order.

**Comment by udaykumar2104** [comment] 2023-09-15 09:20
i got that but how a guest customer is created is there any separate api.?
other that this POST:- /store/customers

**Comment by shahednasser** [comment] 2023-09-15 09:22
It's not created through an API, it's created within the Medusa backend's place order flow. In short, it uses the `CustomerService` directly to create the guest customer. The `CustomerService` is used within the Create Customer endpoint as well.

**Comment by udaykumar2104** [comment] 2023-09-15 09:24
okay thank for that..i got it

**Comment by pevey** [comment] 2023-09-15 14:46
You could create a custom endpoint for adding guest customers that calls the service in the same way Medusa does when a guest checks out.
