### ISSUE TITLE
Error while trying to remove line-item from cart

### ISSUE THREAD

**Issue by anup-a** [medusajs/medusa#1483] opened 2022-05-09 04:31 UTC
I'm getting an error while trying to hit the endpoint `
DELETE
/carts/:id/line-items/:line_id`.

As per the logs,
`update or delete on table "line_item" violates foreign key constraint "FK_5077fa54b0d037e984385dfe8ad" on table "line_item_tax_line"`

Medusa version - v1.2.1

Edit: Same issue after updating to v1.3

Edit: Even setting quantity to 0 is giving "unknow error", (which use to work well with v1.2.1)

**Comment by olivermrbl** [comment] 2022-05-16 08:27
I can't seem to reproduce this issue. Could you provide a couple of steps to get a minimal reproduction?

**Comment by anup-a** [comment] 2022-05-17 03:35
Got fixed after running these scripts. 👍

https://github.com/medusajs/medusa/blob/977e6086f40c5d5f2adf03155e2ec62c14f35f4d/docs/content/advanced/backend/upgrade-guides/1-3-1.md

**Comment by anup-a** [comment] 2022-05-17 04:09
Update - I'm still able to reproduce the error in the following scenario -
Add product to cart.
Then, go to the checkout page, and fill in address details and shipping details.
And now after the stripe element loads. Let's say we want to cancel/abort the payment and go back to the home page.
And now try to remove item from cart, it gives error.

```
[Node] error:   No such payment_intent: 'pi_3L0HdYGUCovRI0f32uNHx0LP'
[Node] StripeInvalidRequestError: No such payment_intent: 'pi_3L0HdYGUCovRI0f32uNHx0LP'
[Node]     at Function.generate (/Users/anup/Desktop/devs/one-pharmacy-backend/node_modules/medusa-payment-stripe-custom/node_modules/stripe/lib/Error.js:40:16)
[Node]     at res.toJSON.then.StripeAPIError.message (/Users/anup/Desktop/devs/one-pharmacy-backend/node_modules/medusa-payment-stripe-custom/node_modules/stripe/lib/StripeResource.js:220:35)
[Node]     at runMicrotasks (<anonymous>)
[Node]     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
[Node]   type: 'StripeInvalidRequestError',
[Node]   raw: {
[Node]     code: 'resource_missing',
[Node]     doc_url: 'https://stripe.com/docs/error-codes/resource-missing',
[Node]     message: "No such payment_intent: 'pi_3L0HdYGUCovRI0f32uNHx0LP'",
[Node]     param: 'intent',
[Node]     type: 'invalid_request_error',
[Node]     headers: {
[Node]       server: 'nginx',
[Node]       date: 'Tue, 17 May 2022 04:09:10 GMT',
[Node]       'content-type': 'application/json',
[Node]       'content-length': '255',
[Node]       connection: 'keep-alive',
[Node]       'access-control-allow-credentials': 'true',
[Node]       'access-control-allow-methods': 'GET, POST, HEAD, OPTIONS, DELETE',
[Node]       'access-control-allow-origin': '*',
[Node]       'access-control-expose-headers': 'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
[Node]       'access-control-max-age': '300',
[Node]       'cache-control': 'no-cache, no-store',
[Node]       'idempotency-key': '47ad5752-4bcd-4cd1-9ece-094e7f99cb79',
[Node]       'original-request': 'req_u6NSZo7AyPe5kM',
[Node]       'request-id': 'req_u6NSZo7AyPe5kM',
[Node]       'stripe-version': '2020-08-27',
[Node]       'strict-transport-security': 'max-age=31556926; includeSubDomains; preload'
[Node]     },
[Node]     statusCode: 404,
[Node]     requestId: 'req_u6NSZo7AyPe5kM'
[Node]   },
[Node]   rawType: 'invalid_request_error',
[Node]   code: 'resource_missing',
[Node]   doc_url: 'https://stripe.com/docs/error-codes/resource-missing',
[Node]   param: 'intent',
[Node]   detail: undefined,
[Node]   headers: {
[Node]     server: 'nginx',
[Node]     date: 'Tue, 17 May 2022 04:09:10 GMT',
[Node]     'content-type': 'application/json',
[Node]     'content-length': '255',
[Node]     connection: 'keep-alive',
[Node]     'access-control-allow-credentials': 'true',
[Node]     'access-control-allow-methods': 'GET, POST, HEAD, OPTIONS, DELETE',
[Node]     'access-control-allow-origin': '*',
[Node]     'access-control-expose-headers': 'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
[Node]     'access-control-max-age': '300',
[Node]     'cache-control': 'no-cache, no-store',
[Node]     'idempotency-key': '47ad5752-4bcd-4cd1-9ece-094e7f99cb79',
[Node]     'original-request': 'req_u6NSZo7AyPe5kM',
[Node]     'request-id': 'req_u6NSZo7AyPe5kM',
[Node]     'stripe-version': '2020-08-27',
[Node]     'strict-transport-security': 'max-age=31556926; includeSubDomains; preload'
[Node]   },
[Node]   requestId: 'req_u6NSZo7AyPe5kM',
[Node]   statusCode: 404,
[Node]   charge: undefined,
[Node]   decline_code: undefined,
[Node]   payment_intent: undefined,
[Node]   payment_method: undefined,
[Node]   payment_method_type: undefined,
[Node]   setup_intent: undefined,
[Node]   source: undefined
[Node] }
[Node] ::1 - - [17/May/2022:04:09:10 +0000] "DELETE /store/carts/cart_01G382Y7KDKTKZEMSKY2YZTWJ3/line-items/item_01G382Z8NE20PYS89F24XS0EAA HTTP/1.1" 500 86 "http://localhost:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36"
```

**Comment by olivermrbl** [comment] 2022-05-17 06:30
> And now try to remove the item from the cart, it gives error.

It looks like, you've previously been using a different Stripe account. Do you see the PaymentIntent `pi_3L0HdYGUCovRI0f32uNHx0LP` in your Stripe dashboard?

**Comment by olivermrbl** [comment] 2022-05-17 06:32
Would be great to create a new issue for this, since it's not related to removing line items. Closing for now. Let me know, if you find that to be okay.

**Closed by olivermrbl** 2022-05-17 06:32 UTC
Labels: status: needs reproduction, type: bug
