### ISSUE TITLE
[Bug]: Can not register a customer which already has an admin account, and vice versa (with same authentication provider)

### ISSUE THREAD

**Issue by karim-bakhsh** [medusajs/medusa#10607] opened 2024-12-14 11:11 UTC
### Package.json file

```JSON
{
  "name": "medusa-starter-default",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "dev": "medusa develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "latest",
    "@medusajs/cli": "latest",
    "@medusajs/framework": "latest",
    "@medusajs/medusa": "latest",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "awilix": "^8.0.1",
    "pg": "^8.13.0"
  },
  "devDependencies": {
    "@medusajs/test-utils": "latest",
    "@mikro-orm/cli": "5.9.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

v20.12.2

### Database and its version

PostgreSQL 14.15

### Operating system name and version

Ubuntu 22.04.5 LTS

### What happended?

I have registered an admin user with the email `john@doe.com` using the API `/auth/user/emailpass/register`. A new admin user has been created which I can authenticate to Medusa Admin panel through that. When I tried to register a customer using the same email through the API `/auth/customer/emailpass/register`, it threw an error saying `Identity with email already exists` while I didn't have any customer account with `john@doe.com`.

### Expected behavior

A customer account should have been created with the email I provided `john@doe.com`.

### Actual behavior

I could not create a customer account with the email `john@doe.com` which I had an admin user with that email. 

This happens because there is the a unique constraint of combine `entity_id` and `provider` are set to be unique, and as a result when I want to create another account for a different actor type and the same provider, there is a conflict because of that unique constraint. Another factor such as the actor type should also be considered in the unique constraint of `entity_id` and `provider`.

### Link to reproduction repo

https://github.com/medusajs/medusa

**Comment by olivermrbl** [comment] 2024-12-16 12:11
@karim-bakhsh, what you are experiencing is the expected behavior of our authentication flows, and let me tell you why.

The flow goes like this:

**Sign up as customer**
- `POST /auth/customer/emailpass/register` -> Creates an auth identity and returns a token
- `POST /store/customers` -> Use the token from the register call to register as a customer

Now, the auth identity you created in the first API call can be used to assume more than just the **customer** role. 

For example, let's say you want to allow a **company** actor to sign up on the storefront as well. Those company actors can be the same individual as your customer, so you would reuse the underlying auth identity for the authentication.

So, this is what you would do to sign up with the same identity:

**Sign up as company (provided you are already a customer)**
- `POST /auth/company/emailpass` -> Returns the already-created auth identity
- `POST /stores/companies` -> Use the token from the authenticate call to register as a company

As you can see, the second time around, you won't need to register again but only re-authenticate. The example above assumes that your `/store` paths allow a company actor, which is something you would configure with our `authenticate` middleware. 

If the `/store` paths don't allow the company, your second request:
```
POST /stores/companies`
```

would fail with a 401.

In this example above we use customer and company as the actor types, but the same behavior applies to customer and user.

You can read more about it in our [documentation](https://docs.medusajs.com/resources/commerce-modules/auth#main).

Let me know if this makes sense. Closing the issue as this is not a bug.

**Closed as completed by olivermrbl** 2024-12-16 12:11 UTC
Labels: status: needs triaging, version: 2.0

**Comment by jakub-borek** [comment] 2024-12-23 08:13
@olivermrbl Can we achieve sharing the same auth identity between 2 different actor types independent of which was created first?

Let's say Company was created first and then they want to also be a regular customer. Can the customer reuse company auth identity and vice versa if customer was created first?

How can we define which actor types can share same auth identity? Could you provide a simple example?
