### ISSUE TITLE
 Unable to parse workspace definition using medusa-dev command

### ISSUE THREAD

**Issue by Alool266** [medusajs/medusa#4835] opened 2023-08-22 21:09 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

While running the medusa-dev command in my Maroc4Products-backend directory, I encountered an error stating "Unable to read and parse the workspace definition from medusa package.json". This prevents me from successfully using the medusa-dev command for development.

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by medbenzekri** [comment] 2023-08-23 14:24
i suspect the issue is with the ```medusa-dev --set-path-to-repo `pwd` ``` when you have a path that contains spaces the full path will not be recognized with medusa-dev  so just change it to   ```medusa-dev --set-path-to-repo "`pwd`" ``` and hopfully its gona run smoothly

**Comment by sradevski** [comment] 2024-07-05 10:14
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏

**Closed as completed by sradevski** 2024-07-05 10:14 UTC
Labels: type: bug, status: needs triaging
