### ISSUE TITLE
[Bug]: Specific cart items are sealed with specific regions

### ISSUE THREAD

**Issue by kevin25** [medusajs/medusa#10462] opened 2024-12-06 02:37 UTC
### Package.json file

```JSON
I've been in E-Commerce owner for 8 years. I'm surprised that the items are sealed with specific regions.

I'm using WooCommerce and Shopify that allows customers to pick up items and change the shipping regions everywhere they want. 

But in medusa, it's impossible. If you pick the item at US region, then on checkout, only US address is available. This feature shouldn't have. Please consider this.
```

### Node.js version

v21.0

### Database and its version

Postgress 16.2

### Operating system name and version

Debiand 12

### What happended?

If you pick the item at US region, then on checkout, only US address is available. This feature shouldn't have. Please consider this.

### Expected behavior

I've been in E-Commerce owner for 8 years. I'm surprised that the items are sealed with specific regions.

I'm using WooCommerce and Shopify that allows customers to pick up items and change the shipping regions everywhere they want. 

### Actual behavior

No way to change the countries in checkout

### Link to reproduction repo

https://github.com/medusajs/

**Comment by sradevski** [comment] 2024-12-06 10:34
Regions can carry different pricing, product availability, and so on, so the problem is not as clear-cut as it seems. This is why you can create multiple regions.

Since this is not an issue, please use Discussions for feature requests or questions on architectural discussions. Closing the ticket.

**Closed as completed by sradevski** 2024-12-06 10:34 UTC
Labels: status: needs triaging, version: 2.0

**Comment by kevin25** [comment] 2024-12-07 02:49
This is not they way it work. We have the currency exchange that should work. Setting price for each regions is messy. That's why shopify don't make it. WooCommerce and other platform as well.
