### ISSUE TITLE
Sales channels error when disabled in feature flags

### ISSUE THREAD

**Issue by BeyondOT** [medusajs/medusa#8348] opened 2024-07-30 09:49 UTC
### Describe the bug

Error when trying to create a price_list when sales_channels are disabled.

::1 - - [30/Jul/2024:09:36:22 +0000] "GET /admin/customer-groups?limit=4&offset=0&expand=customers&q= HTTP/1.1" 304 - "http://localhost:7001/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Edg/127.0.0.0"
error:   Relation with property path sales_channels in entity was not found.
TypeORMError: Relation with property path sales_channels in entity was not found.

::1 - - [30/Jul/2024:09:36:31 +0000] "GET /admin/products?limit=20&offset=0&expand=variants%2Csales_channels%2Ccollection&q= HTTP/1.1" 500 86 "http://localhost:7001/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Edg/127.0.0.0"
error:   Relation with property path sales_channels in entity was not found.
TypeORMError: Relation with property path sales_channels in entity was not found.

### System information

Medusa version (including plugins): 1.20.9
Node.js version: 20.16.0
Database: Postgresql
Operating system: Windows 11
Browser (if relevant): Microsoft Edge

### Steps to reproduce the behavior

1. Disable sales_channels in feature flags.
2. Go to Price list in admin and click create.
3. Enter the title and description and click next, the first step should work well.
4. An error should occur in this step because the products can't be retrieved

### Expected behavior

To be able to create the price list by having the products retrieved properly. This is the behavior that happens when sales_channels are not disabled.

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by adevinwild** [comment] 2024-07-30 10:34
I think the problem is similar to my last PR (https://github.com/medusajs/medusa/issues/8102), I fixed it for the products but not for the rest sorry!
I'll take care of it ASAP 🙌

**Comment by sradevski** [comment] 2024-07-31 15:22
I'll close the issue as the fix was merged, should be available in the next release.

**Closed as completed by sradevski** 2024-07-31 15:22 UTC
Labels: type: bug, status: needs triaging
