### ISSUE TITLE
cannot configure db during backend creation

### ISSUE THREAD

**Issue by freaker2112** [medusajs/medusa#4272] opened 2023-06-09 16:03 UTC
### Describe the bug

When trying to create the medusa backend, I cannot get past the DB creation step. Selecting continue just shows the same output. I can select 'change credentials' and enter data into the fields but it will just spit out "Could not verify DB credentials - please try again" 

### System information

Medusa version (including plugins): 1.3.15
Node.js version: v19.7.0
Database: postgres
Operating system: ubuntu 20.04
Browser (if relevant):

### Steps to reproduce the behavior

1. run 'medusa new my-medusa-store'
2. Click on 'continue' or 'change credentials'

### Expected behavior

the credentials save and i can continue with setup

### Screenshots

![image](https://github.com/medusajs/medusa/assets/50562261/8d8fe6fb-b7a9-4415-9746-24420ea755dd)

###Additional info
nothing i set in 'change credentials' save. ex.: 
![image](https://github.com/medusajs/medusa/assets/50562261/ec9c7293-f8e1-4bd1-84c7-ddcf34b99319)

**Comment by absolutegravitas** [comment] 2023-06-27 10:22
Same -- in my case attempting to connect to Vercel Postgres

**Comment by zbingsong** [comment] 2023-07-03 16:54
I had the same problem when I tried to connect to Postgres on Docker. Turned out it was my VPN that automatically redirected medusa's requests. Maybe check your proxy/network configs?

**Comment by shurerider** [comment] 2023-08-02 01:07
Did you figure this out? Running into the same problem.

**Comment by corganfuzz** [comment] 2023-08-15 16:38
been dealing with this error for weeks. cannot get passed it

**Comment by rookiee-tech** [comment] 2023-08-16 04:13
yeah me too, any hope guys?

**Comment by olivermrbl** [comment] 2023-08-16 07:42
Can I get you to ensure you're using the latest version of our CLI: `npx @medusajs/medusa-cli@latest new new-project`

Also, if the provided credentials cannot establish a connection to your Postgres database, you are prompted for new ones. This will go on until a connection is successfully verified. I imagine this is what you are experiencing. Our error messaging in this scenario can be improved.

**Comment by LiamWinterton** [comment] 2023-08-16 11:12
> 

I think it might be more the fact that using the beta version of this (which is the default in the docs), you cannot specify a host.

I had to revert to using the old way of installing the backend on its own first in order to be able to specify a host. After that, everything worked fine.

Not really sure why this feature was dropped.

**Comment by rookiee-tech** [comment] 2023-08-16 13:11
> > 
> 
> I think it might be more the fact that using the beta version of this (which is the default in the docs), you cannot specify a host.
> 
> I had to revert to using the old way of installing the backend on its own first in order to be able to specify a host. After that, everything worked fine.
> 
> Not really sure why this feature was dropped.

can you tell me exactly how to install using old way?
many thanks

**Comment by LiamWinterton** [comment] 2023-08-16 13:51
@rookiee-tech I used this guide to install the backend on its own: https://docs.medusajs.com/development/backend/install

Here you can specify your DB's user, password, host and port which to me seems essential for standard setup.

You can then enable the admin by uncommenting the default plugin configuration in medusa-config.js on line 46-52

**Comment by corganfuzz** [comment] 2023-08-17 14:04
Figured out. In my case I've installed the cli and use create-medusa-app in macOs and Rocky linux. 

In macOS:

according to the postgres [docs](https://www.postgresql.org/download/macosx/) there are 3 ways to install postgres:

-  brew (this is how I get this error)
-  EDB (this was confusing plus it installs other software, ditched)
-  Postgres.app (recommended)

the issue with brew is that it uses the unix role authentication as default whereas **Postgres.app** will let you set up a username and password from the very beginning of the installation. if you want a set it and forget it solution **this is it.** . Once I uninstalled postgres with Brew and install it with the .app everything works as intended

in Rocky Linux:
```bash
sudo dnf install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm
sudo dnf -qy module disable postgresql
sudo dnf install -y postgresql15-server
sudo /usr/pgsql-15/bin/postgresql-15-setup initdb
sudo systemctl enable postgresql-15
sudo systemctl start postgresql-15
```
also you would need:
```bash
sudo dnf install -y postgresql15-contrib
```
In here, there is no GUI for setting up the postgres user name and the default unix role authentication applies. so what I did is to go to the pg_hba.conf file and **trust** it. [here](https://pankajconnect.medium.com/all-about-pg-hba-conf-authentication-methods-postgresql-95137d896105). that will allow you to login to the db with no password using:

```bash
psql -U postgres
```

then change the password. 
```bash
postgres=# ALTER USER postgres PASSWORD 'myPassword';
ALTER ROLE

```

go back to the pg_hba.conf and put it back to **md5** (read the link)

After that everything works as expected.

**Comment by lizozom** [comment] 2023-08-26 12:19
Still having trouble with this on Ubuntu.
What's the right way to setup `postgresql`? The setup instructions [here](https://docs.medusajs.com/development/backend/prepare-environment?os=linux#postgresql) seem not to be enough.

I connected to the `postgresql` and set the password for both the default 'postgres' user AND to a custom named user, but it did not help.

**Comment by lizozom** [comment] 2023-08-26 13:15
Figured it out for Ubuntu as well (Thanks ChatGPT!)

1. I uninstalled `postgresql` and reinstalled it with 
```
sudo apt install postgresql postgresql-contrib
```
2. I ran the psql console and changed the `postgres` user's password
```
sudo -u postgres psql
\password postgres # This starts an interactive dialogue to change the password
```
3. I deleted the previous `medusa` folder and re-ran 
```
medusa new my-store
```
5. I had to change the DB user to `postgres` and enter the password I chose.

This ended up working. Not sure what was wrong with the previous install, made with the setup instructions. 🤷🏻‍♀️

**Comment by ghost** [comment] 2024-06-08 11:52
### same me can't continue
<img width="991" alt="Screenshot 2567-06-08 at 18 52 03" src="https://github.com/medusajs/medusa/assets/163985666/23baf0a3-ddc6-4c95-a6dd-b062bf2e4062">

**Comment by ghost** [comment] 2024-06-08 12:13
> ### same me can't continue
> <img alt="Screenshot 2567-06-08 at 18 52 03" width="991" src="https://private-user-images.githubusercontent.com/163985666/337872141-23baf0a3-ddc6-4c95-a6dd-b062bf2e4062.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4NDc4NDMsIm5iZiI6MTcxNzg0NzU0MywicGF0aCI6Ii8xNjM5ODU2NjYvMzM3ODcyMTQxLTIzYmFmMGEzLWRkYzYtNGM5NS1hNmRkLWIwNjJiZjJlNDA2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQxMTUyMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YjMyNThiYTA5MTU0MmY1ZTNiMjM3NzYxMDIyNDRiZGVlNDU4YjUxMmFiODA0ODllMmI2NWNhMDAzNDFmNTVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WqIB0s0_tqfCxLEBGAbBh8r2m03LsS8ofAge7fWOptc">

I can fix this
-  medusa-config.js
- change DATABASE_URL -> "postgres://user:yourpass@localhost:5432/postgres";
- run ->medusa migrations run 
- run -> medusa seed --seed-file=data/seed.json
enjoy!!🥳

**Comment by sradevski** [comment] 2024-07-05 09:40
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏

**Closed as completed by sradevski** 2024-07-05 09:40 UTC
Labels: type: bug, status: needs triaging
