### ISSUE TITLE
Stripe error when I try to select Card Payment Method

### ISSUE THREAD

**Issue by lfdadev** [medusajs/medusa#5974] opened 2023-12-28 20:03 UTC
### Describe the bug

Error when I try to select Card Payment Method

### System information

Medusa version (including plugins): 1.19
Node.js version:
Database:
Operating system: Windows
Browser (if relevant): Chrome

### Steps to reproduce the behavior

Try to select card payment method

### Screenshots

![image](https://github.com/medusajs/medusa/assets/151443436/a0f6c919-8837-4032-838b-2d83bd298a85)

![image](https://github.com/medusajs/medusa/assets/151443436/4186cbfd-2546-43dd-a073-91dc19c5ab3e)

### Additional context

Someone told me that it could be a region error, but I cant find it.

Help me to finish this

**Comment by adrien2p** [comment] 2024-01-01 12:26
I think that first it would be nice to get the error instead of undefined. I ll look tomorrow to get you the steps to try and get the errors. And find out why it gives you undefined. From there it will be clearer what is happening

**Comment by davidFCDev** [comment] 2024-01-01 19:51
> I think that first it would be nice to get the error instead of undefined. I ll look tomorrow to get you the steps to try and get the errors. And find out why it gives you undefined. From there it will be clearer what is happening

I would be very grateful, I have been standing there for many days.

**Comment by adrien2p** [comment] 2024-01-02 08:50
in your node_modules under node_modules/@medusajs/medusa-payment-stripe/dist/core/stripe-base you should fine the following block
```ts
StripeBase.prototype.buildError = function (message, e) {
        var _a, _b;
        return {
            error: message,
            code: "code" in e ? e.code : "",
            detail: (0, medusa_1.isPaymentProcessorError)(e)
                ? "".concat(e.error).concat(os_1.EOL).concat((_a = e.detail) !== null && _a !== void 0 ? _a : "")
                : "detail" in e
                    ? e.detail
                    : (_b = e.message) !== null && _b !== void 0 ? _b : "",
        };
    };
    ```
It should be around line 382, would you be able to add a log such as `console.log("stripe error", e)` and share it please

**Comment by adrien2p** [comment] 2024-01-02 14:02
let me know when you have time to give us the output @davidFCDev

**Comment by davidFCDev** [comment] 2024-01-02 14:14
> let me know when you have time to give us the output @davidFCDev

Sorry @adrien2p , coming home! I will test and share it

**Comment by davidFCDev** [comment] 2024-01-02 15:50
@adrien2p Im on discord if you prefer to chat. Where I have to add the console.log ? just below the code you passed?

**Comment by chemicalkosek** [comment] 2024-01-03 10:25
To find the actual error it's best to check Stripe logs.

@adrien2p Remote errors coming from Stripe plugin are being `undefined` for some time now. Can't remember when it broke. I couldn't find in the codebase why the errors are not passed through.

**Comment by adrien2p** [comment] 2024-01-03 10:26
That is weird cause it is supposed to go through the error builder which try to get the message from the error. I d like the error and then fix the builder @chemicalkosek but it is not reproducible locally on his machine, only on railway

**Comment by davidFCDev** [comment] 2024-01-03 14:07
Its very stressful. I do not know what to do. I reinstalled the backend several times and it doesn't fix. I will try to check stripe logs for some clue

**Comment by adrien2p** [comment] 2024-01-03 15:31
@chemicalkosek especially that I don't see the error shape to change and we are trying to get all the info from everywhere
```ts
{
      error: message,
      code: "code" in e ? e.code : "",
      detail: isPaymentProcessorError(e)
        ? `${e.error}${EOL}${e.detail ?? ""}`
        : "detail" in e
        ? e.detail
        : e.message ?? "",
    }
    ```

**Comment by adrien2p** [comment] 2024-01-03 15:38
here is the error
```json
{
  "error": {
    "code": "resource_missing",
    "doc_url": "https://stripe.com/docs/error-codes/resource-missing",
    "message": "No such customer: 'cus_P4uVbdacZxaluV'",
    "param": "customer",
    "request_log_url": "...",
    "type": "invalid_request_error"
  }
}
```

As I explained, this remind me something when we had users playing with their database and the stripe sandbox and end up using the same ids in production. do you remember ?

**Comment by adrien2p** [comment] 2024-01-03 15:45
just for reference, it makes me think about those kind of env mixing https://discord.com/channels/876835651130097704/1156938278235295785/1156938278235295785

**Comment by chemicalkosek** [comment] 2024-01-03 15:45
Yes, most likely OP is using test and production stripe keys on the same database

**Comment by adrien2p** [comment] 2024-01-03 15:45
yes exactly 👍

**Comment by olivermrbl** [comment] 2024-01-03 16:26
@davidFCDev, are you associated with OP? 

Would like to close this and mark as duplicate, but only if OP's issue has been resolved too.

**Comment by adrien2p** [comment] 2024-01-03 16:37
we identified the root cause IMO which is more related to a miss uage/configuration IMO @olivermrbl

**Comment by davidFCDev** [comment] 2024-01-03 16:38
I have changed my user and it lets me select the payment method

**Comment by davidFCDev** [comment] 2024-01-03 16:39
In any case, it hasn't happened to me with only one user, at least with two

**Comment by adrien2p** [comment] 2024-01-03 16:44
just to summarize, the stripe_id attributed to the customer does not exists in the stripe env which in 99% of the cases means that at some points there was a mix of db and or stripe keys

**Comment by davidFCDev** [comment] 2024-01-03 17:04
Is there any way to clean the postgress database in Railways?

**Comment by adrien2p** [comment] 2024-01-03 17:08
I don't know railway, but maybe you can find something in the railway documentation to know if you can run sql queries and how. But at this point it is not related to medusa anymore.

**Comment by davidFCDev** [comment] 2024-01-03 17:10
Thanks for all the help @adrien2p

**Closed as completed** 2024-01-07 13:33 UTC
Labels: type: bug, status: needs triaging
