### ISSUE TITLE
It is possible to create many fulfillments for a single item in the order

### ISSUE THREAD

**Issue by AregMatulyan** [medusajs/medusa#2585] opened 2022-11-10 12:24 UTC
### Describe the bug
When a new order comes with more than one item, I can create many fulfillments for a single item in the order using a manual fulfillment provider.

### System information

Medusa version: 1.4.1
Node.js version: v16.17.0
Database: Postgres 14
Operating system: MacOS
Browser (if relevant): Chrome

### Steps to reproduce the behavior

1. The customer buys 2 products with a single order.
2. After a successful order admin opens the Orders tab in his administration panel.
3. In the Fulfillment section the admin clicks on the "Create Fulfillment" button.
4. inside of "Create Fulfillment" dialog he selects only one item for fulfillment and presses the "Complete" button.
5. The Fulfillment was created successfully.
6. Admin is able to create another fulfillment for the same item.

### Expected behavior
If the item in the order already has a fulfilment created, it should not be allowed to be included to other fulfilments

### Screenshots

![Screenshot 2022-11-10 at 13 21 44](https://user-images.githubusercontent.com/17296862/201090601-d8307248-a9a8-4c29-a0e8-0635b223dd30.png)

**Comment by olivermrbl** [comment] 2022-11-13 11:11
Thanks for reporting this one @AregMatulyan. I've added it to the backlog 💪

**Comment by olivermrbl** [comment] 2023-02-13 08:17
I am unable to reproduce this issue. I believe we should have fixed it as part of reworking the RMA modals, so I will close it for now.

Please don't hesitate to reopen, if you still have the issue when running with the latest Medusa Admin + core version.

**Closed by olivermrbl** 2023-02-13 08:17 UTC
Labels: type: bug
