### ISSUE TITLE
medusa CLI its not working 

### ISSUE THREAD

**Issue by Raoufbaa** [medusajs/medusa#6668] opened 2024-03-11 20:56 UTC
### System information

Medusa version (including plugins): sendgrid plugin 
Node.js version: 18.19.0
Database: local postgress
Operating system: kali linux
Browser (if relevant):chrome 

### The Issue Description 

I'm attempting to host MedusaJS on my VPS, but I want to use a different port than the default 9000. I've opted for port 44235. However, when I execute the command "medusa start -p 44235," I encounter the following issue. 
```
>  Medusa v2.2 [http://www.foofus.net] (C) JoMo-Kun / Foofus Networks <jmk@foofus.net>`

> ALERT: Host information must be supplied.


Syntax: Medusa [-h host|-H file] [-u username|-U file] [-p password|-P file] [-C file] -M module [OPT]
  -h [TEXT]    : Target hostname or IP address
  -H [FILE]    : File containing target hostnames or IP addresses
  -u [TEXT]    : Username to test
  -U [FILE]    : File containing usernames to test
  -p [TEXT]    : Password to test
  -P [FILE]    : File containing passwords to test
  -C [FILE]    : File containing combo entries. See README for more information.
  -O [FILE]    : File to append log information to
  -e [n/s/ns]  : Additional password checks ([n] No Password, [s] Password = Username)
  -M [TEXT]    : Name of the module to execute (without the .mod extension)
  -m [TEXT]    : Parameter to pass to the module. This can be passed multiple times with a
                 different parameter each time and they will all be sent to the module (i.e.
                 -m Param1 -m Param2, etc.)
  -d           : Dump all known modules
  -n [NUM]     : Use for non-default TCP port number
  -s           : Enable SSL
  -g [NUM]     : Give up after trying to connect for NUM seconds (default 3)
  -r [NUM]     : Sleep NUM seconds between retry attempts (default 3)
  -R [NUM]     : Attempt NUM retries before giving up. The total number of attempts will be NUM + 1.
  -c [NUM]     : Time to wait in usec to verify socket is available (default 500 usec).
  -t [NUM]     : Total number of logins to be tested concurrently
  -T [NUM]     : Total number of hosts to be tested concurrently
  -L           : Parallelize logins using one username per thread. The default is to process
                 the entire username before proceeding.
  -f           : Stop scanning host after first valid username/password found.
  -F           : Stop audit after first valid username/password found on any host.
  -b           : Suppress startup banner
  -q           : Display module's usage information
  -v [NUM]     : Verbose level [0 - 6 (more)]
  -w [NUM]     : Error debug level [0 - 10 (more)]
  -V           : Display version
  -Z [TEXT]    : Resume scan based on map of previous scan` 
```

So, I modified the start command in package.json to initiate it on that port initially. I successfully launched it on that port, and fetching the seeded product works perfectly. However, when I attempt to add new products, everything else functions properly except for loading the product image, resulting in this error.

` GET http://localhost:9000/uploads/1710085271304-images.jpg net::ERR_CONNECTION_REFUSED`
As I mentioned, I'm utilizing port 44235 instead of the default 9000, which is why the product images aren't loading. Also, it's worth mentioning that the same error occurs when running "medusa start," while "medusa create user" functions properly.

**Comment by xyzones** [comment] 2024-03-18 19:38
This has been discussed on Discord, this is not a bug but name conflict. Can we please close this.

**Closed as completed** 2024-03-18 19:42 UTC
Labels: type: bug, status: needs triaging
