### ISSUE TITLE
API Ref(store): Issue in Create a Customer

### ISSUE THREAD

**Issue by czw333221** [medusajs/medusa#5843] opened 2023-12-11 18:02 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

没有电话号码验证与邮箱验证很容易找不回密码

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment] 2023-12-12 08:05
Hi @czw333221 it's not clear what the issue is, can you explain more?

**Comment by shahednasser** [comment] 2024-01-18 09:03
Closing this for lack of responsiveness. Feel free to reopen when you have more details.

**Closed as completed by shahednasser** 2024-01-18 09:03 UTC
Labels: type: docs
