### ISSUE TITLE
Bug: Returning "capture" status from authorizePayment does not create order transactions.

### ISSUE THREAD

**Issue by lukegreaves5** [medusajs/medusa#9887] opened 2024-10-31 23:27 UTC
### Describe the bug

As a developer who has implemented a custom payment provider, I want to auto capture the payment. This is supported according to the docs by setting the status to "captured" instead of authorized.

when returning the status "captured" in the authorizePayment method, the capturePayment method is called immediately as expected, but the order transactions are not being created in the database, resulting in the order summary amounts being incorrect. For example, the paid_total amount on the order is still the full order amount. See screenshots below.

### System information

Medusa V2
Node.js version: v20.11.1
Database: Supabase
Operating system: MacOS Sonoma 14.4.1

### Steps to reproduce the behavior

1. Using a custom payment provider, set the return status in the authorizePayment method to "captured"
2. Set the return status in the capturePayment method to "captured"
3. Place an order
4. Got to your medusa admin and find the order - see the incorrect outstanding amount and order summary values not representing the captured amount.

### Expected behavior

Order summary amounts should represent the captured amount and the order transactions should be created in the database

### Screenshots

![Screenshot 2024-10-31 at 7 07 11 PM](https://github.com/user-attachments/assets/14aac622-a85e-4a04-b00b-3885273e6768)

![Screenshot 2024-10-31 at 7 05 34 PM](https://github.com/user-attachments/assets/ceae1304-1e00-40e3-b5bf-8fd8b23ea505)

![Screenshot 2024-10-31 at 7 19 51 PM](https://github.com/user-attachments/assets/4b482c06-4de8-42e8-bdf8-dcf307dd3d7e)

![Screenshot 2024-10-31 at 7 20 18 PM](https://github.com/user-attachments/assets/baf64ac9-8a65-495d-a9fc-213258f305db)

**Comment by sradevski** [comment] 2024-11-06 11:36
Thanks for the ticket, we'll have a look into it and let you know what the next steps are.

**Comment by lukegreaves5** [comment] 2024-11-12 17:04
Thanks @sradevski. Let me know if you would like more information or even a live demo. This bug is blocking development for me and is affecting downstream operations like fulfillment and refunds.

**Comment by fPolic** [comment] 2024-11-12 17:27
hey @lukegreaves5, a [PR](https://github.com/medusajs/medusa/pull/9980) that we merged today should fix your issue.
I'll close this for now but feel free to reopen if the issue is still present after we release a patch.

**Closed as completed by fPolic** 2024-11-12 17:27 UTC

**Comment by lukegreaves5** [comment] 2024-11-12 20:23
Excellent. Thank you so much!
