### ISSUE TITLE
create-medusa-app@latest doesn't use answers.postgresUsername and defaults always to "postgres"

### ISSUE THREAD

**Issue by agustif** [medusajs/medusa#4999] opened 2023-09-09 23:15 UTC
## Bug report

I hadn't been able to run the create-medusa-app util for a while, today decided to check out why exactly, I think the issue is the second call to try/catch postgres client after the answers are asked via cli code path is actually never executed.

### Describe the bug

Run `npx create-medusa-app@latest`
Asks for db username, provide username (which is my macOs username as is by default in brew's installs btw)

### System information

Medusa version (including plugins): latest
Node.js version: 20.4.0
Database: postgresql@15
Operating system: MacOS 14

### Steps to reproduce the behavior

1. Setup postgres in your environment without a default `postgres` username
2. run `npx create-medusa-app@latest`
3. Be asked for your custom postgres username/database, but it fails to connect and proceed to install anyways.
4. See error Couldn't connect to PostgreSQL.
(The error from the first try/catch of the first pgClient call in db-util is thrown, instead of using the answer credentials to try the second try/catch pgClient call block

### Expected behavior

To use my provided answers to authenticate instead of hardcoded postgres.

I got around this by creating a postgres user in my postgresql environment, but others might just abanadon the idea when face walled into an error that's not their fault, so I'm reporting this heh

### Code snippets
https://github.com/medusajs/medusa/blob/7a12aa04ac755c4bb4324d78a0bd1dc7d05757d2/packages/create-medusa-app/src/utils/create-db.ts#L43-L103

**Comment by olivermrbl** [comment] 2023-09-10 11:11
@shahednasser, can you provide some assistance here? :)

**Comment by agustif** [comment] 2023-09-10 21:32
fwiw In a second try using pnpm dlx instead of npx I had no issues, so maybe this can be closed and attributed to me missing some dependencies earlier?

**Comment by shahednasser** [comment] 2023-09-11 07:04
Thank you for submitting this issue @agustif but I couldn't reproduce this error. In the try-catch block, we first try using the default postgres credentials (`postgres` for the username and an empty password). If connecting with these credentials fail, we ask in the `catch` block for the username and password, then use the answer to connect again.

> fwiw In a second try using pnpm dlx instead of npx I had no issues, so maybe this can be closed and attributed to me missing some dependencies earlier?

when using npx, did you run `npx create-medusa-app@latest`? Did you use any options or anything that could lead to a different result that pnpm?

**Comment by agustif** [comment] 2023-09-11 18:44
Thank you @shahednasser , this is the original command I run.
`npx create-medusa-app@latest --with-nextjs-starter` 

I haven't been able to reproduce my original issue either since I created my -postgres- username named -postgres-. Would have to delete it to get my system back to that state.

Happy to leave it as a weird bug (maybe I was inoking some older create-medusa-app version)

Thank you for the help and have a nice week

**Comment by shahednasser** [comment] 2023-09-12 09:59
Thanks for the details! Will close this issue now as we can't reproduce it. If you happen to run into it again feel free to re-open the issue.

**Closed as completed by shahednasser** 2023-09-12 09:59 UTC
Labels: type: bug

**Comment by kensteele** [comment] 2024-03-28 12:18
This should be reopened per https://github.com/medusajs/medusa/discussions/4743#discussioncomment-8939782

Basically this occurs after a clean installation of `postgres` via `brew` on OSX prior to creating the project with the nextjs-starter.
```shell
npx create-medusa-app@latest --with-nextjs-starter
```
Looks like when the user specifies a username, the database name is also set to that username; for example, in the event of username `foo.bar`:
```
Couldn't connect to PostgreSQL because of the following error: error: database "foo.bar" does not exist.
```
I agree with @agustif 
> but others might just abandon the idea when face walled into an error that's not their fault

as this seem to be a fairly common setup.

I presented a workaround and proposed a couple fixes in https://github.com/medusajs/medusa/discussions/4743#discussioncomment-8939782, but happy to debug further, implement an npm fix and submit a PR if you want to assign it to me.

I think I'd need to be made a collaborator in order to reopen this issue.
