### ISSUE TITLE
Unable to access /store/payment-providers API route

### ISSUE THREAD

**Issue by TALHA0713** [medusajs/medusa#10781] opened 2024-12-31 12:26 UTC
Hi Medusa Team,
On this url **https://docs.medusajs.com/resources/storefront-development/checkout/payment** 
I’m facing an issue where I’m unable to access the /store/payment-providers API route.Also when i run api's  on postman some of the other APIs are working fine, but this particular one doesn’t return any results. 

Here’s the code I’m using to make the request:
const retrievePaymentProviders = async () => {
  const { payment_providers } = await fetch(
    `http://localhost:9000/store/payment-providers?region_id=${
      cart.region_id
    }`, {
      credentials: "include",
      headers: {
        "x-publishable-api-key": process.env.NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY || "temp",
      },
    })
    .then((res) => res.json())

  return payment_providers
}
Issue:
I am calling the /store/payment-providers route, but I am not getting any response.
Some other API routes are working fine, but this specific one doesn’t seem to be accessible.
Steps to Reproduce:
Run the backend on localhost:9000.
Make a fetch request to the /store/payment-providers route with the code provided above.
Observe that the API call does not return the expected data.
Expected Behavior:
I expect to get a list of payment providers in the response, but it’s not working.

Additional Notes:
I’ve checked the API key and confirmed it’s valid.
Some APIs are working, while others (like /store/payment-providers) are not.
also i have add Bareer Token but could not work please help regarding this issue.

**Comment by shahednasser** [comment] 2024-12-31 13:26
Hello, I couldn't reproduce this on my end. What Medusa version are you using? Can you share your `package.json`?

**Comment by TALHA0713** [comment] 2024-12-31 13:49
{
"name": "medusa-starter-default",
"version": "0.0.1",
"description": "A starter for Medusa projects.",
"author": "Medusa (https://medusajs.com)",
"license": "MIT",
"keywords": [
"sqlite",
"postgres",
"typescript",
"ecommerce",
"headless",
"medusa"
],
"scripts": {
"clean": "cross-env ./node_modules/.bin/rimraf dist",
"build": "cross-env npm run clean && npm run build:server && npm run
build:admin",
"build:server": "cross-env npm run clean && tsc -p tsconfig.server.json",
"build:admin": "cross-env medusa-admin build",
"watch": "cross-env tsc --watch",
"test": "cross-env jest",
"seed": "cross-env medusa seed -f ./data/seed.json",
"start": "cross-env npm run build && medusa start",
"start:custom": "cross-env npm run build && node --preserve-symlinks
--trace-warnings index.js",
"dev": "cross-env npm run build:server && medusa develop"
},
"dependencies": {
***@***.***/admin": "^7.1.16",
***@***.***/cache-inmemory": "1.8.11",
***@***.***/cache-redis": "^1.9.2",
***@***.***/event-bus-local": "1.9.9",
***@***.***/event-bus-redis": "^1.8.14",
***@***.***/file-local": "1.0.4",
***@***.***/medusa": "^1.20.9",
***@***.***/react-query": "4.22.0",
"body-parser": "^1.19.0",
"cors": "^2.8.5",
"dotenv": "16.3.1",
"express": "^4.17.2",
"medusa-fulfillment-manual": "1.1.41",
"medusa-interfaces": "1.3.10",
"medusa-payment-manual": "1.0.25",
"medusa-payment-stripe": "6.0.11",
"prism-react-renderer": "^2.0.4",
"typeorm": "0.3.16"
},
"devDependencies": {
***@***.***/cli": "^7.14.3",
***@***.***/core": "^7.14.3",
***@***.***/preset-typescript": "^7.21.4",
***@***.***/medusa-cli": "1.3.23",
***@***.***/number-float64-base-normalize": "0.0.8",
***@***.***/express": "^4.17.13",
***@***.***/jest": "^27.4.0",
***@***.***/mime": "1.3.5",
***@***.***/node": "^17.0.8",
"babel-preset-medusa-package": "^1.1.19",
"cross-env": "^7.0.3",
"eslint": "^6.8.0",
"jest": "^27.3.1",
"rimraf": "^3.0.2",
"ts-jest": "^27.0.7",
"ts-loader": "^9.2.6",
"typescript": "^4.5.2"
},
"jest": {
"globals": {
"ts-jest": {
"tsconfig": "tsconfig.spec.json"
}
},
"moduleFileExtensions": [
"js",
"json",
"ts"
],
"testPathIgnorePatterns": [
"/node_modules/",
"<rootDir>/node_modules/"
],
"rootDir": "src",
"testRegex": "(/__tests__/.*|\\.(test|spec))\\.(ts|js)$",
"transform": {
".ts": "ts-jest"
},
"collectCoverageFrom": [
"**/*.(t|j)s"
],
"coverageDirectory": "./coverage",
"testEnvironment": "node"
},
"resolutions": {
"glob": "^7.1.6"
}
}

**Comment by shahednasser** [comment] 2024-12-31 13:52
You're using Medusa v1 but referring to v2 docs. If you just installed this Medusa instance, refer to [this documentation](https://docs.medusajs.com/learn/installation) to install Medusa v2.

If you want to continue development with v1, refer to the [v1 docs](https://docs.medusajs.com/v1) instead.

Closing this issue for now. If you face other issues, please open an issue with the [correct template](https://github.com/medusajs/medusa/issues/new/choose) and provide all the necessary information to help you resolve your issue.

**Comment by TALHA0713** [comment] 2024-12-31 13:53
sure
{
"name": "medusa-next",
"version": "1.0.3",
"private": true,
"author": "Kasper Fabricius Kristensen ***@***.***> & Victor
Gerbrands ***@***.***> (https://www.medusajs.com)",
"description": "Next.js Starter to be used with Medusa server",
"keywords": [
"medusa-storefront"
],
"scripts": {
"dev": "next dev -p 8000",
"build": "next build",
"start": "next start -p 8000",
"lint": "next lint",
"analyze": "ANALYZE=true next build",
"test-e2e": "playwright test e2e"
},
"resolutions": {
"webpack": "^5",
***@***.***/react": "17.0.40"
},
"dependencies": {
***@***.***/react": "^1.6.1",
***@***.***/error-message": "^2.0.0",
***@***.***/framework": "^2.1.3",
***@***.***/link-modules": "^0.2.3",
***@***.***/medusa-js": "^6.1.7",
***@***.***/modules-sdk": "^1.12.3",
***@***.***/pricing": "^0.1.4",
***@***.***/product": "^0.3.4",
***@***.***/ui": "^2.2.0",
***@***.***/instant-meilisearch": "^0.7.1",
***@***.***/paypal-js": "^5.0.6",
***@***.***/react-paypal-js": "^7.8.1",
***@***.***/react-stripe-js": "^1.7.2",
***@***.***/stripe-js": "^1.29.0",
"algoliasearch": "^4.20.0",
"axios": "^1.6.7",
"lodash": "^4.17.21",
"medusa-payment-manual": "^1.0.25",
"medusa-react": "^9.0.0",
"next": "^14.0.0",
"next-i18next": "^15.3.1",
"next-intl": "^3.20.0",
"path": "^0.12.7",
"pg": "^8.11.3",
"react": "^18.3.1",
"react-country-flag": "^3.0.2",
"react-dom": "^18.3.1",
"react-hot-toast": "^2.4.1",
"react-i18next": "^15.0.2",
"react-instantsearch-hooks-web": "^6.29.0",
"react-intersection-observer": "^9.3.4",
"react-player": "^2.16.0",
"tailwindcss-radix": "^2.8.0",
"webpack": "^5"
},
"devDependencies": {
***@***.***/core": "^7.17.5",
***@***.***/client-types": "^0.2.2",
***@***.***/medusa": "^1.18.0",
***@***.***/ui-preset": "^1.0.2",
***@***.***/test": "^1.41.1",
***@***.***/lodash": "^4.14.195",
***@***.***/node": "17.0.21",
***@***.***/pg": "^8.11.0",
***@***.***/react": "^18.2.42",
***@***.***/react-dom": "^18.2.18",
***@***.***/react-instantsearch-dom": "^6.12.3",
"autoprefixer": "^10.4.2",
"babel-loader": "^8.2.3",
"eslint": "8.10.0",
"eslint-config-next": "^13.4.5",
"postcss": "^8.4.8",
"prettier": "^2.8.8",
"tailwindcss": "^3.0.23",
"typescript": "^5.3.2"
}
}

**Closed as not planned** 2024-12-31 13:53 UTC
Labels: type: bug, status: needs triaging

**Comment by TALHA0713** [comment] 2024-12-31 13:56
Can you please give me apis of v1

**Comment by shahednasser** [comment] 2024-12-31 13:57
You can find them here: [https://docs.medusajs.com/v1/api/store](https://docs.medusajs.com/v1/api/store)

**Comment by TALHA0713** [comment] 2024-12-31 14:07
Thanks for this But i could not find Payment provider api in this docs
and last I want to ask  Can you please tell me I want to add the custom
payment provider and attach the Easy Paisa or any other payment gateway
can you please give me suggestion how i can.
i am create a custom Provider
*https://docs.medusajs.com/resources/references/payment/provider
<https://docs.medusajs.com/resources/references/payment/provider> *using
this doc in backend admin but it gives me type script error because i am
using this type script version when i am upgrade the version whole it shows
me error please suggest me
its a humble request to you kindly help me regarding this issue please give
me suggestion how i can add this payment method in my cart
{
"compilerOptions": {
"target": "es2019",
"allowJs": true,
"esModuleInterop": true,
"module": "commonjs",
"moduleResolution": "node",
"emitDecoratorMetadata": true,
"experimentalDecorators": true,
"skipLibCheck": true,
"skipDefaultLibCheck": true,
"declaration": true,
"sourceMap": false,
"outDir": "./dist",
"rootDir": "./src",
"baseUrl": ".",
"jsx": "react-jsx",
"forceConsistentCasingInFileNames": true,
"resolveJsonModule": true,
"checkJs": false
},
"include": ["src/"],
"exclude": [
"**/__tests__",
"**/__fixtures__",
"node_modules",
"build",
".cache"
]
}
