### ISSUE TITLE
[PriceListService] LIST function not working but ListAndCount work

### ISSUE THREAD

**Issue by AlexDigital974** [medusajs/medusa#1831] opened 2022-07-11 11:41 UTC
### Describe the bug
 i take the req.scope.resolve("priceListService") price list service and want to list the data using the list function and get an error on the query level,asking about   price_list.price_list_id  column that don't exist.

### Steps to reproduce the behavior

      const priceListService = req.scope.resolve("priceListService") ;
      console.log(await priceListService.list(); <---error
      console.log(await priceListService.listAndCount(); <---work

 **driverError: error: column price_list.price_list_id does not exist**

### Expected behavior

list should also work.
Just to be sure i try other service like customer/user/ just to be sure i can run list() and they all work
Out of curiosity i immidiately run the listAndCount() and that is working byd default with or without params.

i also run the migration maybe my db wasn't up to date
medusa migrations run

### Additional context

Strange thing if i just run list() without any params it look like that price_list_id is expected and not optional 

check my db i understand that price_list_id does not exist its just id .

Full error query
query: 'SELECT "price_list"."id" AS "price_list_id", "price_list"."created_at" AS "price_list_created_at", "price_list"."updated_at" AS "price_list_updated_at", "price_list"."deleted_at" AS "price_list_deleted_at", "price_list"."name" AS "price_list_name", "price_list"."description" AS "price_list_description", "price_list"."type" AS "price_list_type", "price_list"."status" AS "price_list_status", "price_list"."starts_at" AS "price_list_starts_at", "price_list"."ends_at" AS "price_list_ends_at" FROM "price_list" "price_list" WHERE ( ("**price_list.price_list_id = $1)** ) AND ( "price_list"."deleted_at" IS NULL ) LIMIT 20

### System information
MEDUSA 1.3.1 ,
meilisearch
Node.js version: v16.13.2
Database: postgres
Operating system: mac

**Comment by olivermrbl** [comment] 2022-07-11 16:24
Thanks for the elaborate rundown of the issue. We'll attend to it asap! 

Duplicate of #1336.

**Comment by olivermrbl** [comment] 2022-07-13 14:18
Fixed in #1843

**Closed by olivermrbl** 2022-07-13 14:18 UTC
Labels: type: bug
