### ISSUE TITLE
Getting this error when setup medusa mono repo

### ISSUE THREAD

**Issue by Navneet2213** [medusajs/medusa#5789] opened 2023-12-02 16:43 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

steps i do
1. clone mono repo
2. run yarn install
3. run yarn build

![image](https://github.com/medusajs/medusa/assets/81297446/e2885769-779c-4073-840f-c3b62e3be53e)

### How can this issue be resolved?

1.
2.
4.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by oliwerhelsen** [comment] 2023-12-09 21:08
Same for me. Getting some type issues in multiple packages. Some regarding "clearInterval" and some within admin-ui regarding babel mismatch.

**Comment by riqwan** [comment] 2023-12-11 13:13
@Navneet2213 @oliwerhelsen 

Can you share more details on this?
- Node version
- Yarn version
- OS

I just ran with the latest develop and works fine for me with OSX, node 18.5 and yarn 3.2.1

Do pull the latest develop branch and try again. It might just be a broken commit. If the error persists, can you share the screenshot with the error message as well?

**Comment by Navneet2213** [comment] 2023-12-11 13:43
@riqwan 

node:- 20.10.0
yarn:- 3.2.1 if I run "yarn set version classic" then it changes to 1.22.21
os:- windows

**Comment by riqwan** [comment] 2023-12-11 14:29
I can reproduce this with `yarn set version classic`. Can you try with 3.2.1 from a fresh install? package.json is configured for 3.2.1.

**Comment by riqwan** [comment] 2023-12-13 11:03
@Navneet2213 , @oliwerhelsen let me know if this works for you with yarn 3.2.1, since we're only supporting running the monorepo with yarn berry. Closing this for now, feel free to reopen if you still have issues with yarn berry.

**Closed as completed by riqwan** 2023-12-13 11:03 UTC
Labels: type: bug, status: needs triaging

**Comment by oliwerhelsen** [comment] 2023-12-13 12:52
@riqwan yeah, you are totally right. My bad, I was using Yarn 1.22 🤦 . Wokring fine now!
