### ISSUE TITLE
[Bug]: Stripe payments - customers unable to checkout - checkout error

### ISSUE THREAD

**Issue by chillpilllike** [medusajs/medusa#10093] opened 2024-11-14 05:11 UTC
### Package.json file

```JSON
{
  "name": "medusa-starter-default",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "predeploy": "medusa db:migrate",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "dev": "medusa develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "latest",
    "@medusajs/cli": "latest",
    "@medusajs/framework": "latest",
    "@medusajs/medusa": "latest",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "awilix": "^8.0.1",
    "pg": "^8.13.0"
  },
  "devDependencies": {
    "@medusajs/test-utils": "latest",
    "@mikro-orm/cli": "5.9.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

20

### Database and its version

16

### Operating system name and version

22.04

### What happended?

The stripe checkout giving error

### Expected behavior

The payment should be successful

### Actual behavior

Getting error:

http:    POST /store/payment-collections ← - (200) - 40.023 ms
error:   An error occurred in cancelPayment:
Stripe: Argument "intent" must be a string, but got: undefined (on API request to `POST /v1/payment_intents/{intent}/cancel`)
{
  message: 'An error occurred in cancelPayment:\n' +
    'Stripe: Argument "intent" must be a string, but got: undefined (on API request to `POST /v1/payment_intents/{intent}/cancel`)',
  name: 'Error',
  stack: 'Error: An error occurred in cancelPayment:\n' +
    'Stripe: Argument "intent" must be a string, but got: undefined (on API request to `POST /v1/payment_intents/{intent}/cancel`)\n' +
    '    at PaymentProviderService.throwPaymentProviderError (/app/medusa-starter-default/node_modules/@medusajs/payment/src/services/payment-provider.ts:149:11)\n' +
    '    at PaymentProviderService.deleteSession (/app/medusa-starter-default/node_modules/@medusajs/payment/src/services/payment-provider.ts:77:12)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n' +
    '    at async PaymentModuleService.createPaymentSession (/app/medusa-starter-default/node_modules/@medusajs/payment/src/services/payment-module.ts:330:9)\n' +
    '    at async Proxy.<anonymous> (/app/medusa-starter-default/node_modules/@medusajs/orchestration/src/workflow/local-workflow.ts:129:20)\n' +
    '    at async Object.exports.createPaymentSessionStep.async.container.container (/app/medusa-starter-default/node_modules/@medusajs/core-flows/src/payment-collection/steps/create-payment-session.ts:27:21)\n' +
    '    at async Object.invoke (/app/medusa-starter-default/node_modules/@medusajs/workflows-sdk/src/utils/composer/helpers/create-step-handler.ts:72:52)\n' +
    '    at async DistributedTransaction.handler (/app/medusa-starter-default/node_modules/@medusajs/orchestration/src/workflow/workflow-manager.ts:214:16)\n' +
    '    at async stepHandler (/app/medusa-starter-default/node_modules/@medusajs/orchestration/src/transaction/transaction-orchestrator.ts:806:20)\n' +
    '    at async Promise.allSettled (index 0)\n' +
    '⮑ sat /app/medusa-starter-default/node_modules/@medusajs/core-flows/dist/payment-collection/workflows/create-payment-session.js: [create-payment-sessions -> create-payment-session (invoke)]',
  __isMedusaError: true,
  type: 'invalid_data',
  code: 'unknown',
  date: 2024-11-14T05:07:07.259Z
}
http:    POST /store/payment-collections/pay_col_01JCMH2T086VXAKDBVRPRV6M7F/payment-sessions ← - (400) - 346.295 ms

### Link to reproduction repo

https://github.com/medusajs/medusa-starter-default.git

**Comment by Xarenn** [comment] 2024-11-14 08:52
i have the same issue :)

**Comment by olivermrbl** [comment] 2024-11-15 21:13
@chillpilllike, would it be possible for you to provide the reproducible steps given a fresh Medusa project?

**Comment by chillpilllike** [comment] 2024-11-17 16:12
The error comes after we do a live transaction and it cancels in the middle.

**Comment by olivermrbl** [comment] 2024-11-17 16:23
@chillpilllike, I am asking because I am afraid it might be related to the Stripe payment intent not being created correctly, and I want to reproduce it. 

If the payment intent creation fails, our workflow will attempt to roll back, which in this case means it tries to delete the created payment intent. However, it looks like the payment intent was never actually created in the first place, leading to the `intent must be a string` error.

Does your server logs tell you anything else than what you included in the description above?

Alternatively, you might be able to find more clues in the Stripe dashboard. They are generally good at providing insights into payment failures. Can you let me know?

**Comment by adrien2p** [comment] 2024-11-18 09:30
hi @chillpilllike ,

thank you for pointing out this issue. It should be fixed soon.

Just to let you know about what happened here:
- we create a local payment session
- we call the payment provider to create the payment
  - stripe failed
- we catch the error and do the following
  - delete the local payment session
  - delete the provider payment ------> since it failed above, we were trying to delete something that does not exists

**Comment by adrien2p** [comment] 2024-11-18 09:58
should be closed by https://github.com/medusajs/medusa/pull/10135

**Closed as completed** 2024-11-18 17:45 UTC
Labels: version: 2.0

**Comment by julianengel** [comment] 2024-11-21 10:39
Hi! Facing the same issue in 2.04 with 
```
Stripe: Argument "intent" must be a string, but got: undefined (on API request to `POST /v1/payment_intents/{intent}/cancel`)
error:   Could not delete all payment sessions
{
  message: 'Could not delete all payment sessions',

```

before it even has a chance to create an intent. Is there a workaround until the next version with #10135 is released?

**Comment by julianengel** [comment] 2024-11-21 13:02
We're not able to do anything with the stripe checkout at the moment, because we constantly run into:
```
{"code":"unknown","type":"invalid_data","message":"An error occurred in cancelPayment:\nStripe: Argument \"intent\" must be a string, but got: undefined (on API request to `POST /v1/payment_intents/{intent}/cancel`)"}

Stripe: Argument "intent" must be a string, but got: undefined (on API request to `POST /v1/payment_intents/{intent}/cancel`)
```
Any idea how to fix this is the meantime?
@adrien2p

**Comment by chillpilllike** [comment] 2024-11-21 15:16
Please guys help, I am also stuck. tell us a way to do it manually but the time you release it.

**Comment by adrien2p** [comment] 2024-11-21 15:22
hey @julianengel, @chillpilllike  and everyone, 

sorry for the later answer but it seems a release will be cut out tomorrow, you should be able to update to it soon then

**Comment by julianengel** [comment] 2024-11-21 17:21
Hey @adrien2p!

No worries at all! Did not mean to pressure you in any way, and I super appreciate what y'all are doing. 

we're just in the process of migrating our store from WooComerce to Medusa, and Stripe (and by extension BLIK) are super important. I've managed to patch it in a super hacky way of editing the node modules for now. 

As soon as we're live, I'll revert back and see what we can do about sponsoring the project ;)

Thanks for your hard work!

**Comment by Tyerlo** [comment] 2024-11-22 09:55
I ran into this issue first time today, I just tried to change the payment module to klarna and the error appears inside medusa.configt.ts.

Im using nextjs-starter.
