### ISSUE TITLE
Multi - vendor plugin

### ISSUE THREAD

**Issue by pragnikadia** [medusajs/medusa#3348] opened 2023-03-01 05:42 UTC
does medusa provide multi-vendor plugin??.. if yes then how can we install that in existing medusa project

**Comment by SGFGOV** [comment] 2023-03-01 06:52
Short answer is what do you mean by multivendor?

Do you mean a marketplace vendor module or a shopify like multi store?

**Comment by pragnikadia** [comment] 2023-03-01 09:27
marketplace vendor module

**Comment by pragnikadia** [comment] 2023-03-03 06:24
is there any update, can just please let me know that if it is posible via any plugin or do i have to customized on my side, can you give me some reference??

**Comment by SGFGOV** [comment] 2023-03-03 12:26
Have you used the market place example using the extender

**Comment by pragnikadia** [comment] 2023-03-03 12:42
can you give me resource link here

**Comment by olivermrbl** [comment] 2023-03-04 17:12
Closing this as this is not a bug. Please take a look at our Discussions for feature requests. The [multi-vendor feature has already been requested](https://github.com/medusajs/medusa/discussions/2769).

**Closed by olivermrbl** 2023-03-04 17:12 UTC
Labels: type: bug, status: needs triaging
