### ISSUE TITLE
the total of the order is displayed with this format €NaN

### ISSUE THREAD

**Issue by rida-re** [medusajs/medusa#4278] opened 2023-06-11 06:01 UTC
Hello,
how can I fix this problem knowing that the web service does not report the total according to the JOSN response.

### System information

Medusa version (including plugins): ^1.12.0
Node.js version: v16.15.0
Database: postgres
Operating system:windows
Browser (if relevant):chrome

### Steps to reproduce the behavior

list orders in my account

### Screenshots
![image](https://github.com/medusajs/medusa/assets/58844180/a091ef76-7e99-40f4-b5dc-8da34c78ffb6)

![image](https://github.com/medusajs/medusa/assets/58844180/8869adb0-7441-41a5-a5da-cc2c602defac)

### Code snippets
``

### Additional context

StoreFront B2B

**Comment by tsvetann** [comment] 2023-06-12 08:53
possibly a duplicate of [#4246](https://github.com/medusajs/medusa/issues/4246)

**Comment by adrien2p** [comment] 2023-06-13 10:46
should be fixed by [this](https://github.com/medusajs/medusa/pull/4294) just waiting approval

**Comment by olivermrbl** [comment] 2023-06-18 19:23
Closed by #4294

**Closed as completed by olivermrbl** 2023-06-18 19:23 UTC
Labels: type: bug, status: needs triaging
