### ISSUE TITLE
[Bug]: Add cart and place order so slowly

### ISSUE THREAD

**Issue by hans642** [medusajs/medusa#10751] opened 2024-12-27 07:05 UTC
### Package.json file

```JSON
{
  "name": "medusa-starter-default",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "dev": "medusa develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "2.1.2",
    "@medusajs/cli": "2.1.2",
    "@medusajs/framework": "2.1.2",
    "@medusajs/medusa": "2.1.2",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "awilix": "^8.0.1",
    "pg": "^8.13.0"
  },
  "devDependencies": {
    "@medusajs/test-utils": "2.1.2",
    "@mikro-orm/cli": "5.9.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

v20.15.1

### Database and its version

16.4

### Operating system name and version

macOS 15.1

### Browser name

Chrome

### What happended?

Here is api time record:

http:    POST /store/carts/cart_01JG3EPW3YQXRD4AEN80Z583WK/line-items ← - (200) - 13558.242 ms
http:    POST /store/carts/cart_01JG3EPW3YQXRD4AEN80Z583WK/complete ← - (200) - 17250.425 ms

spend many times, how can reduce it?

### Expected behavior

Time cost need less 5000ms

### Actual behavior

Time cost more than 10000ms

### Link to reproduction repo

medusa(v2)

**Comment by docloulou** [comment] 2024-12-27 07:53
Hi,
API call on prod or dev ? 
how many price rules ?

**Comment by hans642** [comment] 2024-12-27 08:00
In dev environment. 
Use default price rule, not set Price Lists and Promotions

**Comment by docloulou** [comment] 2024-12-27 08:23
in dev, api call are slower, but not as much.
First, try yarn run build (for test prod perf) and if you are working on windows, try with WSL env (not windows).

**Comment by riqwan** [comment] 2024-12-27 15:08
Hey @hans642, can you share your medusa-config? Also, where is your database hosted?

**Comment by nishit-g** [comment] 2024-12-27 15:11
facing similar issue, hosted the nextjs-medusja-starter on vercel hobby plan and for db supabase (free tier) while the backend service is on railway (hobby plan)

**Comment by riqwan** [comment] 2024-12-27 15:14
@nishit-g Can you tell me where the regions for your server and db are currently?

Set the region for both your database and server in the same place. Better, if its in the same network and try again. 

What's the avg response rates you're experiencing right now?

**Comment by SaintsPrinting** [comment] 2024-12-27 15:27
Had that same issue in almost the same scenario and it was because my supabase db was on east-1 and my railway account was in the hobby tier at us-west, and you can't switch to a different region without paying for the pro plan in railway. After changing the regions, everything was quick

**Comment by nishit-g** [comment] 2024-12-27 16:51
@SaintsPrinting @riqwan thanks a lot ! Just migrated by db region to near my server region and things are working fast now.

**Comment by riqwan** [comment] 2024-12-27 17:03
Glad to hear that @nishit-g. @hans642 let me know if that works out for you as well. Closing this for now, feel free to reopen if anything else pops up!

**Closed as completed by riqwan** 2024-12-27 17:03 UTC
Labels: status: needs triaging, version: 2.0

**Comment by hans642** [comment] 2024-12-29 00:47
I also put the  server in local and db in ap-east-1, maybe be the network is not good, if i put the database in local, its work well. thank @riqwan .

**Comment by joekendal** [comment] 2024-12-29 12:59
@riqwan I think we should re-open this issue. It appears to be something unrelated to the distance. I'm getting 4000ms delays even with local infra when it is near instant write speeds directly through postgres. Something doesn't make sense here.

**Comment by riqwan** [comment] 2024-12-29 13:04
@joekendal can you share more details on what exactly you're trying to do?

Additionally, some more info:

- how many products/prices you have in your db?
- what does the cart response look like after the 4000 ms request?
- How much memory do you have on your laptop, and, how much of it does node have access to?

**Comment by joekendal** [comment] 2025-01-01 07:13
We should probably switch to bun or deno, this is way too slow for production use cases

**Comment by riqwan** [comment] 2025-01-01 07:17
@joekendal were gonna need some more info and debugging help requested earlier before that can be considered.

**Comment by jamaybyrone** [comment] 2025-01-01 23:35
I am also being affected 10-15 seconds to add to cart, set up:

- Backend, postgress - railway all in same location (us West Oregon)
- Frontend - vercel (london)
above gave me 12-15 seconds

I switched frontend over to railway and set location to be us west Oregon
which then gave 10 seconds response times.

Products: 7
Categories : 5 then 2 nested so (7 total)

The products have variants. (if that matters? maybe?)

Price lists: none
![image](https://github.com/user-attachments/assets/658d259b-a905-4e53-8d3d-4b21b816431a)
The above image is the backend logs

Postgress: `checkpoint complete: wrote 7 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.604 s, sync=0.012 s, total=0.623 s; sync files=4, longest=0.011 s, average=0.003 s; distance=4 kB, estimate=149 kB; lsn=0/22C6CD8, redo lsn=0/22C6CA0`

The bottle neck appears to be the backend, I can see 10 seconds worth of so many queries going on, some seem duplicate. happy to provide full logs if its useful.

Here is start:
![image](https://github.com/user-attachments/assets/ef8c9bab-693a-4906-98dd-5ee57a46354b)

Here is the end:
![image](https://github.com/user-attachments/assets/946faa38-e621-4bbd-8782-5a4479402204)

So that's 10 seconds of queries, from the backend from that 1 post request.

**Comment by joekendal** [comment] 2025-01-01 23:43
@jamaybyrone as you can see by the implementation: https://github.com/medusajs/medusa/blob/develop/packages/core/core-flows/src/cart/workflows/add-to-cart.ts 

The workflow makes several requests instead of just one.

It looks really inefficient

**Comment by riqwan** [comment] 2025-01-02 08:50
Thanks @jamaybyrone, what's your instance's RAM and CPU specs? 

Additionally, do you have metrics on what it looks like during a request?

**Comment by jamaybyrone** [comment] 2025-01-02 09:08
Hi @riqwan below are the specs for backend:
<img width="421" alt="image" src="https://github.com/user-attachments/assets/a091d7c3-197f-4f59-9c09-0b302f3766a6" />

So 51 queries (from 1 post...)

`select "a0"."id", "a0"."token" from "public"."api_key" as "a0" where "a0"."token" `-  this is done 5 times...
`select "l0".* from "public"."cart_line_item" as "l0" where "l0"."deleted_at" is null and "l0"."cart_id"` - this is done 3 times..
`select "p0"."id", "p0"."code" from "public"."promotion" as "p0" where "p0"`  - this is done 3 times..

average time for each is around 138ms biggest is 157ms

**Comment by riqwan** [comment] 2025-01-02 09:16
those queries look fine to me, its normal that it hits a lot of them due to the distributed nature of the architecture.<br><br>Just to rule out the memory issues, can you increase the RAM temporarily to 6GB and set this environment variable:<br><br>`NODE_OPTIONS=--max-old-space-size=4096`<br><br>Let me know if that changes the performance in any way.

**Comment by joekendal** [comment] 2025-01-02 09:32
Do we really need all these requests? I think we could remove:
```ts
refreshCartItemsWorkflow.runAsStep({
   input: { cart_id: cart.id },
})
```
^ And replace with a transform

```ts
const cartQuery = useQueryGraphStep({
      entity: "cart",
      filters: { id: input.cart_id },
      fields: cartFields,
      options: { throwIfKeyNotFound: true },
    }).config({ name: "get-cart" })

    const cart = transform({ cartQuery }, ({ cartQuery }) => {
      return cartQuery.data[0]
    })

...

const { itemsToCreate = [], itemsToUpdate = [] } = getLineItemActionsStep({
      id: cart.id,
      items: lineItems,
    })
```

^ and modify the getLineItemActionsStep to use the cartQuery instead of having multiple requests.

We could also avoid having the confirm variant inventory do a for loop (this was meant to be done in bulk according to the code author): https://github.com/medusajs/medusa/blob/develop/packages/core/core-flows/src/cart/steps/confirm-inventory.ts#L31

Given these optimisations, we could significantly reduce the amount of latency.

**Comment by jamaybyrone** [comment] 2025-01-02 09:51
@riqwan made the changes: 10seconds
<img width="426" alt="image" src="https://github.com/user-attachments/assets/5f8f2129-6ef1-47bc-b591-a4e877831d1f" />
Just so I understand, your telling me its normal for it to do 51 queries from 1 post request?

**Comment by joekendal** [comment] 2025-01-02 09:54
@jamaybyrone the reason it does 51 queries is because it is doing a lot of unnecessary steps. I've outlined how we can rewrite the add to cart logic to reduce the number of requests and improve it significantly. We need to re-open this issue and create a new pull request

**Comment by riqwan** [comment] 2025-01-02 10:05
@jamaybyrone yes, because the cart operations need to refresh any shipping options, promotions, pricing rules, taxes, etc. thats already been applied to bring the cart to its most accurate state. There can be some improvements made here, but those are unlikely the reason why you're having 10s long requests. You can see that the demo https://demo.medusajs.com/ is running pretty quickly. 

I'll run a deployment on Railway later today and see if i can find anything. 

@joekendal `refreshCartItemsWorkflow` is a necessary workflow for all the above reasons i mentioned ^. We have plans to make a bulk confirmation function, but that will take a bit to work on. 

Also, all of these steps are exported, you can indeed create your own custom API endpoint with a workflow that does exactly what you need.

**Comment by jamaybyrone** [comment] 2025-01-02 10:23
@riqwan Cheers for the clarity on it

That demo is certainly quick! I'm starting to think it is something on the railway end, I can add you as a member to the project in railway if it saves you the time of setting up? I'm just testing things out as I'm migrating over from my current platform.

**Comment by riqwan** [comment] 2025-01-02 10:25
Yeah, that would def speed up the process - riqwan[at]medusajs[dot]com

**Comment by jamaybyrone** [comment] 2025-01-02 15:00
Apologise @riqwan I completely missed your message but I have got it down to under a second
<img width="423" alt="image" src="https://github.com/user-attachments/assets/c68e43a8-a5fa-4880-b9ce-6285525c91d0" />

I updated all the packages to the latest and reran the migrations, this has resolved everything.

**Comment by riqwan** [comment] 2025-01-02 16:09
Nice! Glad it worked out!

**Comment by Ronjea** [comment] 2025-01-30 19:07
@riqwan @jamaybyrone 

Going through the whole thread and I did not picked up the solution maybe I'm missing something or the solution was changing `NODE_OPTIONS=--max-old-space-size=4096` ??

**Comment by jamaybyrone** [comment] 2025-01-30 19:17
> [@riqwan](https://github.com/riqwan) [@jamaybyrone](https://github.com/jamaybyrone)
> 
> Going through the whole thread and I did not picked up the solution maybe I'm missing something or the solution was changing `NODE_OPTIONS=--max-old-space-size=4096` ??

Hey @Ronjea, no that was not the solution that solved my issue, it was "I updated all the packages to the latest and reran the migrations, this has resolved everything." which is my last comment on this thread.

So update: "@medusajs/medusa" to the latest, then run the [migrations](https://docs.medusajs.com/v1/development/entities/migrations/overview) after

**Comment by Ronjea** [comment] 2025-01-30 19:51
@jamaybyrone Thanks a lot! will make sure to make it happen 👍

**Comment by amanmishra003** [comment] 2025-06-25 17:57
We were facing persistent latency issues during the checkout flow:

6–11 seconds delay between each action (e.g., clicking “Next” after entering shipping address, selecting delivery method, or submitting the cart).

Backend was deployed on Railway, database and Redis were in the same region (US West - California).

All API requests from the storefront to the backend were extremely slow despite several optimization attempts.

**What we tried before the fix:**

1. Confirmed both Redis and PostgreSQL services were in the same Railway project and region.

2. Increased resource limits

3. Upgraded both backend and worker services to 8 GB, then to 32 GB RAM and 32 CPU cores on the Pro plan.

No visible performance improvement.

4. Storefront relocation

Moved the storefront from Vercel to Railway, which improved overall frontend responsiveness, but backend API latency remained high (especially during cart operations).  So I would say this helps 

5. Environment tuning

Added NODE_OPTIONS=--max-old-space-size=4096 to both backend and worker.

No meaningful performance difference in API response time.

While following the official Medusa documentation for deployment on Railway, we set up the DATABASE_URL and REDIS_URL using the public Railway connection strings provided under the “Connect” tab.

This config forces internal services (like Medusa backend and worker) to connect to Redis and Postgres over public internet, even though they’re in the same project.

**6. The actual solution that worked:**
Use internal service URLs instead of public ones when setting up Medusa backend and worker services on Railway.

In Railway, go to PostgreSQL service → Connect → Internal URL
Use that value for DATABASE_URL (e.g.):

DATABASE_URL=postgresql://postgres:<password>@postgres.internal:5432/dbname
In Redis, use the internal hostname + ?family=0:

REDIS_URL=redis://default:<password>@redis.internal:6379?family=0
Update these variables in both the Medusa backend and worker service on Railway.

After switching to internal service URLs:

All checkout-related requests dropped from 6–11 seconds to 50–200ms.

Checkout flow became instant and seamless.

Redis and Postgres now resolve through internal Railway DNS, eliminating public network latency.

![Image](https://github.com/user-attachments/assets/b16f5829-affb-4c42-b84a-1a89d5679152)  instead of this 

![Image](https://github.com/user-attachments/assets/3eac18ae-9722-45f3-a1c1-6262d1f3e181)

**Comment by unlux** [comment] 2025-07-22 17:31
i face this issue currently
backend on amazon Lightsail ap-south-1
postgress on neondb in singapore or supabase in ap-south-1 (no meaningfull difference)
redis (valkey) on Aiven ap-south-1 as well
and frontend is either on vercel or on localhost(again in ap-south-1)

yet adding to cart takes about 4-5 seconds
and so does just about interaction while ordering anything
