### ISSUE TITLE
Algolia Documentation

### ISSUE THREAD

**Issue by Brayo007** [medusajs/medusa#6009] opened 2024-01-06 15:58 UTC
### Describe the bug

Please the transformer description, terming it optional is confusing, since one might think the transformer is optional to add in the code. 

### Expected behavior

maybe saying that we should add attributestoRetrieve in the transformer will do it justice and easier to understand. Thanks

### Screenshots

![Screenshot from 2024-01-06 18-51-23](https://github.com/medusajs/medusa/assets/42490777/40588524-3bc9-41cd-b570-1f24e3fde4b5)

### Additional context

Add any other context about the problem here

**Comment by olivermrbl** [comment] 2024-01-07 13:28
I am not sure I understand. The `transformer` function is optional in the plugin configuration and is exposed to allow you to control whatever is indexed by the search engine. As described.

Since this is not a bug, I will be closing the issue.

**Closed as completed by olivermrbl** 2024-01-07 13:28 UTC
Labels: type: bug, status: needs triaging
