### ISSUE TITLE
Product import not possible anymore after update admin 7.1

### ISSUE THREAD

**Issue by raukaute** [medusajs/medusa#5160] opened 2023-09-20 11:45 UTC
## Bug report

Render error thrown by React when Import Product button is clicked.

### Describe the bug

When clicking the import products button on the product list page, an error is thrown. Modal won't open.
### System information

Medusa version (including plugins): 1.16 / Admin 7.1.0 
Node.js version: 16
Database: Postgres

### Steps to reproduce the behavior

1. Install above versions
2. Go to Product details page
3. Click on Import Products

### Expected behavior

Modal should show, not error is thrown
### Screenshots

<img width="1369" alt="image" src="https://github.com/medusajs/medusa/assets/57749196/f6ed06a9-629f-4ec0-a9d8-aa9384132e9a">

<img width="993" alt="image" src="https://github.com/medusajs/medusa/assets/57749196/847bf793-6519-4ed3-b4e5-8230b8bca3c5">

**Comment by fPolic** [comment] 2023-09-20 12:39
Duplicate of https://github.com/medusajs/medusa/issues/5102

**Comment by olivermrbl** [comment] 2023-09-20 16:42
@raukaute, you can give the `next` version a spin until we cut a new release, `yarn add @medusajs/admin@next` :)

**Closed as completed** 2023-09-20 16:42 UTC
Labels: type: bug, status: needs triaging
