### ISSUE TITLE
[CORE-1336] DB connection pool exhausted querying products

### ISSUE THREAD

**Issue by SGFGOV** [medusajs/medusa#3907] opened 2023-04-24 04:28 UTC
### Describe the bug

const catProduct = (
      await this.client.products.list({
        categories: [medusaCategory.id],
        limit: 1,
      })
    ).products;

results in an axios response:-
data: {
      type: 'invalid_data',
      message: 'property categories should not exist'
    }

results in an error 

However, when I query like so

    const catProduct = (
      await this.client.products.list({
        category_id: [medusaCategory.id],
        limit: 1,
      })
    ).products;

There is no response to the client, and server seems to be ignoring the request and the client hangs.. awaiting response from server (medusa)

The complete code snipet

async onModuleInit() {
    this.medusaService = (await this.moduleRef.get(MedusaService, {
      strict: false,
    })) as MedusaService;
    const medusaCategories = (
      await this.medusaService.client.productCategories.list({
        limit: 100,
      })
    ).product_categories;
    this.categories = await Promise.all(
      medusaCategories.map(
        async (t) => await this.medusaService.convert2FrontendCategory(t),
      ),
    );
  }

async convert2FrontendCategory(medusaCategory: MedusaCategory) {
    const catProduct = (
      await this.client.products.list({
        categories: [medusaCategory.id],
        limit: 1,
      })
    ).products;

    const images = catProduct ? catProduct?.[0]?.images : undefined;
    const image = images ? images[0] : undefined;
    const category: Category = {

### System information

Medusa version (including plugins): 1.8.2

### Expected behavior
It shouldn't hang

<sub>[CORE-1336](https://linear.app/medusajs/issue/CORE-1336/querying-product-by-category-id)</sub>

**Comment by SGFGOV** [comment] 2023-04-24 04:29
#3906 and this issue could be related

**Comment by olivermrbl** [comment] 2023-04-24 12:46
@SGFGOV – can I get you to ensure your products are published and the category is active + visible? :)

**Comment by SGFGOV** [comment] 2023-04-24 14:03
All products have been published and the category is active and visible

**Comment by SGFGOV** [comment] 2023-04-24 14:07
In fact curl has no problem receiving the info

**Comment by SGFGOV** [comment] 2023-04-25 02:03
the server responds like so 

::ffff:172.31.34.235 - - [25/Apr/2023:01:56:55 +0000] "GET /store/products?category_id%5B0%5D=pcat_01GYFXKX2EHPNN29C9143AV8GY&limit=1 HTTP/1.1" - - "-" "axios/1.2.1"
::ffff:172.31.34.235 - - [25/Apr/2023:01:56:55 +0000] "GET /store/products?category_id%5B0%5D=pcat_01GYPX5TVB5RSV83ETS6AP0JMK&limit=1 HTTP/1.1" - - "-" "axios/1.2.1"
::ffff:172.31.34.235 - - [25/Apr/2023:01:56:55 +0000] "GET /store/products?category_id%5B0%5D=pcat_01GYPX6B583RKE83NB2TF2KQDT&limit=1 HTTP/1.1" - - "-" "axios/1.2.1"
::ffff:172.31.34.235 - - [25/Apr/2023:01:56:55 +0000] "GET /store/products?category_id%5B0%5D=pcat_01GYPX61TN6KKCKZ9QC8HGTPA7&limit=1 HTTP/1.1" - - "-" "axios/1.2.1"
::ffff:172.31.34.235 - - [25/Apr/2023:01:56:55 +0000] "GET /store/products?category_id%5B0%5D=pcat_01GYGS967YQ97018WS7NQJH9T3&limit=1 HTTP/1.1" - - "-" "axios/1.2.1"
::ffff:172.31.34.235 - - [25/Apr/2023:01:56:55 +0000] "GET /store/products?category_id%5B0%5D=pcat_01GYGS7VQ2TYPXRRHFMCV2SZXX&limit=1 HTTP/1.1" - - "-" "axios/1.2.1"
::ffff:172.31.34.235 - - [25/Apr/2023:01:56:55 +0000] "GET /store/products?category_id%5B0%5D=pcat_01GYPX60FDFG7R14DQBXJW7S0M&limit=1 HTTP/1.1" - - "-" "axios/1.2.1"
::ffff:172.31.34.235 - - [25/Apr/2023:01:56:55 +0000] "GET /store/products?category_id%5B0%5D=pcat_01GYPX7HFPGKZNEAAAMYK6992E&limit=1 HTTP/1.1" - - "-" "axios/1.2.1"
::ffff:172.31.34.235 - - [25/Apr/2023:01:56:55 +0000] "GET /store/products?category_id%5B0%5D=pcat_01GYPX5YDSFKZAC5H6AB52R6Q5&limit=1 HTTP/1.1" - - "-" "axios/1.2.1"
::ffff:172.31.34.235 - - [25/Apr/2023:01:56:55 +0000] "GET /store/products?category_id%5B0%5D=pcat_01GYPX6GMD65RK8CQMABR1F76Y&limit=1 HTTP/1.1" - - "-" "axios/1.2.1"

**Comment by SGFGOV** [comment] 2023-04-25 03:04
It hangs inside typeorm/driver/postgres/PostgresQueryRunner.js line 69 using typeorm 0.3.14

**Comment by SGFGOV** [comment] 2023-04-25 04:47
Ok so i figured this out. the reason was the pool was exhausted. 
So changed the dataSourceSettings  in the database loader like so
                            poolSize: 100,
                            maxQueryExecutionTime:10e3,
                            poolErrorHandler: (err)=>{
                                console.log(err);                           
                            },
                            logNotifications:true,
                            connectTimeoutMS:60e3

Now I'm able to query 5 categories at a time.. I'm sure these are not optimal values. but I'm able to query 5 categories at a time without the server hanging

**Comment by olivermrbl** [comment] 2023-04-25 06:50
Thanks for sharing this @SGFGOV - helps a lot. We will investigate this issue asap and keep you posted. This take high priority for us.

**Comment by olivermrbl** [comment] 2023-04-25 06:53
Are you using the inventory and stock location modules?

**Comment by SGFGOV** [comment] 2023-04-25 07:00
Yes..I am using them..but have not added any data to those.. not dependent on inventory at the moment. Still fixing catalogue

**Comment by fxmb** [comment] 2023-04-26 14:21
I can confirm that this issue seems to be related to `product-categories` and also exists for me as soon as I issue product / product category heavy queries. Thanks for looking into this @SGFGOV !

**Comment by olivermrbl** [comment] 2023-04-26 14:23
@SGFGOV @fxmb – we've identified the culprit and are working on resolving it asap. I hope to be able to share something early next week.

**Comment by fxmb** [comment] 2023-04-26 14:24
Amazing thanks!

**Comment by SGFGOV** [comment] 2023-04-26 15:28
@olivermrbl fantastic..looking forward to the fix

**Comment by JesusDR01** [comment] 2023-04-30 14:15
Hello! 
I'm having this problem extending my product entity.

@olivermrbl 

/src/models.ts

```ts
import { Column, Entity } from "typeorm"
import {
  // alias the core entity to not cause a naming conflict
  Product as MedusaProduct,
} from "@medusajs/medusa"

@Entity()
export class Product extends MedusaProduct {
  @Column({ nullable: true })
  duration?: string
}
```


/src/repositories/product.ts

```ts
import { Product } from "../models/product"
import { 
  dataSource,
} from "@medusajs/medusa/dist/loaders/database"
import {
  // alias the core repository to not cause a naming conflict
  ProductRepository as MedusaProductRepository,
} from "@medusajs/medusa/dist/repositories/product"

export const ProductRepository = dataSource
  .getRepository(Product)
  .extend({
    // it is important to spread the existing repository here.
    // Otherwise you will end up losing core properties.
    // you also update the target to the extended entity
    ...Object.assign(
      MedusaProductRepository, 
      { target: Product }
    ),
      
    // you can add other customizations as well...
  })

export default ProductRepository
```

/src/migrations/1682863562389-ProductChanged.ts

```ts
import { MigrationInterface, QueryRunner } from "typeorm"

export class ProductChanged1682863562389 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "product" ADD "duration" character varying`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "product" DROP COLUMN "duration"`);
    }
}
```

/src/loaders/extend-product-fields.ts

```ts

export default async function () {
    const imports = (await import(
      "@medusajs/medusa/dist/api/routes/store/products/index"
    )) as any
    imports.allowedStoreProductsFields = [
      ...imports.allowedStoreProductsFields,
      "duration",
    ]
    imports.defaultStoreProductsFields = [
      ...imports.defaultStoreProductsFields,
      "duration",
    ]
  }
```

/src/index.d.ts

```ts
export declare module "@medusajs/medusa/dist/models/product" {
    declare interface Product {
      duration?: string;
    }
  }
```

I ran yarn build
And medusa migrations run

Version 1.9.0 (also happens in previous version)


REQUEST:

```shell
curl 'http://localhost:9000/admin/products/prod_01GZ87CGSV0FCAZQA9ZKWJNZDG' \
  -H 'Accept: application/json' \
  -H 'Accept-Language: es-ES,es;q=0.9,en;q=0.8,de;q=0.7' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Cookie: country_code=ca; region_id=reg_01GZ04ADEWMPDNP1EP8G9A983N; cart_id=cart_01GZ87DK86ND6RPX7F3D1T505X; ajs_user_id=usr_01GZ04AD4FRPR0DPQ24XH0TEA4; ajs_anonymous_id=32fe89b4-4441-4ffb-aa01-a405888ca6f4; connect.sid=s%3AH3iMGBkB0hzQ2i4Ls39j95w169eYnHnW.nNFwr0qyLk3WsSnkzaqkIWV99EjV%2BQU2Whe8%2BNzR%2FkE' \
  -H 'Origin: http://localhost:7001' \
  -H 'Referer: http://localhost:7001/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-site' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Chromium";v="112", "Google Chrome";v="112", "Not:A-Brand";v="99"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  --data-raw '{"title":"Competent crew","handle":"competent-crew","duration":"5","subtitle":"","description":null,"type":null,"collection_id":null,"tags":[],"categories":[],"discountable":true,"metadata":{}}' \
  --compressed
```

OUTPUT:

```
{"type":"invalid_data","message":"property duration should not exist"}
```

**Comment by olivermrbl** [comment] 2023-05-01 19:37
@fxmb @SGFGOV – we haven't forgotten this one. We are very close to having a patch ready. I expect, we can publish a snapshot tomorrow or Wednesday 👍

**Comment by SGFGOV** [comment] 2023-05-02 15:11
@olivermrbl Any luck here? Will this make it to the release ?

**Comment by olivermrbl** [comment] 2023-05-02 18:25
We've changed the `relationLoadStrategy` to `query` for products, which means we now perform separate queries for each requested relation. That is much less memory heavy and should generally increase performance.

You can try it here: `npm i @medusajs/medusa@1.9.1-next-20230502181644`.

Whether it solves your issue related to product categories, I am unfortunately not 100% sure. If not, we will keep digging.

**Comment by olivermrbl** [comment] 2023-08-11 08:15
@SGFGOV, my apologies. I never reverted to this issue. The problem should be resolved by now. Let me know if this is not the case :)

**Closed as completed by olivermrbl** 2023-08-11 08:15 UTC
Labels: type: bug, linear
