### ISSUE TITLE
How to avoid npx create-medusa-app@latest to seed demo data?

### ISSUE THREAD

**Issue by mauro-arcelles** [medusajs/medusa#10242] opened 2024-11-23 17:51 UTC
### What Medusa version and documentation are you using?

None

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

npx create-medusa-app@latest seeds demo data

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by olivermrbl** [comment] 2024-11-25 12:30
@mauro-arcelles, can I get you to share more about your use case?

**Comment by olivermrbl** [comment] 2024-12-06 13:18
This is not currently supported. Closing this as it is not a bug. Feel free to open a feature request as a GitHub Discussion.

**Closed as completed by olivermrbl** 2024-12-06 13:18 UTC
Labels: type: docs
