### ISSUE TITLE
Medusa S3 Plugin shows access denied when uploading image

### ISSUE THREAD

**Issue by sats268842** [medusajs/medusa#3904] opened 2023-04-22 21:30 UTC
## Bug report

I updated the medusa s3 plugin to version 1.1.12, and as a result, the plugin is not reflecting my AWS credential configuration. In options and aws_config_object, I attempted to add the AWS secret key and id. They didn't work for me.

### System information

Medusa version (including plugins): 1.8.2
"medusa-file-s3" :  "1.1.12"

Node.js version: v17
Database: Postgres 14
Operating system: Ubuntu
Browser (if relevant): -

### Steps to reproduce the behavior

1. Add Medusa S3 plugin
2. Configure the s3 plugin with cred in medusa-config.js
3. Then run medusa start command
4. Upload a image in product

### Expected behavior

It should upload a file to s3

### Screenshots

![image](https://user-images.githubusercontent.com/42093035/233807163-3cc76f0b-f3a2-4557-a90c-7e2ccbfd8a42.png)

### Additional context

I think the new plugin version, the AWS sdk were initialized before the cred are being injected into it. A screenshot of the code is included . When I set the environment variables AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY, the problem was resolved.

**Comment by pevey** [comment] 2023-04-22 21:36
https://github.com/medusajs/medusa/issues/3830

**Comment by olivermrbl** [comment] 2023-04-23 10:32
#3740 merged. Patch releasing early next week :)

Also, duplicate of #3830

**Closed as completed by olivermrbl** 2023-04-23 10:32 UTC
Labels: type: bug, status: needs triaging
