### ISSUE TITLE
Typescript error on index.d.ts in "Extending Medusa Example: Creating a Marketplace" guide

### ISSUE THREAD

**Issue by fvr1** [medusajs/medusa#4902] opened 2023-08-29 16:50 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

I just downloaded the Medusa app (storefront and backend) using medusa cli and I was following this tutorial
https://medusajs.com/blog/extending-medusa-usecase-marketplace/

It appeared an typescript error` ts(2668): 'export' modifier cannot be applied to ambient modules and module augmentations since they are always visible.` on the step of redeclaring the modules in the `index.d.ts` and in the store service, line 43 an error saying that the `Property 'store_id' does not exist on type 'User'.ts(2339)`.
 
<img width="856" alt="image" src="https://github.com/medusajs/medusa/assets/13739465/8969b466-08a3-4b9a-9390-6c789bd84d39">

<img width="859" alt="image" src="https://github.com/medusajs/medusa/assets/13739465/8e8947c6-ff51-45c0-afbe-b1ba03662039">

Other info:
- I'm running the code with node v18.10.0
- My package json has  typescript: ^4.5.2 and  medusajs its 1.15.0
- My tsconfig file is the next one (the one that is created by default with the `medusa new` command)

```js
{
  "compilerOptions": {
    "target": "es2019",
    "allowJs": true,
    "esModuleInterop": true,
    "module": "commonjs",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "skipLibCheck": true,
    "skipDefaultLibCheck": true,
    "declaration": true,
    "sourceMap": false,
    "outDir": "./dist",
    "rootDir": "./src",
    "baseUrl": ".",
    "jsx": "react-jsx",
    "forceConsistentCasingInFileNames": true,
    "resolveJsonModule": true,
    "checkJs": false
  },
  "include": ["src/"],
  "exclude": [
    "**/__tests__",
    "**/__fixtures__",
    "node_modules",
    "build",
    ".cache"
  ]
}
```

### How can this issue be resolved?

Solved it by renaming `src/index.d.ts` to `src/custom-types.d.ts` (using the exact same code) and adding `include: ["src/", "src/custom-types.d.ts"]` in the `tsconfig.js` file.

I don't know if that's a correct way to do it, but at least I do not have the errors anymore and typescript seems to be working correctly. Is ok this solution or I'm missing something to make the `index.d.ts` work?

Thanks! 🌟 

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment] 2023-08-30 07:42
Hi @fvr1 , just want to point out that blog posts are not always kept up to date, so you should refer to documentation as much as possible instead. Regarding the marketplace, we have a [marketplace recipe](https://docs.medusajs.com/recipes/marketplace) similar to the blog post that we put more effort into updating if necessary. So, feel free to open issues regarding that one when you face issues while following it.

Regarding your issues with types, I'm not sure what could be the cause of it. If `custom-types.d.ts` works for you then you can use it 😄

will close this issue for now, if you face any other issues feel free to reopen the issue or open a new one.

**Closed as completed by shahednasser** 2023-08-30 07:42 UTC
Labels: type: docs

**Comment by arthurcornelio88** [comment] 2024-07-21 14:13
Hello !

I'm very new here, but Gemini suggested me the following code wit this explanation :

`declare module "@medusajs/medusa/dist/models/product" {
  interface Product {
    customAttribute: string;
  }
}`

Understanding the Errors:

TS2668: 'export' modifier cannot be applied to ambient modules and module augmentations... This error means you're trying to use the export keyword within a module declaration (declare module). Module augmentations are meant to extend existing modules, not create new exportable ones.
TS1038: A 'declare' modifier cannot be used in an already ambient context... This error means you're using the declare keyword within a block that's already been marked as ambient. The declare module construct itself establishes an ambient context.

Explanation of Changes:

Removed export: We've removed the unnecessary export keyword from the declare module block. Since module augmentations are always visible, they don't need to be explicitly exported.
Removed declare from Interface: We've removed the declare keyword from inside the Product interface definition. Within the declare module block, the interface is already understood to be a declaration.
How it Works:

This corrected code does the following:

Module Augmentation: It uses declare module to target the existing "@medusajs/medusa/dist/models/product" module.
Interface Extension: It extends the existing Product interface within that module by adding a new property called customAttribute.

Key Points:

Ambient Context: The declare module block creates an ambient context where TypeScript understands that you're not defining a new module, but rather extending an existing one.
Interface Declaration: Inside an ambient context, the declare keyword is redundant when defining interfaces. TypeScript automatically infers that you're declaring the interface rather than implementing it.

Additional Tips:

Declaration File Location: Make sure this index.d.ts file is placed in a directory that is included in the include section of your tsconfig.json. This will ensure that the TypeScript compiler picks it up and applies the augmentation to the Product entity.

===

At least, no more errors here too !
