### ISSUE TITLE
Storefront BUILD FAILS lint checks with "Type error" `medusa-starter-default`

### ISSUE THREAD

**Issue by gamesguru** [medusajs/medusa#4079] opened 2023-05-11 23:43 UTC
### Describe the bug

When building the `storefront` with `npm run build` or `next build` I get the following error,

```text
$ cd storefront

$ npm run build

> medusa-next@1.0.3 build
> next build

next.config.js {
  "reactStrictMode": true,
  "images": {
    "domains": [
      "medusa-public-images.s3.eu-west-1.amazonaws.com",
      "localhost"
    ]
  },
  "env": {}
}
info  - Linting and checking validity of types ...Failed to compile.

./src/lib/data/index.ts:20:3
Type error: Type 'PricedProduct[] | never[]' is not assignable to type 'Product[]'.
  Type 'PricedProduct[]' is not assignable to type 'Product[]'.
    Property 'beforeInsert' is missing in type 'PricedProduct' but required in type 'Product'.

  18 |     .catch((_) => [])
  19 | 
> 20 |   return products
     |   ^
  21 | }
  22 | 
  23 | // get global data used in header and footer
```

### System information

Medusa version (including plugins): 1.3.7
Node.js version: 18
Database:
Operating system: Ubuntu 22.04
Browser (if relevant):

### Steps to reproduce the behavior

1. Create a new app according to https://docs.medusajs.com/create-medusa-app (with default options)
2. Try to build the `storefront`
3. Observe the lint failures

**Comment by chemicalkosek** [comment] 2023-05-12 06:31
https://github.com/medusajs/medusa/issues/4060

**Comment by olivermrbl** [comment] 2023-05-16 15:49
Duplicate of #4060

**Closed as completed by olivermrbl** 2023-05-16 15:49 UTC
Labels: type: bug, status: needs triaging
