### ISSUE TITLE
Not able to run on node js 16.17.1 version

### ISSUE THREAD

**Issue by yasir129** [medusajs/medusa#2262] opened 2022-09-28 06:10 UTC
### System information

Medusa version (including plugins):
Node.js version: 16.17.1
Database: sqlite
Operating system: windows
Browser (if relevant): 

### Problem I am facing
I have cloned the admin panel from giithub and already configured the server on my localhost by using sqlite database but right now, i have already installed all libraries in admin panel but getting error to execute and then terminate. 
the error is: the specified module not found in the system.

**Comment by srindom** [comment] 2022-09-28 08:08
Hi - can I ask you to outline the steps you took and paste the error you are getting in your terminal?

**Comment by edrossy** [comment] 2022-09-30 19:15
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-server-dom-webpack@0.0.0-experimental-c8b778b7f-20220825
npm WARN Found: react@16.14.0
npm WARN node_modules/react
npm WARN   react@"^16.12.0" from the root project
npm WARN   111 more (@hookform/error-message, react-dom, react-hook-form, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"0.0.0-experimental-c8b778b7f-20220825" from react-server-dom-webpack@0.0.0-experimental-c8b778b7f-20220825
npm WARN node_modules/gatsby/node_modules/react-server-dom-webpack
npm WARN   react-server-dom-webpack@"0.0.0-experimental-c8b778b7f-20220825" from gatsby@4.24.1
npm WARN   node_modules/gatsby
npm WARN
npm WARN Conflicting peer dependency: react@0.0.0-experimental-c8b778b7f-20220825
npm WARN node_modules/react
npm WARN   peer react@"0.0.0-experimental-c8b778b7f-20220825" from react-server-dom-webpack@0.0.0-experimental-c8b778b7f-20220825
npm WARN   node_modules/gatsby/node_modules/react-server-dom-webpack
npm WARN     react-server-dom-webpack@"0.0.0-experimental-c8b778b7f-20220825" from gatsby@4.24.1
npm WARN     node_modules/gatsby

**Comment by daniloff200** [comment] 2022-10-03 10:41
I can confirm, that, I had the same for node 16.17.0

**Comment by adrien2p** [comment] 2023-12-06 09:39
I apologize for the delayed response. Could you confirm that the issue is still present?

Thanks ❤️

**Comment by sradevski** [comment] 2024-07-05 09:11
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏

**Closed by sradevski** 2024-07-05 09:11 UTC
Labels: status: needs reproduction, type: bug
