### ISSUE TITLE
[admin] React error when clicking "Import Products" in products list view

### ISSUE THREAD

**Issue by genox** [medusajs/medusa#5102] opened 2023-09-17 15:17 UTC
### Describe the bug

I am running the latest version of medusa and the admin UI locally and on a server in production mode.

I get the following error message on both systems when clicking the "Import Products" button:

```
Uncaught runtime errors:
×
ERROR
Objects are not valid as a React child (found: object with keys {fileTitle}). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (webpack-internal:///91344:14887:9)
    at createChild (webpack-internal:///91344:15139:7)
    at reconcileChildrenArray (webpack-internal:///91344:15404:25)
    at reconcileChildFibers (webpack-internal:///91344:15821:16)
    at reconcileChildren (webpack-internal:///91344:19162:28)
    at updateHostComponent (webpack-internal:///91344:19919:3)
    at beginWork (webpack-internal:///91344:21613:14)
    at HTMLUnknownElement.callCallback (webpack-internal:///91344:4164:14)
    at Object.invokeGuardedCallbackDev (webpack-internal:///91344:4213:16)
    at invokeGuardedCallback (webpack-internal:///91344:4277:31)
ERROR
Objects are not valid as a React child (found: object with keys {fileTitle}). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (webpack-internal:///91344:14887:9)
    at createChild (webpack-internal:///91344:15139:7)
    at reconcileChildrenArray (webpack-internal:///91344:15404:25)
    at reconcileChildFibers (webpack-internal:///91344:15821:16)
    at reconcileChildren (webpack-internal:///91344:19162:28)
    at updateHostComponent (webpack-internal:///91344:19919:3)
    at beginWork (webpack-internal:///91344:21613:14)
    at HTMLUnknownElement.callCallback (webpack-internal:///91344:4164:14)
    at Object.invokeGuardedCallbackDev (webpack-internal:///91344:4213:16)
    at invokeGuardedCallback (webpack-internal:///91344:4277:31)
```

On prod, the error message is truncated and simplified a la React.

I tried switching between minio and local file upload locally, but the error stayed the same.

I made sure all migrations ran.

### System information

```
    "@medusajs/admin": "^7.1.0",
    "@medusajs/cache-inmemory": "^1.8.8",
    "@medusajs/cache-redis": "^1.8.8",
    "@medusajs/event-bus-local": "^1.9.6",
    "@medusajs/event-bus-redis": "^1.8.9",
    "@medusajs/file-local": "^1.0.2",
    "@medusajs/icons": "^1.0.0",
    "@medusajs/medusa": "^1.16.0",
    "@medusajs/ui": "^1.0.0",
    "@tanstack/react-query": "4.22.0",
    "babel-preset-medusa-package": "^1.1.20",
    "body-parser": "^1.20.2",
    "cors": "^2.8.5",
    "dotenv": "16.0.3",
    "express": "^4.18.2",
    "medusa-file-minio": "^1.3.0",
    "medusa-fulfillment-manual": "^1.1.38",
    "medusa-interfaces": "^1.3.7",
    "medusa-payment-manual": "^1.0.24",
    "medusa-payment-stripe": "^6.0.4",
    "medusa-plugin-smtp": "^1.2.0",
    "medusa-plugin-variant-images": "^1.0.0",
    "prism-react-renderer": "^2.0.4",
    "typeorm": "^0.3.17"
```

Node.js version: 18
Database: latest Postgres docker image
Operating system: MacOS and Debian 12
Browser (if relevant):

### Steps to reproduce the behavior

1. Go to product list view
2. Click on Import Products

### Expected behavior

I expect to see the import dialogue.

**Comment by olivermrbl** [comment] 2023-09-17 19:13
@genox – thanks for highlighting. I am indeed able to reproduce your issue. @fPolic would you be able to have a look at this asap?

**Comment by fPolic** [comment] 2023-09-17 19:38
@olivermrbl looks like a small typo introduced with the translations PR - fixed in the linked PR

**Closed as completed by fPolic** 2023-09-17 19:38 UTC
Labels: type: bug

**Comment by genox** [comment] 2023-09-18 08:06
@fPolic @olivermrbl thank you

**Comment by genox** [comment] 2023-09-18 11:45
@olivermrbl Sorry to bother you - I seem not to be able to roll back to a previous release even though I manually set the version in package.json and build based on a lock file. Are you planning to release a patch today?
