### ISSUE TITLE
File upload error when trying to create a new product by medusa-admin

### ISSUE THREAD

**Issue by robertomlj** [medusajs/medusa#2676] opened 2022-11-27 22:31 UTC
I've installed and configured the medusa-file-s3 plugin for file uploads, and whenever I try to create a new product, I get the following browser error:
<sub>Error
Something went wrong while trying to upload images. You might not have a file service configured. Please contact your administrator</sub>

in the browser console I get the error:
<sub>POST http://localhost:9000/admin/uploads 500 (Internal Server Error) xhr.js:244 </sub>

in the medusa-server console I get the error:
<sub>error:   Cannot read properties of undefined (reading 'map')
TypeError: Cannot read properties of undefined (reading 'map')
    at /home/monteiro/Projetos/shoprocket/backend/node_modules/@medusajs/medusa/dist/api/routes/admin/uploads/create-upload.js:118:60
    at step (/home/monteiro/Projetos/shoprocket/backend/node_modules/@medusajs/medusa/dist/api/routes/admin/uploads/create-upload.js:33:23)
    at Object.next (/home/monteiro/Projetos/shoprocket/backend/node_modules/@medusajs/medusa/dist/api/routes/admin/uploads/create-upload.js:14:53)
    at /home/monteiro/Projetos/shoprocket/backend/node_modules/@medusajs/medusa/dist/api/routes/admin/uploads/create-upload.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/monteiro/Projetos/shoprocket/backend/node_modules/@medusajs/medusa/dist/api/routes/admin/uploads/create-upload.js:4:12)
    at /home/monteiro/Projetos/shoprocket/backend/node_modules/@medusajs/medusa/dist/api/routes/admin/uploads/create-upload.js:112:49
    at exports.default (/home/monteiro/Projetos/shoprocket/backend/node_modules/@medusajs/medusa/dist/api/middlewares/await-middleware.js:12:16)
    at Layer.handle [as handle_request] (/home/monteiro/Projetos/shoprocket/backend/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/monteiro/Projetos/shoprocket/backend/node_modules/express/lib/router/route.js:144:13)</sub>

My package.json file:

<sub>{
  "name": "medusa-starter-default",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Sebastian Rindom <skrindom@gmail.com>",
  "license": "MIT",
  "scripts": {
    "seed": "medusa seed -f ./data/seed.json",
    "build": "babel src -d dist --extensions \".ts,.js\"",
    "start": "medusa develop"
  },
  "dependencies": {
    "@medusajs/medusa": "^1.6.0",
    "@medusajs/medusa-cli": "^1.3.3",
    "medusa-file-s3": "^1.1.7",
    "medusa-fulfillment-manual": "^1.1.31",
    "medusa-interfaces": "^1.3.3",
    "medusa-payment-manual": "^1.0.16",
    "medusa-payment-stripe": "^1.1.48",
    "medusa-plugin-meilisearch": "^1.0.0",
    "typeorm": "^0.2.36"
  },
  "repository": "https://github.com/medusajs/medusa-starter-default.git",
  "keywords": [
    "sqlite",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "devDependencies": {
    "@babel/cli": "^7.18.10",
    "@babel/core": "^7.18.10",
    "@babel/preset-typescript": "^7.14.5",
    "babel-preset-medusa-package": "^1.1.19"
  }
}</sub>

I tried to use MiniIO, but I get the same errors mentioned above.

**Comment by InderdeepBajwa** [comment] 2022-11-28 01:35
Duplicate of https://github.com/medusajs/admin/issues/815

**Closed** 2022-11-28 10:14 UTC
Labels: type: bug

**Comment by bjwilk** [comment] 2024-10-15 00:38
I am getting same error.  Were you able to solve this?

**Comment by LuciaBeron3456** [comment] 2024-12-03 11:42
I'm getting this error
