### ISSUE TITLE
STORE_CORS = "/http:\/\/*/"; Not working

### ISSUE THREAD

**Issue by microCloudCode** [medusajs/medusa#4470] opened 2023-07-06 05:44 UTC
![image](https://github.com/medusajs/medusa/assets/46712199/eb360bba-e5fc-4a98-9d55-8b4bd2ae3f19)
![image](https://github.com/medusajs/medusa/assets/46712199/42af66dc-981c-4b48-b2ca-da95d75f3b6c)

**Comment by adrien2p** [comment] 2023-07-07 08:24
When a regexp is a string, you have to take care of escaping. I suggest you to do the following in a template string instead of a string ``/http:\\/\\/*/``

**Comment by microCloudCode** [comment] 2023-07-07 08:27
Are you saying it should be like this?
![image](https://github.com/medusajs/medusa/assets/46712199/84ade7ee-2545-4cc0-a993-bc64026d2a75)

**Comment by adrien2p** [comment] 2023-07-07 10:26
almost :) you are missing the escape `\\` instead of `\`

**Comment by olivermrbl** [comment] 2023-07-09 11:05
Closing this for now. @microCloudCode, shout if you still experience issues after applying @adrien2p's fix.

**Closed as completed by olivermrbl** 2023-07-09 11:05 UTC
Labels: type: bug, status: needs triaging

**Comment by microCloudCode** [comment] 2023-07-10 03:04
![image](https://github.com/medusajs/medusa/assets/46712199/a188605d-2434-48ce-a4fc-830001bf1a6e)
@adrien2p  I modified it like this, but get the following error
![image](https://github.com/medusajs/medusa/assets/46712199/7dac45a6-a5d4-4aa3-83f2-b0871d4d3b39)

**Comment by adrien2p** [comment] 2023-07-10 05:17
Can you log STORE_CORS to see what it contains

**Comment by microCloudCode** [comment] 2023-07-10 05:45
![image](https://github.com/medusajs/medusa/assets/46712199/70b887d1-6ebb-4635-bd9e-265803cff3fa)

**Comment by adrien2p** [comment] 2023-07-10 07:50
Can you share your packages and plugins info please

**Comment by microCloudCode** [comment] 2023-07-10 07:52
![image](https://github.com/medusajs/medusa/assets/46712199/c6ea7ad6-f085-4cc6-84be-d100995a95e6)
![image](https://github.com/medusajs/medusa/assets/46712199/95ea1af7-698d-4aba-8a41-21674dfbe6e9)
I am using the official medusa-starter-default

**Comment by adrien2p** [comment] 2023-07-10 08:02
that seems weird, I use the exact same config myself :), can I get you to put a breakpoint in `node_modules/cors/lib/index line 30 and share what you get please

**Comment by microCloudCode** [comment] 2023-07-10 08:05
![image](https://github.com/medusajs/medusa/assets/46712199/56acf781-7549-4c00-8b90-542277c0065c)

**Comment by microCloudCode** [comment] 2023-07-10 08:08
![image](https://github.com/medusajs/medusa/assets/46712199/1af19d43-fd53-4028-9bfe-2c081089efd5)
I found that only this request happens cors

**Comment by adrien2p** [comment] 2023-07-10 08:11
This breakdpoint you shared is the one that corresponds to that request?

**Comment by microCloudCode** [comment] 2023-07-10 08:15
![image](https://github.com/medusajs/medusa/assets/46712199/460f50aa-2641-40e6-a2a4-a05d7ec0815b)
No, this request entered this breakpoint

**Comment by adrien2p** [comment] 2023-07-10 08:19
humm weird

**Comment by adrien2p** [comment] 2023-07-10 08:21
Can you get from the stack where it is the orgin of that call to the cors to see where this value is coming from please

**Comment by microCloudCode** [comment] 2023-07-11 01:57
![image](https://github.com/medusajs/medusa/assets/46712199/1aaac787-8037-420e-9335-4c2af618d65e)

**Comment by microCloudCode** [comment] 2023-07-12 02:30
@adrien2p Can you help me? I don't understand why CORS is so complicated in Medusa compared to my experience with other frameworks.

**Comment by adrien2p** [comment] 2023-07-12 05:30
I am sorry to hear your difficulties, In the meantime since you want to allow everything you can replace the regexp by just *. 

I am unable to reproduce, and the cors in medusa does not work differently than any express app. it looks like at some point your regexp is considered as a string. Using the * will solve your issue, but if you can it would be nice to put a breakpoint in this file during the bootsrap https://github.com/medusajs/medusa/blob/develop/packages/medusa-core-utils/src/build-regexp-if-valid.ts 

Also, do you have any customisation i should be aware of?

**Comment by microCloudCode** [comment] 2023-07-12 05:43
![image](https://github.com/medusajs/medusa/assets/46712199/a0f287c4-b62e-4aa9-8184-151d860b4a23)

Are you saying that I can write it like this? But he still gets an error! 
![image](https://github.com/medusajs/medusa/assets/46712199/ade2cd46-cddb-4a9c-8750-794c6a5fd465)
![image](https://github.com/medusajs/medusa/assets/46712199/894fc120-07ec-4866-9e6a-6a790f3b4a37)

**Comment by adrien2p** [comment] 2023-07-12 05:48
No just a string "*", can you try that please

**Comment by microCloudCode** [comment] 2023-07-12 05:49
![image](https://github.com/medusajs/medusa/assets/46712199/fc64df8d-7365-46ba-902c-5db5f0aa9cd8)
Writing it like this doesn't work either, it only works when I explicitly specify the domain.


![image](https://github.com/medusajs/medusa/assets/46712199/68373419-52df-4800-8505-eca830222d00)

**Comment by adrien2p** [comment] 2023-07-12 05:53
Also, if even a regexp that let pass everything like you did does not work, there is a real issue somewhere, do you have any customization?

**Comment by adrien2p** [comment] 2023-07-12 06:44
Can you share you repo please

**Comment by adrien2p** [comment] 2023-07-12 06:46
I will retry with my setup and 1.12, but just in case you have something different somewhere

**Comment by adrien2p** [comment] 2023-07-12 07:12
Here is what I did and I don't get any error. I am waiting for a reproducible repository

<img width="3008" alt="Screenshot 2023-07-12 at 09 10 36" src="https://github.com/medusajs/medusa/assets/25098370/adb87c52-da90-4284-a6c1-8e091f9080d5">
<img width="852" alt="Screenshot 2023-07-12 at 09 11 01" src="https://github.com/medusajs/medusa/assets/25098370/e352af05-dc1b-4d10-bba1-e142870c5851">
<img width="1008" alt="Screenshot 2023-07-12 at 09 12 24" src="https://github.com/medusajs/medusa/assets/25098370/8c069eff-746c-4e6f-941e-db1c4ede7e78">

**Comment by microCloudCode** [comment] 2023-07-12 17:44
I apologize for keeping you waiting. This is the repository I created.
https://github.com/microCloudCode/my-medusa-store

**Comment by microCloudCode** [comment] 2023-07-14 05:49
@adrien2p hi

**Comment by microCloudCode** [comment] 2023-07-16 09:17
@adrien2p Hello, may I ask if you can reproduce this issue on your end?

**Comment by adrien2p** [comment] 2023-07-16 09:27
@microCloudCode hey sorry but i am out for the long weekend here in france, i ll come back to you beginning of the week 👍

**Comment by adrien2p** [comment] 2023-07-17 07:29
@microCloudCode I ve been able to test your repo, I ve set the regexp I ve sent you first `const STORE_CORS = "/http:\\/\\/*/";` and it works

**Comment by adrien2p** [comment] 2023-07-17 07:30
<img width="2377" alt="Screenshot 2023-07-17 at 09 30 01" src="https://github.com/medusajs/medusa/assets/25098370/b2f9e83c-73da-49e3-9ea4-f52e98c21f32">
