### ISSUE TITLE
Can't add product to cart

### ISSUE THREAD

**Issue by nparoski** [medusajs/medusa#5124] opened 2023-09-18 19:31 UTC
### Describe the bug
Clicking add to cart doesn't do anything, checking dev console I can see error 500
### System information

Medusa version (including plugins):
```
"@medusajs/admin": "^7.0.1",
"@medusajs/cache-inmemory": "^1.8.8",
"@medusajs/cache-redis": "^1.8.8",
"@medusajs/event-bus-local": "^1.9.6",
"@medusajs/event-bus-redis": "^1.8.9",
"@medusajs/file-local": "^1.0.2",
"@medusajs/icons": "^1.0.0",
"@medusajs/medusa": "^1.15.0",
"@medusajs/ui": "^1.0.0",
"@medusajs/medusa-cli": "^1.3.16"
```
Node.js version: 18.17.1
Database: Postgre 15.4
Operating system: Windows
Browser (if relevant): Chrome

### Steps to reproduce the behavior
1. Go to store
2. Click on any product (only medusa t-shirt worked)
3. Click add to cart

**Request**
```
Request URL:
http://localhost:9000/store/carts/cart_01HAMHP51F21P6XCJ7KM0K5N7Z/line-items
Request Method:
POST
Status Code:
500 Internal Server Error
Remote Address:
[::1]:9000
Referrer Policy:
strict-origin-when-cross-origin
```
**Payload**
```
{code: "unknown_error", type: "unknown_error", message: "An unknown error occurred."}
```
### Additional context
**Dockerfile**
```
FROM node:18.17.1

COPY . /app
WORKDIR /app
RUN npm cache clean --force
RUN npm install

CMD ["npm","run","dev"]
```
**docker-compose.yml**
```
version: "3.8"

services:
  backend:
    container_name: api_backend
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - "7001:7001"
      - "7000:7000"
      - "9000:9000"
    depends_on:
      - database

  database:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: medusa_db
```

**Comment by olivermrbl** [comment] 2023-09-18 19:58
You'll need to share more information about your setup for us to debug your issue. 

- Is this a completely new project?
- How have you configured your products?
- Do you use the multi-warehouse modules?

You should also be able to see a more descriptive error message in the server log. Could I get you to check that? I believe it could contain useful information for debugging your issue.

**Comment by nparoski** [comment] 2023-09-18 20:05
@olivermrbl It's new project setup from current version of docs with nextjs storefront. Projects are seeded with default seed file. I don't use multi warehouse module.

**Comment by olivermrbl** [comment] 2023-09-18 20:07
> @olivermrbl It's new project setup from current version of docs with nextjs storefront. Projects are seeded with default seed file. I don't use multi warehouse module.

Thanks - this is helpful. I'll investigate your issue first thing tomorrow morning and get back to you.

**Comment by nparoski** [comment] 2023-09-18 20:13
@olivermrbl some more useful information

```
api_backend             | ::ffff:172.23.0.1 - - [18/Sep/2023:20:10:59 +0000] "OPTIONS /store/carts/cart_01HAMYNP2MEAYVCWX51FERHN4Z/line-items HTTP/1.1" 
204 0 "http://localhost:8000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"        
api_backend             | error:   Cannot read properties of undefined (reading 'title')
api_backend             | TypeError: Cannot read properties of undefined (reading 'title')
api_backend             |     at LineItemService.<anonymous> (/app/node_modules/@medusajs/medusa/dist/services/line-item.js:384:185)
api_backend             |     at step (/app/node_modules/@medusajs/medusa/dist/services/line-item.js:59:23)
api_backend             |     at Object.next (/app/node_modules/@medusajs/medusa/dist/services/line-item.js:40:53)
api_backend             |     at /app/node_modules/@medusajs/medusa/dist/services/line-item.js:34:71
api_backend             |     at new Promise (<anonymous>)
api_backend             |     at __awaiter (/app/node_modules/@medusajs/medusa/dist/services/line-item.js:30:12)
api_backend             |     at LineItemService.generateLineItem (/app/node_modules/@medusajs/medusa/dist/services/line-item.js:371:16)
api_backend             |     at LineItemService.<anonymous> (/app/node_modules/@medusajs/medusa/dist/services/line-item.js:329:67)
api_backend             |     at step (/app/node_modules/@medusajs/medusa/dist/services/line-item.js:59:23)
api_backend             |     at Object.next (/app/node_modules/@medusajs/medusa/dist/services/line-item.js:40:53
```

**Comment by olivermrbl** [comment] 2023-09-19 07:21
After investigating this issue, it seems this could be related to your malformed product variants (highlighted in your other issue), as the error is thrown on a missing variant title, as part of generating the line item.

I am also unable to reproduce the error following the steps you provided.

I will close this issue for now. Please use Discord for any further help requests.

**Closed as completed by olivermrbl** 2023-09-19 07:21 UTC
Labels: type: bug

**Comment by Mortennn** [comment] 2023-09-20 20:07
I got the same error because I tried to add an item with a `variant_id` that didn't exist. Therefore, if there are any hardcoded `variant_id`'s somewhere, that could be the problem.

But that's just to leave it here in case it helps anyone. I havn't investigated it further.
