### ISSUE TITLE
Omnibus directive compliance

### ISSUE THREAD

**Issue by xzymxeqgmc** [medusajs/medusa#8913] opened 2024-08-30 13:49 UTC
Hello,

Medusa 2.0 boasts about it's new promotion module which is really nice but unfortunately also illegal to use in the European Union.
There are hefty fines for this and thus I think this should be included "in the box" alongside with medusa promo module.

You can read more on the official site: https://commission.europa.eu/law/law-topic/consumer-protection-law/unfair-commercial-practices-law/price-indication-directive_en

Either way being compliant with this law comes down to presenting lowest price of a product within 30 days before the introduction of a discount. Here are the specifics: https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:52021XC1229(06)

Also I think it forces merchants to present price per unit but Im no lawyer so you'd have to dig deeper into that.

**Comment by xzymxeqgmc** [comment] 2024-10-01 11:57
any follow up on this?

**Comment by thetutlage** [comment] 2024-11-08 12:22
Hello @xzymxeqgmc

If I understand correctly, the issue is more related to how a Merchant displays the information within the Storefront. If that's true, I think it will be up to the merchant to comply with the law.

Our starter should be considered a starting point, and we expect you to modify it to your needs and self-manage regional regulations.

I will close this for now as there isn't much to be done right now.

**Closed as completed by thetutlage** 2024-11-08 12:22 UTC

**Comment by maacaron** [comment] 2024-11-14 22:30
Hi @thetutlage 
Currently I'm trying to add this on my store. I think it's not only storefront problem. In EU we need to present the lowest price in past 30 days before discount. So for example:
1. Original price is 215 EUR
2. On day 5 I changed price to 199 EUR
3. On day 10 I changed price to 205 EUR
So we have original price 215 EUR and discounted price 205 EUR. But in the past 30 days there was 199 EUR for the product. And according to the law we need to present this price somewhere on the product page (look at amazon screenshot). The only thing is to store the price in DB (in variant object `calculated_price` maybe?).

<img width="482" alt="Screenshot 2024-11-14 at 23 26 16" src="https://github.com/user-attachments/assets/1ba9ea0a-7940-41d9-ba05-e244ef241850">

**Comment by xzymxeqgmc** [comment] 2024-11-14 22:41
> Hi @thetutlage Currently I'm trying to add this on my store. I think it's not only storefront problem. In EU we need to present the lowest price in past 30 days before discount. So for example:
> 
> 1. Original price is 215 EUR
> 2. On day 5 I changed price to 199 EUR
> 3. On day 10 I changed price to 205 EUR
>    So we have original price 215 EUR and discounted price 205 EUR. But in the past 30 days there was 199 EUR for the product. And according to the law we need to present this price somewhere on the product page (look at amazon screenshot). The only thing is to store the price in DB (in variant object `calculated_price` maybe?).
> 
> <img alt="Screenshot 2024-11-14 at 23 26 16" width="482" src="https://private-user-images.githubusercontent.com/5049531/386388606-1ba9ea0a-7940-41d9-ba05-e244ef241850.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2MjQyMjgsIm5iZiI6MTczMTYyMzkyOCwicGF0aCI6Ii81MDQ5NTMxLzM4NjM4ODYwNi0xYmE5ZWEwYS03OTQwLTQxZDktYmEwNS1lMjQ0ZWYyNDE4NTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTRUMjIzODQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDQ5M2I1NjM2ODE5ZDcyOGM1M2Q2OTI2NDE3Y2IzYzk0MWQyNDViMGM2ZjU1YjcyMzJmNjEwMWM1NWEzZDJkZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.V8GjA5pk9MWAmlxK7ezlOHM8jlhcooNrbIFlPD5CDN4">

He literally just said he wants to close this down because apparently medusa isn't trying to fulfil "local" (as in european) regulations... In my opinion it's just stupid because promo module is unusable (illegal) out of the box, if you tried to use it in most of the developed countries, that is
