### ISSUE TITLE
Barbel Error after installing medusa & running the project

### ISSUE THREAD

**Issue by rightalign-io** [medusajs/medusa#5958] opened 2023-12-22 10:39 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Issue: after following the docs, installing medusa-cli & running the command npx create-next-app@latest, all the files are created in the backend and the store-front folder. when I run the project using ```medusa develop``` i get the error

```
'"D:\Repository\Write Align\SALON-API\fast-internet\admin\salon-storefront\node_modules\.bin\babel"' is not recognized as an internal or external command,
operable program or batch file.
Error: Command failed: "D:\Repository\Write Align\SALON-API\fast-internet\admin\salon-storefront\node_modules\.bin\babel" src -d dist --ignore "src/admin/**"
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at D:\Repository\Write Align\SALON-API\fast-internet\admin\salon-storefront\node_modules\@medusajs\medusa\dist\commands\develop.js:120:42
    at step (D:\Repository\Write Align\SALON-API\fast-internet\admin\salon-storefront\node_modules\@medusajs\medusa\dist\commands\develop.js:44:23)
    at Object.next (D:\Repository\Write Align\SALON-API\fast-internet\admin\salon-storefront\node_modules\@medusajs\medusa\dist\commands\develop.js:25:53)
    at D:\Repository\Write Align\SALON-API\fast-internet\admin\salon-storefront\node_modules\@medusajs\medusa\dist\commands\develop.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (D:\Repository\Write Align\SALON-API\fast-internet\admin\salon-storefront\node_modules\@medusajs\medusa\dist\commands\develop.js:15:12)
    at default_1 (D:\Repository\Write Align\SALON-API\fast-internet\admin\salon-storefront\node_modules\@medusajs\medusa\dist\commands\develop.js:93:12) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 19176,
  stdout: null,
  stderr: null
}
```

I have tried couple of times to create the project anew but consistently this error comes up.

My Tools:
Windows 10
NVM: node 10.2 & node 16.4

### How can this issue be resolved?

1. I tried installing node v10 because thats the one the project usese but it still did not work
2. I made sure to delete node_package files & run 'yarn & yarn start', that did not work.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by olivermrbl** [comment] 2023-12-22 11:57
Possibly a duplicate of https://github.com/medusajs/medusa/issues/5905. Can I get you to give the snapshots posted on the other issue a spin?

**Closed as completed** 2023-12-27 12:56 UTC
Labels: type: docs
