### ISSUE TITLE
Search when creating swaps does not work

### ISSUE THREAD

**Issue by magdafiktus** [medusajs/medusa#3194] opened 2023-02-07 13:28 UTC
**Describe the bug**

When creating swap, we cannot see what we are typing, when we search for the new item

System information
"@medusajs/medusa": "1.7.2-snapshot-20221228134959",
"@medusajs/medusa-cli": "^1.3.5",
"medusa-core-utils": "^1.1.36",
"medusa-file-spaces": "1.3.1",
"medusa-fulfillment-manual": "1.1.31",
"medusa-fulfillment-webshipper": "^1.3.3",
"medusa-interfaces": "1.3.3",
"medusa-payment-adyen": "1.1.39",
"medusa-payment-klarna": "1.3.4",
"medusa-payment-manual": "^1.0.19",
"medusa-payment-paypal": "1.2.6",
"medusa-payment-stripe": "1.1.49",
"medusa-plugin-brightpearl": "1.3.2",
"medusa-plugin-contentful": "^1.2.3",
"medusa-plugin-discount-generator": "1.1.19",
"medusa-plugin-ip-lookup": "1.2.1",
"medusa-plugin-meilisearch": "1.0.0",
"medusa-plugin-restock-notification": "2.0.0",
"medusa-plugin-segment": "^1.3.0",
"medusa-plugin-sendgrid": "1.3.3",
"medusa-plugin-sentry": "^1.2.3",
"medusa-plugin-slack-notification": "1.3.4",
"medusa-plugin-wishlist": "1.1.37",
"medusa-test-utils": "1.1.37",
Node -> v16.x
OS -> Ubuntu 18.04
Database -> Postgres<!--

**Steps to reproduce the behavior**
1. Buy something
2. try to swap it

**Expected behavior**

We would see what is typed 

![Skærmbillede 2022-11-24 kl  15 32 24](https://user-images.githubusercontent.com/116171296/217259171-b083e490-c5a7-4b9a-a376-58f3deb9090c.png)

**Comment by olivermrbl** [comment] 2023-02-13 07:57
I can't seem to reproduce your issue. Can I get you to try once more and verify that the issue persists?

Closing for now.

**Closed by olivermrbl** 2023-02-13 07:57 UTC
Labels: type: bug, status: needs triaging

**Comment by josetr** [comment] 2023-02-13 11:25
I can't reproduce it either, but I did find a similar issue at https://demo.medusajs.com/a/settings/team some time ago. I've created a PR with the fix.

@olivermrbl can we add more data to the demo site? it's mostly empty which makes it harder to try to quickly reproduce issues.
