### ISSUE TITLE
Documentation section pages crash after a while when viewed

### ISSUE THREAD

**Issue by egolegegit** [medusajs/medusa#5309] opened 2023-10-07 16:34 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Documentation section pages crash after a while when viewed

This page crashed.
Failed to execute 'insertBefore' on 'Node': 

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment] 2023-10-09 09:02
Thank you for reporting this issue @egolegegit . Can you let me know which page did this error occur one? Can help us debug it better and narrow down possible reasons

**Comment by shahednasser** [comment] 2023-10-12 07:51
Closing this issue as I can't reproduce it. If you have more information please don't hesitate to reopen the issue with more information.

**Closed as completed by shahednasser** 2023-10-12 07:51 UTC
Labels: type: docs

**Comment by Snorlax-Chan** [comment] 2024-06-10 07:31
It seems that the issue can be reproduced with webpage translation, such as Google Chrome's automatic translation. Any webpage that has been translated may potentially reproduce this issue. @shahednasser

**Comment by shahednasser** [comment] 2024-06-10 07:50
Thanks for reporting this @Snorlax-Chan , will look into it

**Comment by Snorlax-Chan** [comment] 2024-06-10 22:18
> Thanks for reporting this @Snorlax-Chan , will look into it

Thank you for your response. The same issue also appears on the dashboards created by Medusa and on Storefront pages. You just need to use Google Chrome or Microsoft Edge, and enable their built-in automatic webpage translation. After browsing for a while or clicking a few times (the frequency of occurrence is uncertain, sometimes it happens quickly, other times it might take ten minutes or more), the same webpage error appears: ‘Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.’

**Comment by Snorlax-Chan** [comment] 2024-06-11 03:09
> > 感谢您报告此事@Snorlax-Chan，会调查一下
> 
> 感谢您的答复。同样的问题也出现在 Medusa 创建的仪表板和店面页面上。您只需要使用 Google Chrome 或 Microsoft Edge，并启用它们内置的自动网页翻译即可。浏览一段时间或点击几次后（发生的频率不确定，有时发生得很快，有时可能需要十分钟或更长时间），出现相同的网页错误：'Failed to execute 'insertBefore' on 'Node '：要在其之前插入新节点的节点不是该节点的子节点。'

@shahednasser
