### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by finom** [medusajs/medusa#3045] opened 2023-01-16 19:36 UTC
### Describe the bug

After upgrading @medusajs/medusa-js from 1.3.5 to 1.3.6 I've got the following error

![image](https://user-images.githubusercontent.com/1082083/212753763-ddf32226-ebd1-4dc6-a8b4-49e882b83ce6.png)

The cause is nothing but the import 
<img width="383" alt="image" src="https://user-images.githubusercontent.com/1082083/212753953-2d059047-96ce-4930-bec0-da22c9b5d4df.png">

### System information

Medusa version (including plugins): 1.3.5
Node.js version: v18.3.0
Database: not relevant
Operating system: not relevant
Browser (if relevant): not relevant

### Steps to reproduce the behavior

1. Install latest version of @medusajs/medusa-js
2. Import it on NodeJS

### Expected behavior

No error

### Additional context

Downgrading back to 1.3.5 fixes the issue.

**Comment by kasperkristensen** [comment] 2023-01-17 10:08
Hi @finom, this has been fixed and will be released tomorrow, see https://github.com/medusajs/medusa/issues/3020. Closing this as it is a duplicate of the already open issue 😄

**Closed by kasperkristensen** 2023-01-17 10:08 UTC
Labels: type: bug
