### ISSUE TITLE
Getting Semicolon instead of the comma in .csv file as we export it.

### ISSUE THREAD

**Issue by AbhinavChavareTechcopain** [medusajs/medusa#6461] opened 2024-02-21 07:40 UTC
I am exporting the products getting the file in.csv but semicolon separated not comma-separated, so that I am unable to get the details of the products, as all the content is under the single column.
please guide me for the same

**Comment by sradevski** [comment] 2024-02-21 16:06
@AbhinavChavareTechcopain can you please upload a sample of your file? You can easily convert the separator from semicolon to comma in any tool if that's the only problem?

**Comment by xyzones** [comment] 2024-02-28 09:37
What OS are you using?

**Comment by xyzones** [comment] 2024-02-28 09:55
This is not a bug for sure, only US, AUS, UK uses comma as delimiter in other countries, a comma is reserved for the decimal symbol, and the list separator is generally set to semicolon.

This is a training question, please remove bug label and close this.

**Comment by sradevski** [comment] 2024-02-28 09:57
Closing due to lack of activity and it's likely not a bug as @xyzones pointed out.

**Closed as completed by sradevski** 2024-02-28 09:57 UTC

**Comment by AbhinavChavareTechcopain** [comment] 2024-02-28 11:16
OS is 64-bit and currently I am using medusa from
Maharashtra India
Please provide solution for it.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by AbhinavChavareTechcopain** [comment] 2024-03-05 06:29
[https://res.cdn.office.net/assets/mail/file-icon/png/csv_16x16.png]product-export-1709278974726.csv<https://techcopain-my.sharepoint.com/:x:/p/abhinav_chavare/EZ_h8U-0LulAjyYJeZ4S89QB_qPSVANjEzbmqZ_2pseX-w>

Sorry for the delay,
please look over the excel file uploaded in which we are getting semicolons separated data becuase of which all the data are in one column.

Awaiting for your reply,



Best Regards,

Abhinav Chavare

________________________________

**Comment by xyzones** [comment] 2024-03-05 13:22
@AbhinavChavareTechcopain please learn how to convert it in excel. Literally 2 clicks.

**Comment by AbhinavChavareTechcopain** [comment] 2024-03-06 09:52
Thanks for the reply,
I have changed it in Excel, but we have give it to the client (user) they may not know how to do this as it is a marketplace,
so can do something that in Excel it will open properly in separate columns.

Thanks for your time and consideration.


Best Regards,



[https://mail.google.com/mail/u/3?ui=2&ik=42d973e3fe&attid=0.0.1&permmsgid=msg-f:1755153117195092381&th=185b8e75fcd5419d&view=fimg&fur=ip&sz=s0-l75-ft&attbid=ANGjdJ-i99GJzxmPh2JgyqOMRhGdE5cst5gGrc8z-iwsaYKEhwMwWVPGxEoaU4Pm5ko7NQCI-QGqtgZGZlw29MW64PZzndAMHIajjiclF6wFF8vFwJa55lvzctOHoSg&disp=emb]

Abhinav Balkrishna Chavare

TechCopain IT Solutions Pvt. Ltd.

m: (+91) 9921899345

e: ***@***.***<https://www.techcopain.com/>

w: https://www.techcopain.com<https://www.techcopain.com/>

[Yellow Icon LinkedIn | Gaming logos, App icon, Nintendo wii logo]<https://www.linkedin.com/company/techcopainsolutions>  [https://mail.google.com/mail/u/3?ui=2&ik=42d973e3fe&attid=0.0.3&permmsgid=msg-f:1755153117195092381&th=185b8e75fcd5419d&view=fimg&fur=ip&sz=s0-l75-ft&attbid=ANGjdJ_sWkC-nfGXKavcSC7ZTq81yhpomiBTwF6-TSF6G4J9k6Xg-Cr552r4sUk7AWmuGuWD0OiKtyJXusmArdkbzTcSn6QTSGgKeqo0_J5JneOALBSlio3ud3Xl76s&disp=emb] <https://www.facebook.com/TechCopainsolutions/>

________________________________

**Comment by AbhinavChavareTechcopain** [comment] 2024-03-12 04:02
Awaiting for your reply.

**Comment by AbhinavChavareTechcopain** [comment] 2024-03-22 04:19
please reply for the same .
