### ISSUE TITLE
Docs(Code Issue): Code Issue in /starters/nextjs-medusa-starter

### ISSUE THREAD

**Issue by MutisoMuli** [medusajs/medusa#6931] opened 2024-04-04 04:10 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

![image](https://github.com/medusajs/medusa/assets/136011037/74606bfc-1987-46b3-9a7c-9bdcf9d4beae)

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment] 2024-04-04 06:41
Closing this as a duplicate of #6930

**Closed as completed by shahednasser** 2024-04-04 06:41 UTC
Labels: type: docs
