### ISSUE TITLE
Trying to link model throws '...is not linkable on service...' error

### ISSUE THREAD

**Issue by intrinsic-blockchain** [medusajs/medusa#8147] opened 2024-07-16 12:48 UTC
Reference: https://docs.medusajs.com/v2/resources/recipes/marketplace/examples/vendors

## Bug report
I run into the following error: 
Error: Key vendor_id is not linkable on service marketplaceModuleService
    at register (C:\Users\hanee\Documents\medusajs\medusa-preview\node_modules\@medusajs\utils\src\modules-sdk\define-link.ts:153:13)
    at MedusaApp_ (C:\Users\hanee\Documents\medusajs\medusa-preview\node_modules\@medusajs\modules-sdk\src\medusa-app.ts:385:30)
    at async MedusaAppMigrateGenerate (C:\Users\hanee\Documents\medusajs\medusa-preview\node_modules\@medusajs\modules-sdk\src\medusa-app.ts:594:34)
    at async runMedusaAppMigrations (C:\Users\hanee\Documents\medusajs\medusa-preview\node_modules\@medusajs\medusa\src\loaders\medusa-app.ts:127:5)
    at async main (C:\Users\hanee\Documents\medusajs\medusa-preview\node_modules\@medusajs\medusa\src\commands\migrate.ts:100:5)

### Describe the bug
After defining models and then creating links between models, when `npx medusa migrations generate` is run, I see the following error _**Error: Key vendor_id is not linkable on service marketplaceModuleService**_

### System information

Medusa version (including plugins): "preview" version
Node.js version: 20.5.1
Database: postgreSQL 16
Operating system: Windows 11

### Steps to reproduce the behavior

1. Follow steps 1 & 2 to create a module, models and links from the recipe https://docs.medusajs.com/v2/resources/recipes/marketplace/examples/vendors
2. On step 3 when `npx medusa migrations generate marketplaceModuleService` is run, you see the error _**Error: Key vendor_id is not linkable on service marketplaceModuleService**_

### Expected behavior
I expect the migration to generate and when migration is run, it should run without errors.

### Screenshots
![image](https://github.com/user-attachments/assets/a7134ba1-308d-4c08-8603-fad0a92b89d8)
![image](https://github.com/user-attachments/assets/6dec16b5-e036-44d9-b3a0-c8ca9587aba7)
![image](https://github.com/user-attachments/assets/4304eea6-2ee8-469f-8557-fc5faa94e4e2)
![image](https://github.com/user-attachments/assets/0dc9f901-9e63-4d5a-8702-1f6c23621d0e)
![image](https://github.com/user-attachments/assets/faebfc11-b678-480d-8a8d-04471a76eb2e)

**Comment by adrien2p** [comment] 2024-07-16 14:44
hey @intrinsic-blockchain could you share you packages preview versions please

**Comment by intrinsic-blockchain** [comment] 2024-07-16 16:04
@adrien2p thanks for checking. Here is what I have:
@medusajs/medusa@1.20.6-preview-20240716090543
@medusajs/medusa-cli@1.3.23-preview-20240716090543

**Comment by shahednasser** [comment] 2024-07-17 07:15
Hi @intrinsic-blockchain , can you try removing the `node_modules` and `yarn.lock` files and trying again? This could be due to an outdated preview version.

**Comment by intrinsic-blockchain** [comment] 2024-07-17 09:07
@shahednasser deleting the node_modules & yarn.lock did not help. The migrations run successfully only if I comment out the files src/links/vendor-admin.ts & src/links/vendor-order.ts
![image](https://github.com/user-attachments/assets/b15bd5f5-35b1-4b5b-8166-52e83fb14dbc)
![image](https://github.com/user-attachments/assets/b8890922-d1ae-47eb-bbb3-69f48f7cfb08)
![image](https://github.com/user-attachments/assets/e41a7eb2-cb6d-4edb-ae41-63d1ddd3f173)

**Comment by shahednasser** [comment] 2024-07-17 09:20
Is the issue with running or generating the migration? So if you run `npx medusa migrations run` do the links also cause an error?

**Comment by intrinsic-blockchain** [comment] 2024-07-17 10:22
Issue is with generating the migration with the command `npx medusa migrations generate marketplaceModuleService`. I think its unable to create the link between vendor & product models. Same with vendor-order models. It throws the _**Error: Key vendor_id is not linkable on service marketplaceModuleService**_ error. 

If its helpful this is what I have in vendor-product.ts in src/links folder, 
![image](https://github.com/user-attachments/assets/4d1dfedc-1794-43c6-b2ed-6016f6a8f8eb)


hovering over _MarketplaceModule.linkable.vendor_ shows this.
![image](https://github.com/user-attachments/assets/ab9aa7ac-b7d3-41df-a638-4f33f80dadf1)

(property) vendor: {
    id: {
        serviceName: "marketplaceModuleService";
        field: "vendor";
        linkable: "vendor_id";
        primaryKey: "id";
    };
    toJSON: () => {
        serviceName: "marketplaceModuleService";
        field: "vendor";
        linkable: "vendor_id";
        primaryKey: "id";
    };
}

**Comment by shahednasser** [comment] 2024-07-17 10:31
Ok but if you run `npx medusa migrations run` (with the link files) you see no errors right?

**Comment by intrinsic-blockchain** [comment] 2024-07-17 10:53
I see this error WITH the links files

![image](https://github.com/user-attachments/assets/aca76ed9-7175-4a6b-97b4-376a0116bdf2)

**Comment by adrien2p** [comment] 2024-07-17 11:18
@intrinsic-blockchain would you be able to provide us a minimal repository that reproduces this issue?

**Comment by shahednasser** [comment] 2024-07-17 11:19
Thanks for reporting this @intrinsic-blockchain but we still can't reproduce it on our side. Do you mind creating a repository with the changes you have so far and sharing it so that we can try to reproduce it?

**Comment by intrinsic-blockchain** [comment] 2024-07-17 11:41
@adrien2p here it is: https://github.com/intrinsic-blockchain/medusa-preview

**Comment by shahednasser** [comment] 2024-07-17 12:58
@intrinsic-blockchain can you try to download this file and use it as `yarn.lock` in your project, re-install the dependencies, and try again?

https://res.cloudinary.com/dza7lstvk/raw/upload/v1721221052/OpenApi/yarn_ivml2e.lock

**Comment by intrinsic-blockchain** [comment] 2024-07-17 13:29
Unfortunately, using this yarn.lock file too didn't help. I still get the same error. I tried testing using yarn command as well as npm to install node modules, both the times see the same issue.

**Comment by imash96** [comment] 2024-07-19 05:51
![image](https://github.com/user-attachments/assets/9f80c533-5245-4558-b1f5-c22a0469eb94)
 Getting same error while generating migrations

**Comment by adrien2p** [comment] 2024-07-19 08:04
I think I know what is the issues, I am preparing a pr so that you can test as well https://github.com/medusajs/medusa/pull/8194

**Comment by adrien2p** [comment] 2024-07-19 08:28
Would you be able to test the snapshot generate [here](https://github.com/medusajs/medusa/pull/8194) please

**Comment by imash96** [comment] 2024-07-19 09:42
Yes issue is resolve thanks you very much @adrien2p

**Comment by adrien2p** [comment] 2024-07-19 09:57
wonderful, cc @shahednasser

**Comment by adrien2p** [comment] 2024-07-22 07:39
I ll close this issue as it is resolved for windows users as well 👍

**Closed as completed by adrien2p** 2024-07-22 07:39 UTC
Labels: status: needs triaging, version: 2.0

**Comment by intrinsic-blockchain** [comment] 2024-07-22 11:19
@adrien2p thanks for all the support. I can confirm that doing an `npm update` and taking the latest build works just fine as expected. Thanks again for all the help!

**Comment by alisafavi** [comment] 2024-09-22 12:53
Hey all, how can have a page to register new vender before login
