### ISSUE TITLE
Inability to create and use commands to create admin in a deployed railway backend

### ISSUE THREAD

**Issue by Developing100works** [medusajs/medusa#4449] opened 2023-07-01 16:59 UTC
There is a constant error that happens when trying to create and use commands to create admin in a deployed railway backend. When using the command "Railway run npx @medusajs/medusa-cli user -e some@email.com -p some-password" there are many errors that come up.

![image](https://github.com/medusajs/medusa/assets/138317743/22d850ef-0cc8-470b-bad8-f965fae63589)

### System information

Medusa version (including plugins): Medusa CLI version: 1.3.12 
Node.js version: 16.7.1
Database: postgres sq (railway) 
Operating system: windows 10
Browser (if relevant):

### Expected behavior

A clear and concise description of what you expected to happen

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by kleenkanteen** [comment] 2023-07-01 19:30
I got the same error message in his picture a month ago while running the same command. I used the railway CLI, logged in, and selected my project with the postgres + redis + medusa backend running. Running "Railway run npx @medusajs/medusa-cli user -e some@email.com -p some-password" gave the same error message about the "id" argument needing to be a string. I don't remember how I resolved it, I was eventually able to make a admin user and log in to the admin dashboard.

The error message for search engines: TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received undefined

**Comment by MrQQish** [comment] 2023-08-31 03:30
I am getting the same issue, was there any inroads to finding a solution?

**Comment by kleenkanteen** [comment] 2023-08-31 04:25
@MrQQish @Developing100works found a workaround which he told me over discord. I recommend joining the medusa discord as getting help there is faster. He wrote the the command for creating an admin user in the build command under the build section in railway. Pic related:

![image](https://github.com/medusajs/medusa/assets/67878058/89e9f740-ba21-4ba2-b4bf-35b1e97880db)

Quote: "I have been able to find a solution and I have a succesful solution that uses the railay ui. By typing in the settings section of the deployed backend in the build command "npx @medusajs/medusa-cli user -e some@email.com -p some-password". You can create a new user that will be added to your postgres database and you will be able to login".

**Comment by MrQQish** [comment] 2023-09-01 00:04
Hi thanks for the speedy reply. That seems to have worked but I have also joined the discord since I expect that I will be needing help again. Thanks for the assist

**Comment by nonfungibletunji** [comment] 2023-09-13 17:31
can you link to the discord discussion?

**Comment by kleenkanteen** [comment] 2023-09-13 18:09
You have to join the discord server and search for it, can't link it

**Comment by netpoe** [comment] 2023-10-06 02:03
I had the same issue by using `medusa  user`. As a workaround, since I was setting up a new project, I deleted the directories and started over with: 

```
 npx create-medusa-app@latest --db-url [YOUR_POSTGRES_DB_URI]
```

**Comment by netpoe** [comment] 2023-10-06 02:20
> I had the same issue by using `medusa user`. As a workaround, since I was setting up a new project, I deleted the directories and started over with:
> 
> ```
>  npx create-medusa-app@latest --db-url [YOUR_POSTGRES_DB_URI]
> ```

Nevermind. The install went through, but not admin user was created (even following the prompts) and the `medusa user` command is still not working...

I'm at: 

```
Medusa CLI version: 1.3.21
node -v v18.18.0
ubuntu
```

**Comment by luluhoc** [comment] 2023-11-03 15:53
for me medusa user is creating normal user not admin...

**Comment by felixH3r** [comment] 2023-11-19 14:47
@luluhoc you can just go to your postgres in the UI there you can find your user and change it from "member" to "admin"

**Comment by klunejko** [comment] 2023-12-18 15:40
Don't think this is necessarily related to railway. Ran into the same issue when trying to set up my dev environment locally (W10), when I wasn't in the same directory as the backend. The CLI was installed globally (following the docs), but that only includes the new command. Every other command is only included on the local install (I'm guessing after creating a new project). 

I would probably update the documentation to make this clear and maybe also provide an error message that points to the missing command file, rather than just outputting the error thrown from yargs.

**Comment by Kainkainkain** [comment] 2023-12-20 02:29
I installed postgres locally, connected it locally, then ran the npx medusa command locally which is where it does work. Got my admin login, tested. 
Then I manually copied the database entry directly from my local to my railway app data row editor. Worked.

**Comment by ghost** [comment] 2024-01-25 12:52
@Kainkainkain  Very smart solution, it worked for me. 
But for some reason I an unable to run medusa commands using` npx medusa`, in the railway cli. Which makes the whole deployment useless since, we need access to the backend through cli somehow.

**Comment by RyelBanfield** [comment] 2024-02-02 22:48
Make sure when you run the command 

```
railway run npx @medusajs/medusa-cli user -e email@gmail.com -p password   
```

that you are running it from the same directory of the project that has been deployed to railway.

**Comment by JonathanBezdek** [comment] 2024-02-21 13:52
When you're facing similar issues, here's a workaround that I found effective: manually inserting an entry into the database. 

**Here's a step-by-step guide:**
1. Navigate to your PostgreSQL interface.
2. Locate the "Data" section and then find the table "User".
3. Add a new row with the following example data:

User ID: `usr_01HQ3B1EXGFJT71YYXBFMN92P4`
Email: `admin@medusa-test.com`
Password (hashed): `c2NyeXB0AAEAAAABAAAAAXlxnqHM+OtooAxUC45JGAc/GT5vlceQjtD1knRKHOP+LrGNqHnmW4y7a0jPQG74EZ5L8pazeadZaYmg038KJ+jtEjDdz1PvJTHI7iDGPv73`
Created At: `2024-02-20 14:24:46.993678+01`
Updated At: `2024-02-20 14:24:46.993678+01`
Role: `member`

Please adjust the values according to your specific requirements. This solution worked for me, and I hope it helps you too!

**Comment by poiuyt183** [comment] 2024-05-29 08:30
I had the same issue. But I run '''npm install''' and then recreate user by '''run medusa user''' ....
And it done!

**Comment by sradevski** [comment] 2024-07-05 09:56
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏

**Closed as completed by sradevski** 2024-07-05 09:56 UTC
Labels: type: bug, status: needs triaging

**Comment by johnmweisz** [comment] 2024-11-10 22:51
I'm having this issue with v2...

TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received undefined

**Comment by kacime** [comment] 2024-11-26 16:27
I have no idea what the problem is, but I solved this in v2 doing
`npx ./node_modules/@medusajs/cli/  user -e admin@medusajs.com -p supersecret`

**Comment by alleny0o** [comment] 2025-01-28 22:36
@kacime thank you for the update. however where exactly did you place this command?

**Comment by MichaelAsiass** [comment] 2025-02-14 01:34
One workaround is if you have your backend deployed on your machine 

run  "npx medusa user -e some@email.com -p some-password"

and take the url for your database from railway and add it as the databaseURL in your local env

this should work

**Comment by itsbrianburton** [comment] 2025-09-22 07:20
Since this is the #1 result for this error, this can be caused by mixing package managers.  If you've been using yarn but install a package with npm it can cause this behavior.  Deleting your node_modules directory and running `yarn install` was the solution for me.
