### ISSUE TITLE
Unable to Set Inventory Quantity to 0 for Variants

### ISSUE THREAD

**Issue by ivanskodje** [medusajs/medusa#4426] opened 2023-06-27 22:25 UTC
### Describe the bug

When I edit Variants inventory quantity to 0, no changes occurs. 

The cause of this is when we are setting a number besides 0, we are setting inventory_quantity. When we send 0, it does NOT send inventory_quantity.

When setting 1 inventory:
```json
{
  "title": "My stuff, med skum, svart",
  "sku": "1535-BLK-WF",
  "inventory_quantity": 1,
  "manage_inventory": true,
  "metadata": {},
  "prices": [
    {
      "amount": 369900,
      "currency_code": "nok",
      "region_id": null,
      "id": "ma_01H3ZE0VGBFR0AVS5X2GNEPWS7"
    }
  ],
  "options": [
    {
      "option_id": "opt_01H3ZDV1EE2E8XA0T87RX9EGZF",
      "value": "Svart"
    },
    {
      "option_id": "opt_01H3ZDV1EKN7200BSC8NRXG5QT",
      "value": "Med Skum"
    }
  ],
  "allow_backorder": false
}
 ``` 

When setting 0 inventory:
```json
{
  "title": "My stuff, med skum, svart",
  "sku": "1535-BLK-WF",
  "manage_inventory": true,
  "metadata": {},
  "prices": [
    {
      "amount": 369900,
      "currency_code": "nok",
      "region_id": null,
      "id": "ma_01H3ZE0VGBFR0AVS5X2GNEPWS7"
    }
  ],
  "options": [
    {
      "option_id": "opt_01H3ZDV1EE2E8XA0T87RX9EGZF",
      "value": "Svart"
    },
    {
      "option_id": "opt_01H3ZDV1EKN7200BSC8NRXG5QT",
      "value": "Med Skum"
    }
  ],
  "allow_backorder": false
}
```

If I Create a CURL from the inspector and manually set 0, it works just fine, so there seem to be an issue with parsing of 0 into ... nothing.

**Note** that I have managed to set it to 0 before, and that this bug seem to be caused by other circumstances that I have not yet identified. I will be doing further testing, but until now I am reporting there _is_ an issue.

### System information

Medusa version (including plugins):
```
  "dependencies": {
    "@medusajs/admin": "^6.0.0",
    "@medusajs/cache-inmemory": "^1.8.7",
    "@medusajs/cache-redis": "^1.8.7",
    "@medusajs/event-bus-local": "^1.9.4",
    "@medusajs/event-bus-redis": "^1.8.7",
    "@medusajs/file-local": "^1.0.1",
    "@medusajs/medusa": "^1.12.0",
    "body-parser": "^1.19.0",
    "cors": "^2.8.5",
    "express": "^4.17.2",
    "medusa-fulfillment-manual": "^1.1.37",
    "medusa-interfaces": "^1.3.7",
    "medusa-payment-manual": "^1.0.23",
    "medusa-payment-stripe": "^6.0.0",
    "typeorm": "^0.3.16"
  },
```

``` 
const plugins = [
  `medusa-fulfillment-manual`,
  `medusa-payment-manual`,
  {
    resolve: `@medusajs/file-local`,
    options: {
      upload_dir: "uploads",
      backend_url: FILE_UPLOADS_BACKEND_URL,
    },
  },
  {
    resolve: "@medusajs/admin",
    /** @type {import('@medusajs/admin').PluginOptions} */
    options: {
      serve: true,
      autoRebuild: true,
    },
  },
  {
    resolve: `medusa-payment-stripe`,
    options: {
      api_key: process.env.STRIPE_API_KEY,
      webhook_secret: process.env.STRIPE_WEBHOOK_SECRET,
    },
  },
];

module.exports = {
  projectConfig,
  plugins,
  modules,
  featureFlags: {
    tax_inclusive_pricing: true,
  },
};

```

Node.js version: v18.16.0
Database: Postgres
Operating system: Ubuntu
Browser (if relevant): Chromium

### Steps to reproduce the behavior

1. Create variant with inventory quantity, and save it.
2. Edit variant and set inventory quantity to 0, and save it.
3. Nothing happens with the inventory quantity.

### Expected behavior

0 inventory size.

### Additional context

Discord:  https://discord.com/channels/876835651130097704/1123373226869936168

**Comment by quang-ng** [comment] 2023-06-29 08:32
I am starting contribute to Medusa project. Could I take this issue.

**Comment by raidsrc** [comment] 2023-09-08 23:21
I am experiencing this issue as well in Medusa version 1.15.

**Comment by farouk-hubelia** [comment] 2023-09-19 20:12
I am experiencing this issue as well, the issue is due to the removeFalsy function, it considers 0 values as falsy. since this function is called on the payload object before making the api call to update the variant inventory, it removes the "inventory_quantity" in the payload object.

**Comment by ntonjsgo** [comment] 2023-11-14 10:55
any update on this?

**Comment by ivanskodje** [comment] 2023-11-27 16:24
This could potentially be a good beginner task for anyone willing to help out 😅  (I havent had the time myself to even look at this yet)

**Comment by ntonjsgo** [comment] 2023-11-27 16:26
@ivanskodje seems fixed so far with newer versions

**Comment by sradevski** [comment] 2024-07-05 09:49
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏

**Closed as completed by sradevski** 2024-07-05 09:49 UTC
Labels: type: bug, status: needs triaging
