### ISSUE TITLE
Medusa v2 Docs: Issue in 3.12 : Widgets - Medusa v2 Docs

### ISSUE THREAD

**Issue by Saadchr** [medusajs/medusa#8005] opened 2024-07-07 22:16 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

I reproduced the tutorial .
I can't see any widget at the top of the page

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment] 2024-07-08 08:34
Hi @Saadchr thanks for reporting this! Can you please give us more details of the steps you took (other than the documentation you followed)? Was your server running while you created it? Did you try restarting the server? Can you share any screenshots?

**Comment by Petr-Hl** [comment] 2024-07-10 05:17
In my case I can't create no widget or route UI on Windows 11 for this issue:
```
[plugin:vite:import-analysis] Failed to resolve import "H:medusasrcadmin
outescustompage.tsx" from "virtual:medusa/routes/pages". Does the file exist?
virtual:medusa/routes/pages:1:24
1  |  import RouteExt0 from "H:\medusa\src\admin\routes\custom\page.tsx";
   |                         ^
2  |  export default {
3  |        pages: [{ path: "H:\medusa\src\admin\routes\custom\page.tsx", Component: RouteExt0 }],
```

Can't create any modules too for compiling file .ts like directory not like file in dist folder.
I use Node v22.4.0 and VSC 1.91

**Comment by shahednasser** [comment] 2024-07-10 08:32
Thanks for reporting this! Looping @kasperkristensen to give more assistance on this

**Comment by kasperkristensen** [comment] 2024-07-11 07:41
Hi @Saadchr, can I get you to try with the latest preview release? You might have to delete your `yarn.lock` and `node_modules` and re-install dependencies.

**Comment by grgmgd** [comment] 2024-07-20 19:23
@kasperkristensen I am also facing this issue with widgets. Installed the latest preview version as of date and still facing the issue.

**Comment by SalahAdDin** [comment] 2024-09-22 04:25
@grgmgd @Saadchr can you provide a more elaborated description, please?

**Comment by renequez** [comment] 2024-10-15 12:34
Same problem here. I think it has to do with how paths are interpreted on Windows.

I'm on a fresh install of rc 4, only thing I've done was to add the widget from the docs and i'm getting the same error as @Petr-Hl:

```
[plugin:vite:import-analysis] Failed to resolve import "C:codingmedusasrcadminwidgetsproduct-widget.tsx" 
from "virtual:medusa/widgets". Does the file exist?
virtual:medusa/widgets:1:60
1  |  import WidgetComponent0, { config as WidgetConfig0 } from "C:\coding\medusa\src\admin\widgets\product-widget.tsx"
   |                                                             ^
2  |  
3  |  export default {
```

**Comment by LauschaNN** [comment] 2024-11-12 15:09
> Same problem here. I think it has to do with how paths are interpreted on Windows.
> 
> I'm on a fresh install of rc 4, only thing I've done was to add the widget from the docs and i'm getting the same error as @Petr-Hl:
> 
> ```
> [plugin:vite:import-analysis] Failed to resolve import "C:codingmedusasrcadminwidgetsproduct-widget.tsx" 
> from "virtual:medusa/widgets". Does the file exist?
> virtual:medusa/widgets:1:60
> 1  |  import WidgetComponent0, { config as WidgetConfig0 } from "C:\coding\medusa\src\admin\widgets\product-widget.tsx"
>    |                                                             ^
> 2  |  
> 3  |  export default {
> ```

I can confirm that this error is still happening in v2.0.4.

I am trying to copy / paste the code shown in this official docs tutorial https://docs.medusajs.com/learn/basics/admin-customizations but it is not working.

**Comment by kasperkristensen** [comment] 2024-11-12 15:26
> > Same problem here. I think it has to do with how paths are interpreted on Windows.
> > I'm on a fresh install of rc 4, only thing I've done was to add the widget from the docs and i'm getting the same error as @Petr-Hl:
> > ```
> > [plugin:vite:import-analysis] Failed to resolve import "C:codingmedusasrcadminwidgetsproduct-widget.tsx" 
> > from "virtual:medusa/widgets". Does the file exist?
> > virtual:medusa/widgets:1:60
> > 1  |  import WidgetComponent0, { config as WidgetConfig0 } from "C:\coding\medusa\src\admin\widgets\product-widget.tsx"
> >    |                                                             ^
> > 2  |  
> > 3  |  export default {
> > ```
> 
> I can confirm that this error is still happening in v2.0.4.
> 
> I am trying to copy / paste the code shown in this official docs tutorial https://docs.medusajs.com/learn/basics/admin-customizations but it is not working.

Are you getting this exact error where the path contains backwards slashes?

**Comment by LauschaNN** [comment] 2024-11-12 15:38
> > > Same problem here. I think it has to do with how paths are interpreted on Windows.
> > > I'm on a fresh install of rc 4, only thing I've done was to add the widget from the docs and i'm getting the same error as @Petr-Hl:
> > > ```
> > > [plugin:vite:import-analysis] Failed to resolve import "C:codingmedusasrcadminwidgetsproduct-widget.tsx" 
> > > from "virtual:medusa/widgets". Does the file exist?
> > > virtual:medusa/widgets:1:60
> > > 1  |  import WidgetComponent0, { config as WidgetConfig0 } from "C:\coding\medusa\src\admin\widgets\product-widget.tsx"
> > >    |                                                             ^
> > > 2  |  
> > > 3  |  export default {
> > > ```
> > 
> > 
> > I can confirm that this error is still happening in v2.0.4.
> > I am trying to copy / paste the code shown in this official docs tutorial https://docs.medusajs.com/learn/basics/admin-customizations but it is not working.
> 
> Are you getting this exact error where the path contains backwards slashes?

Nope, I am not running Medusa on Windows. To give you a bit more context, I am running Medusa dockerized.

This is my Dockerfile:

```dockerfile
FROM node:latest

WORKDIR /app/medusa

COPY . .

RUN apt-get update && apt-get install -y python3 python3-pip python-is-python3

RUN npm install 

RUN npm run build

CMD npm run db:migrate && npm run dev
```

This is the error that I am receiving:

```
2024-11-12 16:32:35 3:32:35 PM [vite] Internal server error: Failed to resolve import "/medusa/src/admin/widgets/product-widget.tsx" from "virtual:medusa/forms". Does the file exist?
2024-11-12 16:32:35   Plugin: vite:import-analysis
2024-11-12 16:32:35   File: virtual:medusa/forms:1:60
2024-11-12 16:32:35   1  |  import WidgetComponent0, { config as WidgetConfig0 } from "/app/medusa/src/admin/widgets/product-widget.tsx"
2024-11-12 16:32:35      |                                                             ^
2024-11-12 16:32:35   2  |  
2024-11-12 16:32:35   3  |  export default {
2024-11-12 16:32:35       at TransformPluginContext._formatError (file:///app/medusa/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:49255:41)
2024-11-12 16:32:35       at TransformPluginContext.error (file:///app/medusa/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:49250:16)
2024-11-12 16:32:35       at normalizeUrl (file:///app/medusa/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:64041:23)
2024-11-12 16:32:35       at async file:///app/medusa/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:64173:39
2024-11-12 16:32:35       at async Promise.all (index 0)
2024-11-12 16:32:35       at async TransformPluginContext.transform (file:///app/medusa/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:64100:7)
2024-11-12 16:32:35       at async PluginContainer.transform (file:///app/medusa/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:49096:18)
2024-11-12 16:32:35       at async loadAndTransform (file:///app/medusa/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:51929:27)
```

**Comment by kasperkristensen** [comment] 2024-11-12 15:42
> > > > Same problem here. I think it has to do with how paths are interpreted on Windows.
> > > > I'm on a fresh install of rc 4, only thing I've done was to add the widget from the docs and i'm getting the same error as @Petr-Hl:
> > > > ```
> > > > [plugin:vite:import-analysis] Failed to resolve import "C:codingmedusasrcadminwidgetsproduct-widget.tsx" 
> > > > from "virtual:medusa/widgets". Does the file exist?
> > > > virtual:medusa/widgets:1:60
> > > > 1  |  import WidgetComponent0, { config as WidgetConfig0 } from "C:\coding\medusa\src\admin\widgets\product-widget.tsx"
> > > >    |                                                             ^
> > > > 2  |  
> > > > 3  |  export default {
> > > > ```
> > > 
> > > 
> > > I can confirm that this error is still happening in v2.0.4.
> > > I am trying to copy / paste the code shown in this official docs tutorial https://docs.medusajs.com/learn/basics/admin-customizations but it is not working.
> > 
> > 
> > Are you getting this exact error where the path contains backwards slashes?
> 
> Nope, I am not running Medusa on Windows. To give you a bit more context, I am running Medusa dockerized.
> 
> This is my Dockerfile:
> 
> ```dockerfile
> FROM node:latest
> 
> WORKDIR /app/medusa
> 
> COPY . .
> 
> RUN apt-get update && apt-get install -y python3 python3-pip python-is-python3
> 
> RUN npm install 
> 
> RUN npm run build
> 
> CMD npm run db:migrate && npm run dev
> ```
> 
> This is the error that I am receiving:
> 
> ```
> 2024-11-12 16:32:35 3:32:35 PM [vite] Internal server error: Failed to resolve import "/medusa/src/admin/widgets/product-widget.tsx" from "virtual:medusa/forms". Does the file exist?
> 2024-11-12 16:32:35   Plugin: vite:import-analysis
> 2024-11-12 16:32:35   File: virtual:medusa/forms:1:60
> 2024-11-12 16:32:35   1  |  import WidgetComponent0, { config as WidgetConfig0 } from "/app/medusa/src/admin/widgets/product-widget.tsx"
> 2024-11-12 16:32:35      |                                                             ^
> 2024-11-12 16:32:35   2  |  
> 2024-11-12 16:32:35   3  |  export default {
> 2024-11-12 16:32:35       at TransformPluginContext._formatError (file:///app/medusa/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:49255:41)
> 2024-11-12 16:32:35       at TransformPluginContext.error (file:///app/medusa/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:49250:16)
> 2024-11-12 16:32:35       at normalizeUrl (file:///app/medusa/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:64041:23)
> 2024-11-12 16:32:35       at async file:///app/medusa/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:64173:39
> 2024-11-12 16:32:35       at async Promise.all (index 0)
> 2024-11-12 16:32:35       at async TransformPluginContext.transform (file:///app/medusa/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:64100:7)
> 2024-11-12 16:32:35       at async PluginContainer.transform (file:///app/medusa/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:49096:18)
> 2024-11-12 16:32:35       at async loadAndTransform (file:///app/medusa/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:51929:27)
> ```

Okay, so not the same issue, whats mentioned in this issue has been fixed so will close the issue. 

The issue you are facing happens because the root of your docker image is `/app` and your `path` in the admin options is also `/app` (this is the default value, so if you haven't provided a custom path then this will be used). The issue is described in our docs here: https://docs.medusajs.com/resources/troubleshooting/medusa-admin/no-widget-route#errors-in-docker. One option would be to change the path to `/dashboard`. If this does not fix your widgets loading, then please open a new issue 👍

**Closed as completed by kasperkristensen** 2024-11-12 15:42 UTC
Labels: status: needs triaging, version: 2.0

**Comment by LauschaNN** [comment] 2024-11-12 15:53
> > > > > Same problem here. I think it has to do with how paths are interpreted on Windows.
> > > > > I'm on a fresh install of rc 4, only thing I've done was to add the widget from the docs and i'm getting the same error as @Petr-Hl:
> > > > > ```
> > > > > [plugin:vite:import-analysis] Failed to resolve import "C:codingmedusasrcadminwidgetsproduct-widget.tsx" 
> > > > > from "virtual:medusa/widgets". Does the file exist?
> > > > > virtual:medusa/widgets:1:60
> > > > > 1  |  import WidgetComponent0, { config as WidgetConfig0 } from "C:\coding\medusa\src\admin\widgets\product-widget.tsx"
> > > > >    |                                                             ^
> > > > > 2  |  
> > > > > 3  |  export default {
> > > > > ```
> > > > 
> > > > 
> > > > I can confirm that this error is still happening in v2.0.4.
> > > > I am trying to copy / paste the code shown in this official docs tutorial https://docs.medusajs.com/learn/basics/admin-customizations but it is not working.
> > > 
> > > 
> > > Are you getting this exact error where the path contains backwards slashes?
> > 
> > 
> > Nope, I am not running Medusa on Windows. To give you a bit more context, I am running Medusa dockerized.
> > This is my Dockerfile:
> > ```dockerfile
> > FROM node:latest
> > 
> > WORKDIR /app/medusa
> > 
> > COPY . .
> > 
> > RUN apt-get update && apt-get install -y python3 python3-pip python-is-python3
> > 
> > RUN npm install 
> > 
> > RUN npm run build
> > 
> > CMD npm run db:migrate && npm run dev
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This is the error that I am receiving:
> > ```
> > 2024-11-12 16:32:35 3:32:35 PM [vite] Internal server error: Failed to resolve import "/medusa/src/admin/widgets/product-widget.tsx" from "virtual:medusa/forms". Does the file exist?
> > 2024-11-12 16:32:35   Plugin: vite:import-analysis
> > 2024-11-12 16:32:35   File: virtual:medusa/forms:1:60
> > 2024-11-12 16:32:35   1  |  import WidgetComponent0, { config as WidgetConfig0 } from "/app/medusa/src/admin/widgets/product-widget.tsx"
> > 2024-11-12 16:32:35      |                                                             ^
> > 2024-11-12 16:32:35   2  |  
> > 2024-11-12 16:32:35   3  |  export default {
> > 2024-11-12 16:32:35       at TransformPluginContext._formatError (file:///app/medusa/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:49255:41)
> > 2024-11-12 16:32:35       at TransformPluginContext.error (file:///app/medusa/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:49250:16)
> > 2024-11-12 16:32:35       at normalizeUrl (file:///app/medusa/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:64041:23)
> > 2024-11-12 16:32:35       at async file:///app/medusa/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:64173:39
> > 2024-11-12 16:32:35       at async Promise.all (index 0)
> > 2024-11-12 16:32:35       at async TransformPluginContext.transform (file:///app/medusa/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:64100:7)
> > 2024-11-12 16:32:35       at async PluginContainer.transform (file:///app/medusa/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:49096:18)
> > 2024-11-12 16:32:35       at async loadAndTransform (file:///app/medusa/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:51929:27)
> > ```
> 
> Okay, so not the same issue, whats mentioned in this issue has been fixed so will close the issue.
> 
> The issue you are facing happens because the root of your docker image is `/app` and your `path` in the admin options is also `/app` (this is the default value, so if you haven't provided a custom path then this will be used). The issue is described in our docs here: https://docs.medusajs.com/resources/troubleshooting/medusa-admin/no-widget-route#errors-in-docker. One option would be to change the path to `/dashboard`. If this does not fix your widgets loading, then please open a new issue 👍

Thank you so much! 
I didn't see the doc linked by you.
Now it's working as expected 🎉
