### ISSUE TITLE
TypeORMError: Entity metadata for Store#default_currency was not found

### ISSUE THREAD

**Issue by bytevault** [medusajs/medusa#8479] opened 2024-08-07 02:15 UTC
### Describe the bug

Error generating migration script when extending Store Entity

### System information

Medusa version (default dependencies from create-medusa): 1.20.9
Node.js version: 20.11.1
Database: postgres local
Operating system: MacOS 14.5

### Steps to reproduce the behavior

1. Extend store entity with customAttr: string
```ts
import {Column, Entity} from 'typeorm'
import {
  Store as MedusaStore
} from '@medusajs/medusa'

@Entity()
export class Store extends MedusaStore {
  @Column()
  customAttr: string
}

```
2. Run the following command to generate migrations
```
>> yarn build:server
>> typeorm migration:generate -d datasource.js src/migrations/extendStore
>> TypeORMError: Entity metadata for Store#default_currency was not found.
```

**Comment by srindom** [comment] 2024-08-07 09:26
Can you verify that you have run all migrations on your db before you added this customization?

This error usually happens if your schema in the code is out of sync with the schema in the database. Running migrations should fix it.

**Comment by bytevault** [comment] 2024-08-07 23:00
I can confirm that all migrations were ran before extending this entity

```
>>> medusa migrations run

query: SELECT * FROM current_schema()
query: SELECT version();
query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = 'public' AND "table_name" = 'migrations'
query: SELECT * FROM "public"."migrations" "migrations" ORDER BY "id" DESC
No migrations are pending
```

**Comment by srindom** [comment] 2024-08-13 07:42
@ByteVault - can I ask you to share a minimal reproduction. I am not able to reproduce locally with the information shared here.

**Comment by srindom** [comment] 2024-08-19 08:52
Closing for now - feel free to reopen if you have new information.

**Closed as completed by srindom** 2024-08-19 08:52 UTC
Labels: type: bug, status: needs triaging

**Comment by Vn-ChemGio** [comment] 2024-10-03 16:51
I got the same issue
When we create new model role, which relation ManyToOne with Store (which extends from MedusaStore)

``
import { BaseEntity } from '@medusajs/medusa';
import { generateEntityId } from '@medusajs/utils';
import { BeforeInsert, Column, Entity, Index, ManyToOne, OneToMany, Unique } from 'typeorm';
import { RolePermission } from './role-permission';
import { UserRole } from './user-role';
import { Store } from './store';

@Entity()
@Unique(['store_id', 'name'])
export class Role extends BaseEntity {
  @Index()
  @Column({ type: 'varchar', nullable: false, length: 100 })
  name: string;
  
  @Index()
  @Column({ nullable: true })
  store_id: string;
  //Reference with Store N-1
  @ManyToOne(() => Store, (store: Store) => store.roles, {
    cascade: ['remove'],
  })
  store: Store;
  
  @BeforeInsert()
  private beforeInsert(): void {
    this.id = generateEntityId(this.id, 'role');
  }
}
``

``

import { Store as MedusaStore } from '@medusajs/medusa';
import { Entity, OneToMany } from 'typeorm';
import { Role } from './role';

@Entity()
export class Store extends MedusaStore {
  //Reference with Role 1-Role
  @OneToMany(() => Role, (role: Role) => role.store, {
    onDelete: 'CASCADE',
  })
  roles: Role[];
}
``
then generate new migration with query bellow after build
```
npx typeorm migration:generate -d datasource.js src/migrations/ACL-Create
```
