### ISSUE TITLE
[Bug]: Admin portal throws 401 (Unauthorized)

### ISSUE THREAD

**Issue by homosape** [medusajs/medusa#10498] opened 2024-12-09 07:58 UTC
### Package.json file

```JSON
{
  "name": "",
  "version": "0.0.1",
  "author": "",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "dev": "medusa develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "^2.1.0",
    "@medusajs/cli": "^2.1.0",
    "@medusajs/framework": "^2.1.0",
    "@medusajs/medusa": "^2.1.0",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "awilix": "^8.0.1",
    "pg": "^8.13.0",
    "zod": "^3.22"
  },
  "devDependencies": {
    "@medusajs/test-utils": "^2.1.0",
    "@mikro-orm/cli": "5.9.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.6.2",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

v22.11.0

### Database and its version

supabase

### Operating system name and version

macOS Sequoia 15.1.1

### What happended?

I've detached medusa admin portal from medusa backend. 

My medusa backend is deployed to Google Cloud Run and admin portal to Firebase hosting.
When I try to log in to deployed admin portal with my user it immediately throws 401 Unauthorized. However, I'm able to login to admin portal when running backend locally.

This is th
<img width="1439" alt="Screenshot 2024-12-09 at 12 21 46" src="https://github.com/user-attachments/assets/38f55fed-6adb-4e16-adaf-2c15b3e8a244">
e error:

This is how my bitbucket pipelines look:
<img width="1199" alt="Screenshot 2024-12-09 at 11 57 26" src="https://github.com/user-attachments/assets/4846630e-5521-41ad-9402-1c21b6d2a886">

This is my medusa config:
```
import { loadEnv, defineConfig } from "@medusajs/framework/utils";

loadEnv(process.env.NODE_ENV || "development", process.cwd());

module.exports = defineConfig({
  modules: [
    {
      resolve: "@medusajs/medusa/payment",
      options: {
        providers: [
          {
            resolve: "./src/modules/bog",
            id: "bog-payment",
          },
        ],
      },
    },
    {
      resolve: "./src/modules/marketplace",
    },
    {
      resolve: "@medusajs/medusa/cache-redis",
      options: {
        redisUrl: process.env.REDIS_URL,
      },
    },
    {
      resolve: "@medusajs/medusa/event-bus-redis",
      options: {
        redisUrl: process.env.REDIS_URL,
      },
    },
    {
      resolve: "@medusajs/medusa/workflow-engine-redis",
      options: {
        redis: {
          url: process.env.REDIS_URL,
        },
      },
    },

  ],
  admin: {
    disable: process.env.DISABLE_MEDUSA_ADMIN === "true",
    backendUrl: process.env.MEDUSA_BACKEND_URL || "http://localhost:9000",
    storefrontUrl: process.env.MEDUSA_STOREFRONT_URL || "http://localhost:9000",
    path: (process.env.MEDUSA_ADMIN_PATH as `/${string}`) || "/app",
  },
  featureFlags: {
    analytics: false,
  },
  projectConfig: {
    workerMode: process.env.MEDUSA_WORKER_MODE as
      | "shared"
      | "worker"
      | "server",
    databaseUrl: process.env.DATABASE_URL,
    http: {
      storeCors: process.env.STORE_CORS!,
      adminCors: process.env.ADMIN_CORS!,
      authCors: process.env.AUTH_CORS!,
      jwtSecret: process.env.JWT_SECRET || "supersecret",
      cookieSecret: process.env.COOKIE_SECRET || "supersecret",
    },
  },
});
```

### Expected behavior

I should be able to log in to staging admin portal.

### Actual behavior

It throws 401 error when calling `admin/users/me` endpoint.

### Link to reproduction repo

n/a

**Comment by thetutlage** [comment] 2024-12-09 12:00
Hello @homosape 

The information you have provided is not enough for us to debug the issue. Please look at the logs of your deployed backend to ensure that everything is properly and the database connection is fine too.

Since, the same code works fine locally, it means there is some issue with your setup on Cloud run.

I will close the issue for now. However, feel free to comment here if you discover something wrong with Medusa codebase that leads to this behavior 👍

**Closed as completed by thetutlage** 2024-12-09 12:00 UTC
Labels: status: needs triaging, version: 2.0

**Comment by mk0y** [comment] 2024-12-13 19:16
For me this happens as well after upgrading to latest release. I sign in as admin and get logged out immediately. Not sure how to explain, since I don't know what's the cause of it. It just happened suddenly after upgrading. We have "latest" tag in package.json, we'll try lower versions to see if that will fix it temporally.

**Comment by bouazzaayyoub** [comment] 2025-02-13 16:21
> For me this happens as well after upgrading to latest release. I sign in as admin and get logged out immediately. Not sure how to explain, since I don't know what's the cause of it. It just happened suddenly after upgrading. We have "latest" tag in package.json, we'll try lower versions to see if that will fix it temporally.

Hello, did you find the issue? i have the same here

**Comment by sid69rawal** [comment] 2025-07-19 09:42
> > For me this happens as well after upgrading to latest release. I sign in as admin and get logged out immediately. Not sure how to explain, since I don't know what's the cause of it. It just happened suddenly after upgrading. We have "latest" tag in package.json, we'll try lower versions to see if that will fix it temporally.
> 
> Hello, did you find the issue? i have the same here

I have the same issue too? did anyone find it out @mk0y @bouazzaayyoub @homosape
