### ISSUE TITLE
[Bug]: Issue when call complete cart 

### ISSUE THREAD

**Issue by trinhcongduc** [medusajs/medusa#10191] opened 2024-11-21 01:52 UTC
### Package.json file

```JSON
{
  "name": "trustedo-medusas-backend",
  "version": "0.0.1",
  "description": "A TrustedO Medusa source",
  "author": "dukstry.com",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "start": "medusa start",
    "dev": "medusa develop",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "gen:root-user": "npx medusa user --email dukstry@gmail.com --password Demo@123a",
    "migrate:contentful": "./src/loaders/contentful-migrations/index.ts",
    "import:contentful": "contentful space import --space-id $CONTENTFUL_SPACE_ID --mt $CONTENTFUL_ACCESS_TOKEN --content-file  ./data/contentful-seed.json",
    "seed:contentful": "dotenv-run-script .env -- import:contentful",
    "docker:services": "bash docker-services/runAll.sh",
    "setup:first-run": "npx medusa db:migrate && yarn seed && yarn gen:root-user"`
  },
  "dependencies": {
    "@faker-js/faker": "^9.2.0",
    "@medusajs/admin-sdk": "latest",
    "@medusajs/cli": "latest",
    "@medusajs/event-bus-redis": "^2.0.4",
    "@medusajs/framework": "latest",
    "@medusajs/medusa": "latest",
    "@medusajs/workflow-engine-redis": "^2.0.4",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "cf-content-types-generator": "^2.15.5",
    "contentful": "^11.2.2",
    "medusa-file-minio": "^1.3.2",
    "medusa-payment-manual": "^1.0.25",
    "medusa-payment-stripe": "^6.0.11",
    "medusa-plugin-contentful": "^1.2.12",
    "medusa-plugin-meilisearch": "^2.0.11",
    "minio": "^8.0.2",
    "pg": "^8.13.0",
    "stripe": "^17.3.1",
    "typeorm": "^0.3.20",
    "typesense": "^1.8.2"
  },
  "devDependencies": {
    "@medusajs/test-utils": "latest",
    "@mikro-orm/cli": "5.9.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "contentful-migration": "^4.26.1",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

v21.7.3

### Database and its version

17.0

### Operating system name and version

MacOS

### What happended?
It happens when i trying to complete the card
<img width="1429" alt="image" src="https://github.com/user-attachments/assets/2c32c05f-05d7-4612-b81b-42ac93d3755a">
<img width="1024" alt="image" src="https://github.com/user-attachments/assets/3d28b038-460f-4d2b-a67c-aa472ee018bc">

### Expected behavior

Complete cart works well

### Actual behavior

Error

### Link to reproduction repo

https://github.com/trinhcongduc/medusajs-demo

**Comment by kasperkristensen** [comment] 2024-11-21 15:40
Hi @trinhcongduc, could you please provide some more info, such as a dump of the cart that fails when you try to complete it? Without more info its hard for us to pinpoint why you are experiencing this issue.

**Comment by sradevski** [comment] 2024-11-22 16:52
The link is broken, and there is no proper description on what the issue is, closing.

**Closed as completed by sradevski** 2024-11-22 16:52 UTC
Labels: status: needs triaging, version: 2.0, awaiting-more-information
