### ISSUE TITLE
[BUG] Create new medusa app does not request for a admin email forcing us to create it by CLI in Linux

### ISSUE THREAD

**Issue by SalahAdDin** [medusajs/medusa#9294] opened 2024-09-25 00:43 UTC
### Describe the bug

When creating a new Medusa application we don't see the CLI asking us for an admin email, i.e., it does not ask for creating a default admin user.

In Medusa v1.x it does ask.

### System information

Medusa version (including plugins):
```
"@medusajs/admin-sdk": "preview",
    "@medusajs/api-key": "preview",
    "@medusajs/auth": "preview",
    "@medusajs/auth-emailpass": "preview",
    "@medusajs/cache-inmemory": "preview",
    "@medusajs/cart": "preview",
    "@medusajs/currency": "preview",
    "@medusajs/customer": "preview",
    "@medusajs/event-bus-local": "preview",
    "@medusajs/file": "preview",
    "@medusajs/file-local-next": "preview",
    "@medusajs/fulfillment": "preview",
    "@medusajs/fulfillment-manual": "preview",
    "@medusajs/inventory-next": "preview",
    "@medusajs/medusa": "preview",
    "@medusajs/medusa-cli": "preview",
    "@medusajs/notification": "preview",
    "@medusajs/notification-local": "preview",
    "@medusajs/order": "preview",
    "@medusajs/payment": "preview",
    "@medusajs/pricing": "preview",
    "@medusajs/product": "preview",
    "@medusajs/promotion": "preview",
    "@medusajs/region": "preview",
    "@medusajs/sales-channel": "preview",
    "@medusajs/stock-location-next": "preview",
    "@medusajs/store": "preview",
    "@medusajs/tax": "preview",
    "@medusajs/user": "preview",
    "@medusajs/workflow-engine-inmemory": "preview",
```
Node.js version: v20.15.1
Database: Postgre SQL 13
Operating system: Manjaro Linux
Browser (if relevant): Firefox

### Steps to reproduce the behavior

1. In shell `pnpx create-medusa-app@preview`
2. Give the required data
3. See admin user question is not being asked

### Expected behavior
As the prior version it should ask for the admin user.

### Screenshots

Medusa v1.x
![image](https://github.com/user-attachments/assets/5795c456-7f2e-479f-bfc6-950539b9862e)

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by SalahAdDin** [comment] 2024-09-25 00:59
**UPDATE**:
I checked on Medusa `1.20.9` with admin `7.1.16`, and it seems it is unable to open Firefox-based browsers.
 
Despite we chose the default given email, it seems the user was not created:
```
::ffff:127.0.0.1 - - [25/Sep/2024:00:47:39 +0000] "OPTIONS /admin/auth HTTP/1.1" 204 0 "http://localhost:7001/" "Mozilla/5.0 (X11; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0"
error:   User with email: admin@medusa-test.com was not found
```

**Comment by shahednasser** [comment] 2024-09-25 06:00
Regarding the original issue, it's inteded that we don't ask the admin email. You can enter it when the Medusa application opens and you create a user.

> I checked on Medusa 1.20.9 with admin 7.1.16, and it seems it is unable to open Firefox-based browsers.

Will look into this

**Comment by shahednasser** [comment] 2024-09-25 06:47
@SalahAdDin I can't reproduce the issue with the browser not opening in v1. Can you share more details about the browser and OS?

> Despite we chose the default given email, it seems the user was not created:

The user is created when the browser when is opened, but as you mentioned it's not opening for you.

**Comment by SalahAdDin** [comment] 2024-09-25 16:15
> @SalahAdDin I can't reproduce the issue with the browser not opening in v1. Can you share more details about the browser and OS?
> 
> > Despite we chose the default given email, it seems the user was not created:
> 
> The user is created when the browser when is opened, but as you mentioned it's not opening for you.

Yeah, I realized that sister, I guess Medusa is unable to open a Firefox browser.

**Comment by shahednasser** [comment] 2024-09-26 06:27
It worked fine with my firefox browser. Can you share your OS / browser version details?

**Comment by SalahAdDin** [comment] 2024-09-26 13:22
Of course:
```bash
██████████████████  ████████   luisalaguna@luis-rogstrixscar18g 
██████████████████  ████████   -------------------------------- 
██████████████████  ████████   OS: Manjaro Linux x86_64 
██████████████████  ████████   Host: ROG Strix SCAR 18 G834JYR_G834JYR 1.0 
████████            ████████   Kernel: 6.11.0-rc4-7-MANJARO 
████████  ████████  ████████   Uptime: 20 hours, 58 mins 
████████  ████████  ████████   Packages: 1375 (pacman) 
████████  ████████  ████████   Shell: bash 5.2.32 
████████  ████████  ████████   Resolution: 3440x1440 
████████  ████████  ████████   DE: Plasma 6.0.5 
████████  ████████  ████████   WM: kwin 
████████  ████████  ████████   Theme: Breeze [GTK2/3] 
████████  ████████  ████████   Icons: McMojave-circle [GTK2/3] 
████████  ████████  ████████   Terminal: konsole 
                               CPU: Intel i9-14900HX (32) @ 5.600GHz 
                               GPU: NVIDIA 01:00.0 NVIDIA Corporation GN21-X11 
                               GPU: Intel Raptor Lake-S UHD Graphics 
                               Memory: 12250MiB / 31710MiB 
``` 

And: 
![image](https://github.com/user-attachments/assets/04b195a2-a3b1-4a75-ad1b-8c5aa0c6fd0d)

**Comment by shahednasser** [comment] 2024-09-26 13:27
Alright thanks, will take some time to look into it to see what the issue possibly is

**Comment by SalahAdDin** [comment] 2024-09-26 14:44
No problem.

**Comment by sradevski** [comment] 2024-12-26 13:21
@SalahAdDin is this still an issue on the latest 2.x release? I also couldn't reproduce, so it also might be something related to the OS you are using. I'll close the issue, but please let me know if the issue persists and if you can try it on a different OS.

**Closed as completed by sradevski** 2024-12-26 13:21 UTC

**Comment by SalahAdDin** [comment] 2024-12-31 04:24
> @SalahAdDin is this still an issue on the latest 2.x release? I also couldn't reproduce, so it also might be something related to the OS you are using. I'll close the issue, but please let me know if the issue persists and if you can try it on a different OS.

I will check it soon.

**Comment by SalahAdDin** [comment] 2025-02-25 21:57
> [@SalahAdDin](https://github.com/SalahAdDin) is this still an issue on the latest 2.x release? I also couldn't reproduce, so it also might be something related to the OS you are using. I'll close the issue, but please let me know if the issue persists and if you can try it on a different OS.

@sradevski Yes, it is happening in Medusa 2:

![Image](https://github.com/user-attachments/assets/e05c9e1a-0e59-47a1-bce4-90ccbd54cb74)

It does not ask for user.

**Comment by SalahAdDin** [comment] 2025-02-25 22:10
My setup:
```bash
    /media/Storage/Projects/Experiments/e-commerce/test2  neofetch                                                                                                                                          ✔  5s  
██████████████████  ████████   luisalaguna@luis-rogstrixscar18g 
██████████████████  ████████   -------------------------------- 
██████████████████  ████████   OS: Manjaro Linux x86_64 
██████████████████  ████████   Host: ROG Strix SCAR 18 G834JYR_G834JYR 1.0 
████████                                   ████████   Kernel: 6.13.1-2-MANJARO 
████████  ████████  ████████   Uptime: 5 hours, 10 mins 
████████  ████████  ████████   Packages: 1392 (pacman) 
████████  ████████  ████████   Shell: bash 5.2.37 
████████  ████████  ████████   Resolution: 2560x1600 
████████  ████████  ████████   DE: Plasma 6.2.5 
████████  ████████  ████████   WM: kwin 
████████  ████████  ████████   Theme: Breeze [GTK2/3] 
████████  ████████  ████████   Icons: McMojave-circle [GTK2/3] 
████████  ████████  ████████   Terminal: vscode 
                               CPU: Intel i9-14900HX (32) @ 5.600GHz 
                               GPU: Intel Raptor Lake-S UHD Graphics 
                               GPU: NVIDIA GeForce RTX 4090 Laptop GPU 
                               Memory: 18360MiB / 31707MiB
```
