### ISSUE TITLE
Missing Modal for ProductCategoryProduct 

### ISSUE THREAD

**Issue by jagadeesh-si** [medusajs/medusa#6941] opened 2024-04-04 13:30 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

What:
There is no ProductCategoryProduct modal for ProductCategoryProduct Entity

why:
To create custom service : In my case i need productCategoryProduct modal to do inner join with productVariant modal

### How can this issue be resolved?

.

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment] 2024-04-04 14:01
Closing this as it's a duplicate of another issue

**Closed as completed by shahednasser** 2024-04-04 14:01 UTC
Labels: type: docs

**Comment by jagadeesh-si** [comment] 2024-04-04 14:22
Please share me link of the duplicate issue

**Comment by shahednasser** [comment] 2024-04-04 15:16
You created it in this issue #6940
